Repository keras-team/keras, pull requests merged in 2021-09, with the labels that each got.

#15200 adapt EarlyStopping auto mode to auc
  keras/callbacks.py
Labels: ready to pull, cla: yes, size:XS

#15288 change misleading description of m_mul
  keras/optimizer_v2/learning_rate_schedule.py
Labels: ready to pull, cla: yes, size:XS

#15295 The latest update.Hope it can suit you
  keras/layers/preprocessing/benchmarks/image_preproc_benchmark.py
Labels: ready to pull, cla: yes, size:XS

#15318 Fixed and added ValueError for `plot_model`, `model_to_dot` and `model.summary()`
  keras/engine/training.py
  keras/utils/vis_utils.py
Labels: ready to pull, cla: yes, size:S

#15321 Fix a minor typo in CIFAR-10 and CIFAR-100 description
  keras/datasets/cifar10.py
  keras/datasets/cifar100.py
Labels: kokoro:force-run, ready to pull, cla: yes, size:XS

#15326 Fix cropping2D empty list #15325
  keras/layers/convolutional.py
  keras/layers/convolutional_test.py
Labels: ready to pull, cla: yes, size:S

#15363 convert label_smoothing dtype to y dtype
  keras/losses.py
  keras/losses_test.py
Labels: ready to pull, cla: yes, size:S

#15343 Exclude default bazel paths for VsCode
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: ready to pull, cla: yes, awaiting review, size:S

#15370 fix: typo in SeparableConv1D
  keras/layers/convolutional.py
Labels: ready to pull, cla: yes, size:XS

#15385 Add user bin path for pip installed packages
  .devcontainer/Dockerfile
Labels: ready to pull, cla: yes, awaiting review, size:XS

#15315 Reopening #48000, #48491, #48610 from tensorflow/tensorflow
  keras/layers/convolutional.py
  keras/layers/convolutional_test.py
  keras/layers/local.py
  keras/layers/local_test.py
Labels: kokoro:force-run, ready to pull, cla: yes, size:M

#15355 `expand_nested` bug fix and changing `model.summary` style
  keras/utils/layer_utils.py
  keras/utils/layer_utils_test.py
Labels: kokoro:force-run, ready to pull, cla: yes, awaiting review, size:XS

#15399 unnecessary casting and condition removed
  keras/activations.py
Labels: ready to pull, cla: yes, size:XS

#15286 Bug fix for issue #15211, PR #15233 ("Plot model show activations")
  keras/utils/vis_utils.py
  keras/utils/vis_utils_test.py
Labels: ready to pull, cla: yes, size:S

#15422 fix a bug: when use tf.keras.layers.TextVectorization layer to load model
  keras/layers/preprocessing/text_vectorization.py
Labels: kokoro:force-run, ready to pull, cla: yes, size:XS

#15423 added correct initialisation for MHA
  keras/layers/multi_head_attention.py
Labels: ready to pull, cla: yes, size:XS
