Repository keras-team/keras, pull requests merged in 2021-12, with the labels that each got.

#15723 doc: add link to SciKeras migration guide
  keras/wrappers/scikit_learn.py
Labels: ready to pull, cla: yes, awaiting review, size:XS

#15683 Fix a minor typo in the docstring
  keras/preprocessing/timeseries.py
Labels: ready to pull, cla: yes, size:XS

#15718 Fixed docstrings in keras/optimizer_v2/learning_rate_schedule.py
  keras/optimizer_v2/learning_rate_schedule.py
Labels: ready to pull, cla: yes, awaiting review, size:S

#15720 Implement compute_output_shape for BaseDenseAttention
  keras/layers/dense_attention.py
  keras/layers/wrappers_test.py
Labels: ready to pull, cla: yes, awaiting review, size:M

#15814 Update README.md
  README.md
Labels: kokoro:force-run, ready to pull, size:XS

#15819 Update_OptimizerV2.py
  keras/optimizer_v2/optimizer_v2.py
Labels: ready to pull, keras-team-review-pending, awaiting review, size:XS

#15773 Use `assign_sub` when computing `moving_average_update`
  keras/backend.py
Labels: ready to pull, size:XS
