Repository keras-team/keras, pull requests merged in 2021-07, with the labels that each got.

#14861 add patterns to .gitignore
  .gitignore
Labels: cla: yes, ready to pull

#14817 Clarify documentation of DepthwiseConv2D
  keras/layers/convolutional.py
Labels: cla: yes, ready to pull

#14881 Add more explicit error message for instance type checking of optimizer.
  keras/mixed_precision/loss_scale_optimizer.py
  keras/mixed_precision/loss_scale_optimizer_test.py
Labels: cla: yes

#14865 Make model summary wrap
  keras/utils/layer_utils.py
Labels: cla: yes, ready to pull

#14901 Update the link in Estimator
  keras/estimator/__init__.py
Labels: cla: yes, ready to pull

#14905 Fix RNN, StackedRNNCells with nested state_size, output_size TypeError issues
  keras/layers/recurrent.py
  keras/layers/recurrent_test.py
Labels: cla: yes, kokoro:force-run, ready to pull

#14917 Fix the use of imagenet_utils.preprocess_input within a Lambda layer with mixed precision
  keras/applications/imagenet_utils.py
  keras/applications/imagenet_utils_test.py
Labels: cla: yes, ready to pull

#14920 Fix docstrings in `MultiHeadAttention layer` call argument `return_attention_scores`.
  keras/layers/multi_head_attention.py
Labels: cla: yes, ready to pull

#14903 Check if layer has _metrics_lock attribute
  keras/engine/base_layer.py
Labels: cla: yes, ready to pull

#14748 Make keras.Model picklable
  keras/engine/training.py
  keras/saving/BUILD
  keras/saving/pickle_utils.py
  keras/saving/pickle_utils_test.py
Labels: cla: yes, ready to pull

#14946 Fix typo in docs
  keras/layers/recurrent.py
Labels: cla: yes, ready to pull

#14948 use getter setter
  keras/optimizer_v2/optimizer_v2.py
Labels: cla: yes, ready to pull

#14414 Close _SESSION.session in clear_session
  keras/backend.py
Labels: cla: yes, ready to pull

#14952 Add default value in Attention layer docs #50839
  keras/layers/dense_attention.py
Labels: cla: yes, ready to pull

#14991 Update 00-bug-template.md
  .github/ISSUE_TEMPLATE/00-bug-template.md
Labels: cla: yes

#15015 Remove cast of y_true to y_pred data type in sparse categorical cross entropy loss
  keras/losses.py
Labels: cla: yes, ready to pull
