Repository keras-team/keras, pull requests merged in 2021-08, with the labels that each got.

#14982 Fix clone_model to consider input_tensors
  keras/models.py
  keras/models_test.py
Labels: cla: yes, ready to pull

#15062 Cherrypick security fixes into 2.6 release
  keras/engine/functional.py
  keras/engine/functional_test.py
  keras/engine/training.py
  keras/saving/model_config.py
Labels: cla: yes

#15058 Fix docs about GRU and cuDNN.
  keras/layers/__init__.py
  keras/layers/gru_v2_test.py
  keras/layers/lstm_v2_test.py
  keras/layers/recurrent.py
  keras/layers/recurrent_v2.py
  keras/saving/hdf5_format.py
Labels: cla: yes, ready to pull

#14989 fix: typo spelling
  keras/benchmarks/eager_microbenchmarks_test.py
  keras/benchmarks/layer_benchmarks/layer_benchmarks_test.py
  keras/distribute/distribute_strategy_test.py
  keras/engine/compile_utils.py
  keras/engine/keras_tensor.py
  keras/engine/training_utils.py
  keras/layers/preprocessing/preprocessing_stage.py
  keras/mixed_precision/loss_scale_optimizer.py
  keras/optimizer_v2/optimizer_v2.py
  keras/preprocessing/image_dataset.py
  keras/preprocessing/text_dataset.py
Labels: cla: yes, ready to pull

#15063 update contributing guide
  CONTRIBUTING.md
Labels: ready to pull, cla: yes

#15075 Make python code in Sequential docs consistent
  keras/engine/sequential.py
Labels: ready to pull, cla: yes

#15176 Create stale.yml
  .github/stale.yml
Labels: kokoro:force-run, ready to pull, cla: yes, awaiting review, size:S

#15133 Update Contributing Guide
  CONTRIBUTING.md
Labels: cla: yes

#15177 fix "rbg" -> "rgb" in image_dataset_from_directory
  keras/preprocessing/image_dataset.py
Labels: ready to pull, cla: yes, size:XS

#15197 Log the best epoch when restoring the best weights in early stopping
  keras/callbacks.py
Labels: ready to pull, cla: yes, awaiting review, size:XS

#15189 update contributing guide
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
Labels: ready to pull, cla: yes, awaiting review

#15201 fix __array__ for numpy support
  keras/engine/keras_tensor.py
Labels: ready to pull, cla: yes, awaiting review, size:XS

#15195 Update training.py
  keras/engine/training.py
Labels: ready to pull, cla: yes, size:XS

#15222 [Follow-up for #15197] Fix a log message for weight restoration in early stopping
  keras/callbacks.py
Labels: ready to pull, cla: yes, size:XS

#14970 fix cropping layer return empty list if crop is higher than data shape
  keras/layers/convolutional.py
  keras/layers/convolutional_test.py
Labels: ready to pull, cla: yes, awaiting review

#15209 Specify `stacklevel` for `warnings.warn` to make it easier to identify which lines throw warnings
  keras/applications/efficientnet_weight_update_util.py
  keras/applications/imagenet_utils.py
  keras/backend.py
  keras/engine/base_layer.py
  keras/engine/base_layer_v1.py
  keras/engine/functional.py
  keras/engine/training.py
  keras/engine/training_v1.py
  keras/layers/core/lambda_layer.py
  keras/layers/legacy_rnn/rnn_cell_impl.py
  keras/layers/legacy_rnn/rnn_cell_wrapper_impl.py
  keras/layers/recurrent.py
  keras/legacy_tf_layers/base.py
  keras/legacy_tf_layers/convolutional.py
  keras/legacy_tf_layers/core.py
  keras/legacy_tf_layers/normalization.py
  keras/legacy_tf_layers/pooling.py
  keras/metrics.py
  keras/optimizer_v2/optimizer_v2.py
  keras/saving/saved_model_experimental.py
  keras/utils/generic_utils.py
  keras/wrappers/scikit_learn.py
Labels: ready to pull, cla: yes, size:S
