Repository keras-team/keras, pull requests merged in 2021-11, with the labels that each got.

#15543 Fix typos
  CONTRIBUTING.md
  keras/applications/mobilenet_v2.py
  keras/benchmarks/BUILD
  keras/benchmarks/keras_examples_benchmarks/antirectifier_benchmark_test.py
  keras/callbacks.py
  keras/distribute/BUILD
  keras/engine/BUILD
  keras/engine/base_layer.py
  keras/engine/base_layer_v1.py
  keras/engine/data_adapter.py
  keras/engine/functional.py
  keras/engine/functional_utils_test.py
  keras/engine/training_test.py
  keras/initializers/initializers_v1.py
  keras/integration_test/BUILD
  keras/integration_test/parameter_server_keras_preprocessing_test.py
  keras/integration_test/preprocessing_test_utils.py
  keras/integration_test/tpu_strategy_test.py
  keras/layers/convolutional.py
  keras/layers/core/core_test.py
  keras/layers/core/lambda_layer.py
  keras/layers/core/tf_op_layer.py
  keras/layers/normalization/layer_normalization_test.py
  keras/layers/preprocessing/discretization.py
  keras/layers/preprocessing/hashing.py
  keras/layers/preprocessing/index_lookup.py
  keras/layers/preprocessing/preprocessing_stage.py
  keras/layers/wrappers.py
  keras/losses.py
  keras/metrics.py
  keras/models.py
  keras/optimizer_experimental/optimizer.py
  keras/optimizer_v2/optimizer_v2.py
  keras/regularizers.py
  keras/saving/saved_model/layer_serialization.py
  keras/saving/saved_model/load.py
  keras/utils/data_utils.py
  keras/utils/generic_utils.py
  keras/utils/kpl_test_utils.py
  keras/utils/metrics_utils.py
  keras/utils/vis_utils.py
Labels: ready to pull, cla: yes, awaiting review, size:M

#15447 Update the contribution guide to include a applications section
  CONTRIBUTING.md
Labels: ready to pull, cla: yes, size:S

#15551 chore: replace os.path.join with tf.io.gfile.join
  keras/saving/pickle_utils.py
  keras/saving/saved_model/load.py
  keras/saving/saved_model/save.py
  keras/saving/saved_model_experimental.py
  keras/saving/utils_v1/export_utils.py
Labels: ready to pull, cla: yes, awaiting review, size:S

#15626 Fixing typos.
  CONTRIBUTING.md
Labels: ready to pull, cla: yes, size:XS

#15604 Updating the documentation of MAPE
  keras/losses.py
Labels: type:docs, ready to pull, cla: yes, awaiting review, size:XS

#15639 Fix typo
  keras/utils/losses_utils.py
Labels: ready to pull, cla: yes, awaiting review, size:XS

#15640 [Docs] Changed typo ModelNetV3 to MobileNetV3.
  keras/applications/mobilenet_v3.py
Labels: ready to pull, cla: yes, awaiting review, size:XS

#15646 Adding a choice not to make batches in `timeseries_dataset_from_array`
  keras/preprocessing/image_dataset.py
  keras/preprocessing/image_dataset_test.py
  keras/preprocessing/text_dataset.py
  keras/preprocessing/text_dataset_test.py
  keras/preprocessing/timeseries.py
  keras/preprocessing/timeseries_test.py
Labels: cla: yes, size:XS

#15612 Bypass the require a config warning for marge layers
  keras/layers/merge.py
Labels: ready to pull, cla: yes, size:XS

#15264 Allow keras.utils.Sequence sub-classes to use sparse/ragged tensors
  keras/engine/data_adapter.py
  keras/engine/data_adapter_test.py
Labels: ready to pull, cla: yes, size:M

#15520 fix backend _GRAPH_LEARNING_PHASES graph circular reference.
  keras/backend.py
Labels: ready to pull, cla: yes, awaiting review, size:M
