Repository keras-team/keras, pull requests merged in 2022-08, with the labels that each got.

#16839 Incorrectly rendered table
  keras/applications/mobilenet.py
  keras/applications/mobilenet_v2.py
  keras/applications/nasnet.py
Labels: type:docs, ready to pull, size:S

#16856 Add `is_legacy_optimizer` to optimizer config to keep saving/loading …
  keras/mixed_precision/loss_scale_optimizer.py
  keras/optimizers/__init__.py
  keras/optimizers/optimizer_experimental/optimizer.py
  keras/optimizers/optimizer_experimental/optimizer_test.py
Labels: size:S

#16864 Update `tf.keras.preprocessing.image*` to `tf.keras.utils*`
  keras/utils/image_utils.py
Labels: ready to pull, size:S

#16877 Updating get_file() to respect KERAS_HOME environment variable
  keras/utils/data_utils.py
Labels: ready to pull, size:XS

#16893 Fix docs of `metrics` parameter in `compile`
  keras/engine/training.py
Labels: kokoro:force-run, ready to pull, size:XS

#16874 [Refactoring] making the code more Succinct and Pythonic
  keras/utils/layer_utils_test.py
  keras/utils/text_dataset_test.py
Labels: ready to pull, size:M

#16929 Fix Value Error for Units of tf.keras.layers.LSTM
  keras/layers/rnn/lstm.py
Labels: ready to pull, keras-team-review-pending, size:XS

#16926 Fix Value error for Units of tf.keras.layers.SimpleRNN
  keras/layers/rnn/simple_rnn.py
Labels: ready to pull, keras-team-review-pending, size:XS

#16921 Fix value error for Units of tf.keras.layers.Dense
  keras/layers/core/dense.py
Labels: ready to pull, size:XS

#16937 Fixed: #16936 broken hyperlink
  keras/applications/resnet_v2.py
Labels: ready to pull, size:XS
