Repository keras-team/keras, pull requests merged in 2022-04, with the labels that each got.

#16326 Fix typos in data_adapter.py
  keras/engine/data_adapter.py
Labels: ready to pull, size:S

#16364 Typo fix in LSTM docstring
  keras/layers/rnn/lstm.py
Labels: ready to pull, size:XS

#16360 Copy loss and metric to prevent side effect
  keras/engine/compile_utils.py
  keras/engine/compile_utils_test.py
Labels: ready to pull, size:S

#16379 Cherrypick Keras DTensor related updates into keras 2.9
  keras/dtensor/BUILD
  keras/dtensor/__init__.py
  keras/dtensor/initializers_test.py
  keras/dtensor/layers_test.py
  keras/dtensor/layout_map_test.py
  keras/dtensor/metrics_test.py
  keras/dtensor/mnist_model_test.py
  keras/dtensor/optimizers_test.py
  keras/dtensor/test_util.py
  keras/dtensor/utils_test.py
  keras/optimizers/optimizer_experimental/BUILD
  keras/tools/pip_package/BUILD
  keras/tools/pip_package/create_pip_helper.py
Labels: size:M

#16413 Add subset="both" functionality to {image|text}_dataset_from_directory()
  keras/utils/dataset_utils.py
  keras/utils/image_dataset.py
  keras/utils/image_dataset_test.py
  keras/utils/text_dataset.py
  keras/utils/text_dataset_test.py
Labels: ready to pull, size:XL

#16434 Cherrypick DTensor docstring fix for 2.9 release.
  keras/dtensor/layout_map.py
  keras/dtensor/optimizers.py
Labels: size:M

#16435 Cherrypick for RandomContrast update
  keras/layers/preprocessing/image_preprocessing.py
Labels: keras-team-review-pending, size:XS

#16402 Fix non-float32 efficientnet calls
  keras/applications/efficientnet.py
Labels: ready to pull, size:XS

#16408 Fix prediction with structured output
  keras/engine/training.py
  keras/engine/training_test.py
Labels: ready to pull, size:XS

#16409 Add reference to resource variables.
  keras/engine/base_layer.py
Labels: ready to pull, size:XS

#16454 Cherrypick ImageAugmetation related change to R2.9
  keras/layers/preprocessing/image_preprocessing.py
Labels: size:XS

#16447 Fix Syntax error for combined_model.compile of WideDeepModel
  keras/premade_models/wide_deep.py
Labels: ready to pull, size:XS

#16459 Missing `f` prefix on f-strings fix
  keras/applications/mobilenet.py
  keras/benchmarks/keras_examples_benchmarks/text_classification_transformer_benchmark_test.py
  keras/dtensor/layout_map.py
  keras/dtensor/lazy_variable.py
  keras/engine/base_layer.py
  keras/layers/rnn/cell_wrappers.py
  keras/layers/rnn/legacy_cell_wrappers.py
  keras/layers/rnn/legacy_cells.py
  keras/optimizers/optimizer_v2/optimizer_v2.py
  keras/saving/utils_v1/signature_def_utils.py
  keras/utils/audio_dataset.py
Labels: ready to pull, size:S
