Repository keras-team/keras, pull requests merged in 2022-03, with the labels that each got.

#16145 Fixed EfficientNetV2 b parameter not increasing with each block.
  keras/applications/efficientnet_v2.py
Labels: ready to pull, size:XS

#16147 Updated args of train_on_batch method
  keras/engine/training.py
Labels: ready to pull, size:XS

#16083 Binary accuracy bug fixes - Metric accuracy method refactor
  keras/metrics/metrics.py
  keras/utils/metrics_utils.py
  keras/utils/metrics_utils_test.py
Labels: ready to pull, size:M

#16165 Fix typo in docstring for `DenseFeatures`
  keras/feature_column/dense_features_v2.py
Labels: ready to pull, size:XS

#16182 Fix typo in Returns Section
  keras/layers/preprocessing/text_vectorization.py
Labels: ready to pull, size:XS

#16198 Add .DS_Store to .gitignore for macOS users
  .gitignore
  README.md
Labels: ready to pull, keras-team-review-pending, size:XS

#16259 Update README.md
  README.md
Labels: ready to pull, size:XS

#16253 Fix documentation text being mistakenly rendered as code
  keras/utils/dataset_utils.py
  keras/utils/image_dataset.py
  keras/utils/text_dataset.py
Labels: ready to pull, size:XS

#16230 Allow single input for merging layers Add, Average, Concatenate, Maximum, Minimum, Multiply
  keras/layers/merging/add.py
  keras/layers/merging/average.py
  keras/layers/merging/base_merge.py
  keras/layers/merging/concatenate.py
  keras/layers/merging/maximum.py
  keras/layers/merging/merging_test.py
  keras/layers/merging/minimum.py
  keras/layers/merging/multiply.py
Labels: kokoro:force-run, ready to pull, size:S

#16232 Mention image dimensions format in image_dataset_from_directory
  keras/utils/image_dataset.py
Labels: ready to pull, size:XS

#16249 Implement all tf interpolation upscaling methods
  keras/backend.py
  keras/layers/reshaping/up_sampling2d.py
Labels: ready to pull, size:S

#16332 Fix TypeError positional argument when LossScalerOptimizer is used conjointly with tfa wrappers
  keras/mixed_precision/loss_scale_optimizer.py
Labels: ready to pull, size:XS

#16208 Add type check to axis
  keras/losses.py
Labels: ready to pull, size:XS
