Repository keras-team/keras, pull requests merged in 2022-01, with the labels that each got.

#15817 Document the verbose parameter in EarlyStopping
  keras/callbacks.py
Labels: ready to pull, keras-team-review-pending, awaiting review, size:XS

#15756 Fix LSTM and GRU cuDNN kernel failure for RaggedTensors.
  keras/layers/recurrent_v2.py
  keras/layers/recurrent_v2_test.py
Labels: ready to pull, size:S

#15862 Cherrypick: Compute LSTM and GRU via cuDNN for RaggedTensors.
  keras/layers/recurrent_v2.py
  keras/layers/recurrent_v2_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:M

#15847 A tiny problem in an AttributeError message in base_layer.py
  keras/engine/base_layer.py
Labels: ready to pull, cla: yes, size:XS

#15876 Update training_generator_test.py
  keras/engine/training_generator_test.py
Labels: ready to pull, size:XS

#15924 refactoring code with List Comprehension
  keras/callbacks_test.py
Labels: ready to pull, size:XS

#15930 added clarifying statement to save_model example text
  keras/saving/save.py
Labels: ready to pull, keras-team-review-pending, size:XS

#15943 Update base_conv.py
  keras/layers/convolutional/base_conv.py
Labels: ready to pull, size:XS

#15938 Update global_clipnorm
  keras/optimizer_v2/adadelta.py
  keras/optimizer_v2/adagrad.py
  keras/optimizer_v2/adam.py
  keras/optimizer_v2/adamax.py
  keras/optimizer_v2/ftrl.py
  keras/optimizer_v2/gradient_descent.py
  keras/optimizer_v2/nadam.py
  keras/optimizer_v2/rmsprop.py
Labels: ready to pull, keras-team-review-pending, size:S

#15977 Update callbacks.py
  keras/callbacks.py
Labels: ready to pull, size:XS
