Repository keras-team/keras, pull requests merged in 2022-10, with the labels that each got.

#17096 Fix typos in docstrings
  keras/callbacks.py
  keras/losses.py
Labels: ready to pull, size:XS

#16922 More Tests for customizable reduction strategy in model
  keras/distribute/multi_worker_test.py
  keras/distribute/multi_worker_testing_utils.py
  keras/engine/training.py
Labels: ready to pull, keras-team-review-pending, size:M

#17065 Fix Batch Normalization inference behavior when virtual_batch_size is set
  keras/layers/normalization/batch_normalization.py
  keras/layers/normalization/batch_normalization_test.py
Labels: ready to pull, size:S

#17119 Include dictionary comprehension
  keras/legacy_tf_layers/normalization_test.py
Labels: ready to pull, size:XS

#17068 Fixes ConvNeXt and RegNet when input_tensor is given
  keras/applications/convnext.py
  keras/applications/regnet.py
Labels: ready to pull, size:XS

#17153 Cherrypick the fix for zlib
  WORKSPACE
Labels: size:XS

#17160 Cherrypick all the fixes since last branch cut to r2.11.
  WORKSPACE
  keras/BUILD
  keras/backend.py
  keras/engine/compile_utils_test.py
  keras/engine/training_test.py
  keras/engine/training_v1.py
  keras/losses.py
Labels: size:M

#17165 Cherrypick 2 more changes for the optimizer docstring fix.
  keras/mixed_precision/loss_scale_optimizer.py
  keras/optimizers/__init__.py
  keras/optimizers/optimizer_experimental/optimizer.py
Labels: size:XS

#17179 Cherrypick for cl/482011499: Throw error on deprecated fields.
  keras/optimizers/optimizer_experimental/optimizer.py
  keras/optimizers/optimizer_experimental/optimizer_test.py
Labels: keras-team-review-pending, size:S

#17170 Changed .format to f-string for better readability
  keras/layers/preprocessing/image_preprocessing.py
Labels: ready to pull, size:S

#17111 Use the fallback method for GRU and LSTM on ROCm if padded I/O is needed
  keras/layers/rnn/BUILD
  keras/layers/rnn/gru.py
  keras/layers/rnn/gru_lstm_utils.py
  keras/layers/rnn/gru_test.py
  keras/layers/rnn/lstm.py
  keras/layers/rnn/lstm_test.py
Labels: ready to pull, size:M
