Repository keras-team/keras, pull requests merged in 2022-05, with the labels that each got.

#15998 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready to pull, size:XS

#16398 adds split_dataset utility
  keras/utils/BUILD
  keras/utils/__init__.py
  keras/utils/dataset_utils.py
  keras/utils/dataset_utils_test.py
Labels: ready to pull, size:M

#16521 Fix OrthogonalRegularizer to implement the (1,1) matrix norm
  keras/regularizers.py
Labels: ready to pull, size:XS

#16528 fix: weight keys so that imagenet init works
  keras/applications/convnext.py
Labels: ready to pull, size:S

#16527 Preprocess input correction
  keras/applications/convnext.py
  keras/applications/regnet.py
Labels: ready to pull, size:XS

#16534 Fix typo in documentation
  keras/layers/preprocessing/index_lookup.py
  keras/layers/preprocessing/integer_lookup.py
  keras/layers/preprocessing/string_lookup.py
Labels: ready to pull, size:XS

#16460 Update index_lookup.py
  keras/layers/preprocessing/index_lookup.py
Labels: ready to pull, size:XS

#16575 update codespaces bazel install
  .devcontainer/Dockerfile
Labels: ready to pull, size:S

#16568 Fix typos
  README.md
  keras/applications/efficientnet.py
  keras/benchmarks/keras_examples_benchmarks/README.md
  keras/callbacks_test.py
  keras/datasets/reuters.py
  keras/dtensor/layout_map.py
  keras/layers/preprocessing/integer_lookup.py
  keras/layers/preprocessing/string_lookup.py
  keras/layers/preprocessing/text_vectorization.py
  keras/layers/rnn/lstm_test.py
  keras/legacy_tf_layers/base_test.py
  keras/legacy_tf_layers/variable_scope_shim_test.py
Labels: ready to pull, keras-team-review-pending, size:S

#16571 Fix mixed precision serialization of group convs
  keras/layers/convolutional/base_conv.py
Labels: ready to pull, size:XS

#16584 resolve line-too-long in root directory
  keras/activations.py
  keras/backend.py
  keras/backend_config.py
  keras/backend_test.py
  keras/callbacks.py
  keras/callbacks_test.py
  keras/callbacks_v1.py
  keras/callbacks_v1_test.py
  keras/constraints.py
  keras/losses.py
  keras/losses_test.py
  keras/regularizers.py
  keras/regularizers_test.py
Labels: ready to pull, size:XL

#16586 resolve line-too-long in metrics
  keras/metrics/__init__.py
  keras/metrics/base_metric.py
  keras/metrics/base_metric_test.py
  keras/metrics/confusion_matrix_test.py
  keras/metrics/metrics.py
  keras/metrics/metrics_correctness_test.py
  keras/metrics/metrics_functional_test.py
  keras/metrics/metrics_test.py
Labels: ready to pull, size:L

#16587 resolve line-too-long in optimizers
  keras/optimizers/__init__.py
  keras/optimizers/legacy_learning_rate_decay.py
  keras/optimizers/optimizer_experimental/adadelta.py
  keras/optimizers/optimizer_experimental/adamax.py
  keras/optimizers/optimizer_experimental/adamw.py
  keras/optimizers/optimizer_experimental/ftrl.py
  keras/optimizers/optimizer_experimental/optimizer.py
  keras/optimizers/optimizer_experimental/optimizer_pss_test.py
  keras/optimizers/optimizer_experimental/optimizer_test.py
  keras/optimizers/optimizer_experimental/sgd.py
  keras/optimizers/optimizer_v1.py
  keras/optimizers/optimizer_v2/adadelta.py
  keras/optimizers/optimizer_v2/adadelta_test.py
  keras/optimizers/optimizer_v2/adagrad.py
  keras/optimizers/optimizer_v2/adam.py
  keras/optimizers/optimizer_v2/adam_test.py
  keras/optimizers/optimizer_v2/adamax_test.py
  keras/optimizers/optimizer_v2/ftrl.py
  keras/optimizers/optimizer_v2/ftrl_test.py
  keras/optimizers/optimizer_v2/gradient_descent.py
  keras/optimizers/optimizer_v2/gradient_descent_test.py
  keras/optimizers/optimizer_v2/nadam.py
  keras/optimizers/optimizer_v2/optimizer_v2.py
  keras/optimizers/optimizer_v2/optimizer_v2_test.py
  keras/optimizers/optimizer_v2/rmsprop.py
  keras/optimizers/optimizer_v2/rmsprop_test.py
  keras/optimizers/optimizer_v2/utils.py
  keras/optimizers/schedules/learning_rate_schedule.py
Labels: ready to pull, size:XL

#16594 resolve line-too-long in distribute
  keras/distribute/collective_all_reduce_strategy_test.py
  keras/distribute/ctl_correctness_test.py
  keras/distribute/custom_training_loop_metrics_test.py
  keras/distribute/custom_training_loop_models_test.py
  keras/distribute/dataset_creator_model_fit_test.py
  keras/distribute/distribute_coordinator_utils.py
  keras/distribute/distribute_strategy_test.py
  keras/distribute/distributed_file_utils.py
  keras/distribute/distributed_training_utils_v1.py
  keras/distribute/keras_correctness_test_base.py
  keras/distribute/keras_dnn_correctness_test.py
  keras/distribute/keras_embedding_model_correctness_test.py
  keras/distribute/keras_metrics_test.py
  keras/distribute/keras_optimizer_v2_test.py
  keras/distribute/keras_premade_models_test.py
  keras/distribute/keras_utils_test.py
  keras/distribute/minimize_loss_test.py
  keras/distribute/mirrored_variable_test.py
  keras/distribute/multi_worker_callback_tf2_test.py
  keras/distribute/multi_worker_test.py
  keras/distribute/multi_worker_testing_utils.py
  keras/distribute/optimizer_combinations.py
  keras/distribute/parameter_server_evaluation_test.py
  keras/distribute/saved_model_save_load_test.py
  keras/distribute/saved_model_test_base.py
  keras/distribute/sharded_variable_test.py
  keras/distribute/sidecar_evaluator.py
  keras/distribute/sidecar_evaluator_test.py
  keras/distribute/test_example.py
  keras/distribute/worker_training_state.py
Labels: ready to pull, size:XL

#16599 resolve line-too-long in integration_test
  keras/integration_test/custom_object_saving_test.py
  keras/integration_test/distributed_training_test.py
  keras/integration_test/forwardprop_test.py
  keras/integration_test/function_test.py
  keras/integration_test/gradient_checkpoint_test.py
  keras/integration_test/legacy_rnn_test.py
  keras/integration_test/multi_worker_tutorial_test.py
  keras/integration_test/mwms_multi_process_runner_test.py
  keras/integration_test/preprocessing_applied_in_dataset_creator_test.py
  keras/integration_test/preprocessing_applied_in_model_test.py
Labels: ready to pull, size:M

#16600 resovle line-too-long in legacy-tf-layers
  keras/legacy_tf_layers/base.py
  keras/legacy_tf_layers/base_test.py
  keras/legacy_tf_layers/convolutional.py
  keras/legacy_tf_layers/convolutional_test.py
  keras/legacy_tf_layers/core.py
  keras/legacy_tf_layers/core_test.py
  keras/legacy_tf_layers/migration_utils.py
  keras/legacy_tf_layers/migration_utils_test.py
  keras/legacy_tf_layers/normalization.py
  keras/legacy_tf_layers/normalization_test.py
  keras/legacy_tf_layers/pooling.py
  keras/legacy_tf_layers/variable_scope_shim.py
  keras/legacy_tf_layers/variable_scope_shim_test.py
Labels: ready to pull, size:L

#16598 resolve line-too-long in initializers
  keras/initializers/__init__.py
  keras/initializers/initializers_test.py
  keras/initializers/initializers_v1.py
  keras/initializers/initializers_v2.py
Labels: ready to pull, size:M

#16592 resolve line-too-long in api
  keras/api/tests/api_compatibility_test.py
Labels: ready to pull, size:S

#16593 resolve line-too-long in benchmarks
  keras/benchmarks/benchmark_util.py
  keras/benchmarks/distribution_util.py
  keras/benchmarks/eager_microbenchmarks_test.py
  keras/benchmarks/keras_examples_benchmarks/cifar10_cnn_benchmark_test.py
  keras/benchmarks/keras_examples_benchmarks/mnist_conv_custom_training_benchmark_test.py
  keras/benchmarks/keras_examples_benchmarks/text_classification_transformer_benchmark_test.py
  keras/benchmarks/layer_benchmarks/run_xprof.py
  keras/benchmarks/metrics_memory_benchmark_test.py
  keras/benchmarks/optimizer_benchmarks_test.py
Labels: ready to pull, size:M

#16597 resolve line-too-long in feature_column
  keras/feature_column/base_feature_layer.py
  keras/feature_column/dense_features.py
  keras/feature_column/dense_features_test.py
  keras/feature_column/dense_features_v2.py
  keras/feature_column/dense_features_v2_test.py
  keras/feature_column/sequence_feature_column.py
  keras/feature_column/sequence_feature_column_test.py
Labels: ready to pull, size:M

#16591 resolve line-too-long in datasets
  keras/datasets/imdb.py
  keras/datasets/reuters.py
Labels: ready to pull, size:XS

#16595 resolve line-too-long in dtensor
  keras/dtensor/__init__.py
  keras/dtensor/initializers_test.py
  keras/dtensor/layout_map.py
  keras/dtensor/layout_map_test.py
  keras/dtensor/lazy_variable.py
  keras/dtensor/mnist_model_test.py
  keras/dtensor/optimizers.py
  keras/dtensor/test_util.py
  keras/dtensor/utils.py
Labels: ready to pull, size:M

#16596 resolve line-too-long in estimator
  keras/estimator/__init__.py
Labels: ready to pull, size:M

#16590 resolve line-too-long in applications
  keras/applications/convnext.py
  keras/applications/efficientnet.py
  keras/applications/efficientnet_v2.py
  keras/applications/inception_resnet_v2.py
  keras/applications/inception_v3.py
  keras/applications/mobilenet_v2.py
  keras/applications/mobilenet_v3.py
  keras/applications/nasnet.py
  keras/applications/regnet.py
  keras/applications/resnet_rs.py
  keras/applications/vgg16.py
  keras/applications/vgg19.py
Labels: ready to pull, size:L

#16605 resolve line-too-long in mixed_precision
  keras/mixed_precision/autocast_variable.py
  keras/mixed_precision/autocast_variable_test.py
  keras/mixed_precision/device_compatibility_check.py
  keras/mixed_precision/device_compatibility_check_test.py
  keras/mixed_precision/layer_correctness_test.py
  keras/mixed_precision/layer_test.py
  keras/mixed_precision/loss_scale_optimizer.py
  keras/mixed_precision/loss_scale_optimizer_test.py
  keras/mixed_precision/mixed_precision_graph_rewrite_test.py
  keras/mixed_precision/model_test.py
  keras/mixed_precision/policy.py
  keras/mixed_precision/policy_test.py
  keras/mixed_precision/test_util.py
Labels: ready to pull, size:L

#16606 resolve line-too-long in models
  keras/models/cloning.py
  keras/models/cloning_test.py
  keras/models/sharpness_aware_minimization.py
Labels: ready to pull, size:M

#16608 resolve line-too-long in premade_models
  keras/premade_models/linear.py
  keras/premade_models/wide_deep.py
Labels: ready to pull, size:S

#16613 resolve line-too-long in tests
  keras/tests/automatic_outside_compilation_test.py
  keras/tests/convert_to_constants_test.py
  keras/tests/integration_test.py
  keras/tests/model_subclassing_compiled_test.py
  keras/tests/model_subclassing_test_util.py
  keras/tests/temporal_sample_weights_correctness_test.py
  keras/tests/tracking_test.py
  keras/tests/tracking_util_test.py
  keras/tests/tracking_util_with_v1_optimizers_test.py
Labels: ready to pull, keras-team-review-pending, size:M

#16612 resolve line-too-long in testing_infra
  keras/testing_infra/keras_doctest_lib.py
  keras/testing_infra/test_combinations.py
  keras/testing_infra/test_utils.py
Labels: ready to pull, keras-team-review-pending, size:M

#16611 resolve line-too-long in saving
  keras/saving/experimental/saving_lib.py
  keras/saving/experimental/saving_lib_test.py
  keras/saving/hdf5_format.py
  keras/saving/pickle_utils_test.py
  keras/saving/save.py
  keras/saving/save_test.py
  keras/saving/save_weights_test.py
  keras/saving/saved_model/base_serialization.py
  keras/saving/saved_model/json_utils.py
  keras/saving/saved_model/layer_serialization.py
  keras/saving/saved_model/load.py
  keras/saving/saved_model/model_serialization.py
  keras/saving/saved_model/order_preserving_set.py
  keras/saving/saved_model/revive_test.py
  keras/saving/saved_model/save.py
  keras/saving/saved_model/save_impl.py
  keras/saving/saved_model/saved_model_test.py
  keras/saving/saved_model/serialized_attributes.py
  keras/saving/saved_model/utils.py
  keras/saving/saved_model_experimental.py
  keras/saving/saved_model_experimental_test.py
  keras/saving/saving_utils.py
  keras/saving/saving_utils_test.py
  keras/saving/utils_v1/export_output.py
  keras/saving/utils_v1/export_utils.py
  keras/saving/utils_v1/mode_keys.py
  keras/saving/utils_v1/signature_def_utils.py
Labels: ready to pull, keras-team-review-pending, size:XL

#16609 resolve line-too-long in preprocessing
  keras/preprocessing/image.py
  keras/preprocessing/image_test.py
  keras/preprocessing/sequence_test.py
  keras/preprocessing/text.py
  keras/preprocessing/text_test.py
Labels: ready to pull, keras-team-review-pending, size:L

#16614 resolve line-too-long in utils
  keras/tools/pip_package/create_pip_helper.py
  keras/utils/audio_dataset.py
  keras/utils/audio_dataset_test.py
  keras/utils/composite_tensor_support_test.py
  keras/utils/control_flow_util.py
  keras/utils/conv_utils.py
  keras/utils/data_utils.py
  keras/utils/dataset_creator.py
  keras/utils/dataset_utils.py
  keras/utils/generic_utils.py
  keras/utils/generic_utils_test.py
  keras/utils/image_dataset.py
  keras/utils/image_dataset_test.py
  keras/utils/image_utils.py
  keras/utils/kernelized_utils.py
  keras/utils/kernelized_utils_test.py
  keras/utils/kpl_test_utils.py
  keras/utils/layer_utils.py
  keras/utils/layer_utils_test.py
  keras/utils/losses_utils.py
  keras/utils/metrics_utils.py
  keras/utils/metrics_utils_test.py
  keras/utils/object_identity.py
  keras/utils/text_dataset.py
  keras/utils/text_dataset_test.py
  keras/utils/tf_inspect.py
  keras/utils/tf_utils.py
  keras/utils/timeseries_dataset.py
  keras/utils/timeseries_dataset_test.py
  keras/utils/traceback_utils.py
  keras/utils/version_utils.py
  keras/utils/vis_utils.py
Labels: ready to pull, keras-team-review-pending, size:XL

#16537 Optimize L2 Regularizer (use tf.nn.l2_loss)
  keras/regularizers.py
Labels: ready to pull, size:XS

#16607 Fix typo
  keras/engine/training.py
Labels: ready to pull, keras-team-review-pending, size:XS

#16604 Explicitely set `AutoShardPolicy.DATA` for `TensorLike` datasets
  keras/engine/data_adapter.py
Labels: ready to pull, keras-team-review-pending, size:XS

#16621 Fix all flake8 errors
  keras/api/create_python_api_wrapper.py
  keras/backend.py
  keras/benchmarks/layer_benchmarks/run_xprof.py
  keras/callbacks.py
  keras/callbacks_test.py
  keras/distribute/worker_training_state.py
  keras/dtensor/lazy_variable.py
  keras/engine/base_layer.py
  keras/engine/base_layer_v1.py
  keras/engine/functional.py
  keras/engine/saving.py
  keras/engine/sequential.py
  keras/engine/training.py
  keras/engine/training_test.py
  keras/integration_test/multi_worker_tutorial_test.py
  keras/layers/noise.py
  keras/layers/normalization/batch_normalization.py
  keras/layers/serialization.py
  keras/legacy_tf_layers/migration_utils_test.py
  keras/preprocessing/image.py
  keras/saving/saved_model/load.py
  keras/saving/saved_model/saved_model_test.py
  keras/saving/saved_model/utils.py
  keras/saving/saving_utils.py
  keras/saving/utils_v1/__init__.py
  keras/testing_infra/keras_doctest_lib_test.py
  keras/tests/keras_doctest.py
  keras/utils/data_utils.py
  keras/utils/dataset_utils_test.py
  keras/utils/layer_utils.py
  keras/utils/mode_keys.py
  setup.cfg
Labels: ready to pull, size:XL
