Repository keras-team/keras, pull requests merged in 2022-09, with the labels that each got.

#16963 Fix Value error of tf.keras.layers.GRU
  keras/layers/rnn/gru.py
Labels: ready to pull, size:XS

#16870 PR for solving issue #16797
  keras/engine/base_layer.py
  keras/engine/base_layer_test.py
Labels: ready to pull, size:S

#17025 Add imports to base_rnn example
  keras/layers/rnn/base_rnn.py
Labels: ready to pull, size:XS

#17034 Update conv layer docs to reflect lack of CPU support for channels_first
  keras/layers/convolutional/conv1d.py
  keras/layers/convolutional/conv2d.py
  keras/layers/convolutional/conv3d.py
Labels: ready to pull, keras-team-review-pending, size:S

#17038 Fixed Broken link of paper jozefowicz15 et al
  keras/layers/rnn/lstm.py
Labels: ready to pull, keras-team-review-pending, size:XS

#17050 GitHub Workflows security hardening
  .github/workflows/format.yml
  .github/workflows/lint.yml
Labels: ready to pull, size:XS

#17054 Update normalization.py to fix a bug when "denormalizing"
  keras/layers/preprocessing/normalization.py
  keras/layers/preprocessing/normalization_test.py
Labels: ready to pull, size:XS

#17081 Fix IndexError when outs is empty
  keras/engine/training_distributed_v1.py
Labels: ready to pull, size:XS
