Repository keras-team/keras, pull requests merged in 2023-08, with the labels that each got.

#18314 typo in disable_interactie_logging
  keras/utils/io_utils.py
Labels: ready to pull, size:XS

#18332 Removes Python 3.8 support
  oss_setup.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#17632 Fix ModelCheckpoint trained-on batch counting when using steps_per_execution>1
  keras/callbacks.py
  keras/callbacks_test.py
Labels: stat:awaiting keras-team, ready to pull, size:XS
