Repository keras-team/keras, pull requests merged in 2023-03, with the labels that each got.

#17595 grammar corrections
  keras/layers/preprocessing/text_vectorization.py
Labels: ready to pull, size:XS

#17667 Correct the docstring of Head func in convnext.py
  keras/applications/convnext.py
  keras/applications/regnet.py
Labels: ready to pull, keras-team-review-pending, size:XS

#17636 fix a small bug in tf.keras.layer.Layer.compute_output_signature
  keras/engine/base_layer.py
Labels: ready to pull, size:S

#17638 Optimize mixed-precision finite check for sparse tensors.
  keras/mixed_precision/loss_scale_optimizer.py
Labels: stat:awaiting response from contributor, ready to pull, size:XS

#17726 Typo Lion docstring
  keras/optimizers/lion.py
Labels: ready to pull, size:XS

#16755 Raise ValueError if reducing axis dimension is 0
  keras/layers/pooling/base_global_pooling1d.py
  keras/layers/pooling/base_global_pooling2d.py
  keras/layers/pooling/base_global_pooling3d.py
  keras/layers/pooling/global_average_pooling_test.py
  keras/layers/pooling/global_max_pooling_test.py
Labels: ready to pull, size:S

#17742 Unifying interpolation selection
  keras/layers/reshaping/up_sampling2d.py
Labels: ready to pull, size:S
