Repository keras-team/keras, pull requests merged in 2023-10, with the labels that each got.

#18534 Apply `backend.result_type` to `bincount`, `substract`, `matmul`, `multiply`, `mean` and `max`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18550 Fix for torch2.1.0
  keras/backend/torch/optimizers/torch_optimizer.py
  keras/backend/torch/optimizers/torch_parallel_optimizer.py
  keras/layers/reshaping/up_sampling2d.py
Labels: kokoro:force-run, ready to pull, size:XS

#18538 Add threshold support to `BinaryAccuracy`
  keras/metrics/accuracy_metrics.py
  keras/metrics/accuracy_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18540 Add a shim so tf.estimators and downstream packages import
  keras/optimizers/__init__.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18549 Adds GPU CI for TensorFlow
  keras/kokoro/github/ubuntu/gpu/build.sh
  keras/kokoro/github/ubuntu/gpu/tensorflow/continuous.cfg
  keras/kokoro/github/ubuntu/gpu/tensorflow/presubmit.cfg
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18547 Fix issues with tensordot on torch backend
  keras/backend/torch/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:S, awaiting review

#18548 Apply `backend.result_type` to `absolute`, `argmax`, `argmin`, `argsort`, `ceil`, `clip` and `dot`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull

#18546 Update writing_a_custom_training_loop_in_jax.py
  guides/writing_a_custom_training_loop_in_jax.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:XS, awaiting review

#18483 Add tests for `mixed_precision` + `variables`
  keras/backend/common/variables.py
  keras/backend/common/variables_test.py
  keras/mixed_precision/dtype_policy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18552 Generalize tf and torch dataset check in case path is not strict prefix
  keras/trainers/data_adapters/__init__.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18553 Convert padding to lower case, so `same` and `SAME` are equivalent
  keras/ops/nn.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18554 Update Torch Req to 2.1.0
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18557 TensorFlow GPU CI - Green
  keras/kokoro/github/ubuntu/gpu/build.sh
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18498 Torch Wrapper Serialize
  keras/utils/torch_utils.py
  keras/utils/torch_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18559 Ignore error on upload to codecov
  .github/workflows/actions.yml
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18536 Add sharding constraint for the output tensor in the model
  keras/backend/jax/core.py
  keras/backend/jax/distribution_lib.py
  keras/backend/jax/trainer.py
  keras/distribution/distribution_lib.py
  keras/distribution/distribution_lib_test.py
  keras/layers/layer.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18555 Update layout_map to use re.search instead of re.match.
  keras/distribution/distribution_lib.py
  keras/distribution/distribution_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18566 Add cuda installation instructions
  README.md
  requirements-cuda.txt
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18562 Add JAX and Torch GPU Test setup
  keras/kokoro/github/ubuntu/gpu/jax/continuous.cfg
  keras/kokoro/github/ubuntu/gpu/jax/presubmit.cfg
  keras/kokoro/github/ubuntu/gpu/torch/continuous.cfg
  keras/kokoro/github/ubuntu/gpu/torch/presubmit.cfg
Labels: ready to pull, size:S, awaiting review

#18544 Update reduction_metrics.py
  keras/metrics/reduction_metrics.py
  keras/metrics/reduction_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18571 Fix BackupRestore Test for TensorFlow GPU CI
  keras/callbacks/backup_and_restore_callback_test.py
  keras/kokoro/github/ubuntu/gpu/build.sh
Labels: kokoro:force-run, ready to pull, size:XS

#18573 Fix format and uncomment TF GPU embedding test
  keras/kokoro/github/ubuntu/gpu/build.sh
  keras/metrics/reduction_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#18537 Increase test coverage `keras/layers/core/`
  keras/layers/core/dense_test.py
  keras/layers/core/embedding_test.py
  keras/layers/core/input_layer_test.py
  keras/layers/core/wrapper_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18581 Pin tf-nightly
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS

#18580 Add Torch, JAX GPU CI
  keras/kokoro/github/ubuntu/gpu/build.sh
  keras/kokoro/github/ubuntu/gpu/jax/continuous.cfg
  keras/kokoro/github/ubuntu/gpu/jax/presubmit.cfg
  keras/kokoro/github/ubuntu/gpu/tensorflow/continuous.cfg
  keras/kokoro/github/ubuntu/gpu/tensorflow/presubmit.cfg
  keras/kokoro/github/ubuntu/gpu/torch/continuous.cfg
  keras/kokoro/github/ubuntu/gpu/torch/presubmit.cfg
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18563 No-op for torch.no_grad if torch<2.1.0
  keras/backend/torch/optimizers/torch_optimizer.py
  keras/backend/torch/optimizers/torch_parallel_optimizer.py
  keras/utils/torch_utils.py
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:S

#18584 Replace `Tensorflow` with `numpy` for `nn_test`
  keras/kokoro/github/ubuntu/gpu/build.sh
  keras/layers/convolutional/conv_transpose_test.py
  keras/layers/pooling/average_pooling_test.py
  keras/layers/pooling/max_pooling_test.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:XL, awaiting review

#18585 Fix torch gpu tensors in `tf.data.Dataset` - `flatten_test.py`
  keras/kokoro/github/ubuntu/gpu/build.sh
  keras/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18588 Add additional path separator normalization
  keras/saving/saving_lib.py
Labels: kokoro:force-run, ready to pull, size:S

#18587 Split the jax distribution backend test into separate file.
  keras/backend/jax/distribution_lib_test.py
  keras/distribution/distribution_lib_test.py
  keras/kokoro/github/ubuntu/gpu/build.sh
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18551 Add multi-process/worker support for JAX distribution.
  keras/backend/jax/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18586 Increase test coverage in `keras/random`
  keras/random/random_test.py
  keras/random/seed_generator_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:M

#18589 Skip feature_space `test_saving` unless backend is `TensorFlow`
  keras/kokoro/github/ubuntu/gpu/build.sh
  keras/layers/preprocessing/feature_space.py
  keras/layers/preprocessing/feature_space_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18590 Expand battle test coverage for saving library
  keras/ops/operation.py
  keras/saving/saving_lib_test.py
  keras/saving/serialization_lib.py
Labels: kokoro:force-run, ready to pull, size:L

#18595 Extend test coverage for TF SavedModel
  keras/backend/tensorflow/saved_model_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18596 Add initialization logic for multi-worker/process distribution.
  keras/backend/jax/distribution_lib.py
  keras/backend/jax/distribution_lib_test.py
  keras/distribution/distribution_lib.py
  keras/distribution/distribution_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18603 Fixed clone_model with no inputs
  keras/models/cloning.py
  keras/models/cloning_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18591 Supervised contrastive learning
  examples/keras_io/vision/supervised_contrastive_learning.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18602 Add dataset related function for multi worker/process distribution.
  keras/backend/jax/distribution_lib.py
  keras/backend/jax/distribution_lib_test.py
  keras/distribution/distribution_lib.py
  keras/distribution/distribution_lib_test.py
Labels: ready to pull, size:M, awaiting review

#18607 Move kokoro CI folder to top level
  kokoro/github/ubuntu/gpu/build.sh
  kokoro/github/ubuntu/gpu/jax/continuous.cfg
  kokoro/github/ubuntu/gpu/jax/presubmit.cfg
  kokoro/github/ubuntu/gpu/tensorflow/continuous.cfg
  kokoro/github/ubuntu/gpu/tensorflow/presubmit.cfg
  kokoro/github/ubuntu/gpu/torch/continuous.cfg
  kokoro/github/ubuntu/gpu/torch/presubmit.cfg
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18610 Fix TensorFlow LSTM Masking Layer Issue
  keras/backend/tensorflow/rnn.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18611 Fix kokoro continuous env. variable for backend
  kokoro/README.md
  kokoro/github/ubuntu/gpu/build.sh
  kokoro/github/ubuntu/gpu/jax/continuous.cfg
  kokoro/github/ubuntu/gpu/tensorflow/continuous.cfg
  kokoro/github/ubuntu/gpu/torch/continuous.cfg
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18612 Fixed typo timeseries_anomaly_detection.py
  examples/keras_io/timeseries/timeseries_anomaly_detection.py
Labels: kokoro:force-run, ready to pull, size:XS

#18609 Keras nightly pip
  .github/workflows/nightly.yml
  pip_build.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18615 Distribution tests causing core dump on JAX GPU
  kokoro/github/ubuntu/gpu/build.sh
Labels: kokoro:force-run, ready to pull, size:XS

#18569 (re)enable torch.compile in the pytorch trainer for train, predict, and eval
  keras/backend/common/global_state.py
  keras/backend/torch/core.py
  keras/backend/torch/numpy.py
  keras/backend/torch/random.py
  keras/backend/torch/trainer.py
  keras/layers/reshaping/flatten.py
  keras/layers/reshaping/up_sampling2d.py
  keras/testing/test_case.py
  keras/trainers/epoch_iterator.py
  keras/trainers/trainer.py
  keras/trainers/trainer_test.py
  keras/utils/naming_test.py
  requirements.txt
Labels: size:M

#18616 Fix: typos at mask propagation test in `MultiHeadAttention`
  keras/layers/attention/multi_head_attention_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18617 Fix nightly pip
  .github/workflows/nightly.yml
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18619 Fix serialising index lookup when the input vocabulary is a numpy array
  keras/layers/preprocessing/index_lookup.py
Labels: kokoro:force-run, ready to pull, size:XS

#18618 Increase test coverage in `common/dtypes_test.py`
  keras/backend/common/dtypes_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18623 Use PyPa Action to upload
  .github/workflows/nightly.yml
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18629 Uninstall pypi keras from TF in GitHub Actions
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18628 Switch from tensor reshape to ops.reshape
  keras/ops/nn.py
Labels: kokoro:force-run, ready to pull, size:S

#18626 Add `named_product` test utility to generate test cases with names.
  keras/backend/common/dtypes_test.py
  keras/ops/numpy_test.py
  keras/testing/test_utils.py
  keras/testing/test_utils_test.py
Labels: kokoro:force-run, ready to pull, size:L

#18635 Fixed typo in adafactor.py
  keras/optimizers/adafactor.py
Labels: kokoro:force-run, ready to pull, size:XS

#18632 Keras io example : PixelCNN
  examples/keras_io/generative/pixelcnn.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18641 Fix torch reshape
  keras/backend/torch/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#18631 Keras IO example - GPT2 Text Generation with KerasNLP
  examples/keras_io/generative/gpt2_text_generation_with_kerasnlp.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18644 Update line 543 in metrics_utils.py
  keras/metrics/metrics_utils.py
Labels: kokoro:force-run, ready to pull, size:XS

#18643 Change import statement of keras_core in README.md
  README.md
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18645 Fixed typo in adafactor.py
  keras/optimizers/adafactor.py
Labels: kokoro:force-run, ready to pull, size:XS

#18639 Increase test coverage in `constraints_test` and `backup_and_restore_callback_test`
  keras/callbacks/backup_and_restore_callback_test.py
  keras/constraints/constraints_test.py
Labels: ready to pull, size:S, awaiting review

#18630 Use torch._dynamo.disable (versus torch.compiler.disable) and version…
  keras/backend/torch/random.py
  keras/backend/torch/trainer.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:S, awaiting review

#18656 Manually pad the tensor only when needed
  keras/backend/torch/nn.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18655 Avoid import tensorflow directly
  keras/distribution/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18663 ensure the main process raise an exception when the subprocess fails
  integration_tests/import_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18660 Disable traceback filtering after clearing session for tests
  keras/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18649 Add `quantile` and `median`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18664 Increase test coverage in `layers`
  keras/layers/regularization/dropout_test.py
  keras/layers/reshaping/cropping1d_test.py
  keras/layers/reshaping/cropping2d_test.py
  keras/layers/reshaping/cropping3d_test.py
  keras/layers/reshaping/repeat_vector_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18488 Add `GroupedQueryAttention` layer
  keras/layers/__init__.py
  keras/layers/attention/grouped_query_attention.py
  keras/layers/attention/grouped_query_attention_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18659 Set evaluation epoch iterator object to None for each model.fit call
  keras/backend/jax/trainer.py
  keras/backend/tensorflow/trainer.py
  keras/backend/torch/trainer.py
  keras/trainers/trainer_test.py
Labels: stat:awaiting response from contributor, kokoro:force-run, ready to pull, size:XS

#18665 Increase test coverage
  keras/initializers/random_initializers_test.py
  keras/random/random_test.py
  keras/random/seed_generator_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#18671 Implement syncbn for TensorFlow
  keras/layers/normalization/batch_normalization.py
Labels: size:M

#18661 use cpu for backends when not testing on gpu
  requirements-jax-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18675 Fix numpy conversion for tf MirroredVariable.
  integration_tests/tf_distribute_training_test.py
  keras/backend/common/variables.py
  keras/backend/common/variables_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18677 Add unit test for sync batch norm under distribution strategy.
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18654 Add multi-worker support for JAX training.
  keras/backend/jax/core.py
  keras/backend/jax/distribution_lib.py
  keras/backend/jax/distribution_lib_test.py
  keras/backend/jax/trainer.py
  keras/distribution/distribution_lib.py
  keras/trainers/data_adapters/__init__.py
  keras/trainers/data_adapters/tf_dataset_adapter.py
  keras/trainers/data_adapters/tf_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18503 Add `pad_to_bounding_box` image ops
  keras/ops/image.py
  keras/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18678 Validate alpha argument in leaky relu
  keras/layers/activations/leaky_relu.py
Labels: kokoro:force-run, ready to pull, size:XS

#18682 Restore hacky workaround for tf dict wrapper errors
  keras/models/model_test.py
  keras/ops/function.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18633 Add `tf.SparseTensor` and `tf.IndexedSlices` support to a number of T…
  keras/backend/common/dtypes_test.py
  keras/backend/tensorflow/core.py
  keras/backend/tensorflow/numpy.py
  keras/backend/tensorflow/sparse.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:XL

#18684 Improve dtype compatibility in `ops.numpy`
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L

#18691 Fix the loss scale optimizer for tf.distribute.
  integration_tests/tf_distribute_training_test.py
  keras/optimizers/loss_scale_optimizer.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18687 Fix tracking of special characters in the progress bar.
  keras/utils/progbar.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18692 Add support for Tensorflow SparseTensors: optimizers.
  keras/backend/tensorflow/optimizer.py
  keras/backend/tensorflow/optimizer_sparse_test.py
  keras/optimizers/adadelta.py
  keras/optimizers/adafactor.py
  keras/optimizers/adagrad.py
  keras/optimizers/adam.py
  keras/optimizers/adamax.py
  keras/optimizers/base_optimizer.py
  keras/optimizers/ftrl.py
  keras/optimizers/lion.py
  keras/optimizers/nadam.py
  keras/optimizers/rmsprop.py
  keras/optimizers/sgd.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18690 Add movielens recommendation with keras 3.0
  examples/keras_io/tensorflow/structured_data/movielens_recommendations_transformers.py
Labels: ready to pull, size:L, awaiting review

#18693 Apply `backend.result_type` to `linspace`, `logspace` and `log*`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: ready to pull, size:L, awaiting review

#18694 Add devcontainer for easier external contribution
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18705 Implement auto-assignment for newly created issues.
  .github/workflows/auto-assignment.yaml
  .github/workflows/scripts/auto-assignment.js
Labels: ready to pull, size:M, awaiting review

#18710 Apply `backend.result_type` to `all`, `amax`, `amin`, `any`, `logical*`, `maximum`, `min`, `minimum`, `mod`, `nan_to_num` and `not_equal`
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/layers/normalization/unit_normalization.py
  keras/layers/preprocessing/normalization.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18713 Avoid calling pad when possible
  keras/backend/torch/nn.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review
