Repository keras-team/keras, pull requests merged in 2023-12, with the labels that each got.

#18859 Fix LSTM performance on TF Backend
  keras/backend/tensorflow/rnn.py
Labels: ready to pull, size:S, awaiting review

#18858 Added contributing guide as `CONTRIBUTING.md`.
  CONTRIBUTING.md
  README.md
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18860 Add `hard_swish` to `ops.nn` and dtype tests for `hard_swish` and `hard_sigmoid`
  keras/activations/activations.py
  keras/backend/jax/nn.py
  keras/backend/numpy/nn.py
  keras/backend/tensorflow/nn.py
  keras/backend/torch/nn.py
  keras/ops/nn.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18867 [TODO] : Complete test for orthogonal regularizer
  keras/regularizers/regularizers_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18871 Reduce redundancy on saving model
  keras/models/model.py
  keras/saving/saving_api.py
  keras/saving/saving_api_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18897 Use floating point numbers instead of integer when expected
  keras/callbacks/reduce_lr_on_plateau.py
  keras/utils/audio_dataset_utils_test.py
  keras/utils/image_dataset_utils_test.py
  keras/utils/text_dataset_utils_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#18902 Fix `ops.tril` and `ops.triu` with tensorflow backend
  keras/backend/tensorflow/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18908 Remove versioning restrictions for export from JAX backend
  keras/export/export_lib.py
  keras/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18911 Fix the doc bug in channels_last shape in conv2d_transpose.py
  keras/layers/convolutional/conv2d_transpose.py
Labels: kokoro:force-run, ready to pull, size:XS

#18917 Rename kokoro to .kokoro
  .kokoro/README.md
  .kokoro/github/ubuntu/gpu/build.sh
  .kokoro/github/ubuntu/gpu/jax/continuous.cfg
  .kokoro/github/ubuntu/gpu/jax/presubmit.cfg
  .kokoro/github/ubuntu/gpu/tensorflow/continuous.cfg
  .kokoro/github/ubuntu/gpu/tensorflow/presubmit.cfg
  .kokoro/github/ubuntu/gpu/torch/continuous.cfg
  .kokoro/github/ubuntu/gpu/torch/presubmit.cfg
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18924 Fix jax2tf device incompatiblity for Export
  keras/export/export_lib.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18920 Implement `binomial` and `beta` distribution functions in `keras.random`
  keras/backend/jax/random.py
  keras/backend/numpy/random.py
  keras/backend/tensorflow/random.py
  keras/backend/torch/random.py
  keras/random/random.py
  keras/random/random_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18921 Add masking to BatchNormalization
  keras/layers/normalization/batch_normalization.py
  keras/layers/normalization/batch_normalization_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18926 Fixes Torch GPU Test for Binomial and Beta Distribution
  keras/backend/torch/random.py
  keras/random/random_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18928 Fix descrepancies in Conv Module docstrings regarding data_format
  keras/layers/convolutional/conv2d.py
  keras/layers/convolutional/conv3d.py
  keras/layers/convolutional/conv3d_transpose.py
  keras/layers/convolutional/depthwise_conv2d.py
  keras/layers/convolutional/separable_conv2d.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18933 add get_config() to SeedGenerator
  keras/random/seed_generator.py
  keras/random/seed_generator_test.py
Labels: ready to pull, size:XS, awaiting review

#18936 Fix Adafactor when variables have 2 dimensions or more.
  keras/optimizers/adafactor.py
  keras/optimizers/adafactor_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18937 Tweaks to TensofFlow support for SparseTensor/IndexedSlices.
  keras/backend/tensorflow/numpy.py
  keras/backend/tensorflow/sparse.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18938 Update multiprocessing import in py_dataset_adapter.py
  keras/trainers/data_adapters/py_dataset_adapter.py
Labels: ready to pull, size:XS

#18929 CTC loss for TF and torch
  keras/backend/tensorflow/nn.py
  keras/backend/torch/nn.py
  keras/ops/nn.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18940 Add `ops.random.alpha_dropout` and `layers.AlphaDropout`
  keras/layers/__init__.py
  keras/layers/regularization/alpha_dropout.py
  keras/layers/regularization/alpha_dropout_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18954 default value for input_shape when include_top is provided has False.
  keras/applications/nasnet.py
Labels: ready to pull, size:XS

#18952 CTC API for JAX
  keras/backend/jax/nn.py
  keras/backend/tensorflow/nn.py
  keras/backend/torch/nn.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18960 Return regularization losses in stateless_call.
  keras/layers/layer.py
  keras/layers/layer_test.py
Labels: size:S

#18963 Minor typo fix
  keras/losses/loss.py
Labels: kokoro:force-run, ready to pull, size:XS

#18951 Add gradient accumulation support for all backends, and enable optimizer EMA for JAX and torch
  keras/backend/jax/optimizer.py
  keras/backend/tensorflow/optimizer.py
  keras/backend/tensorflow/optimizer_distribute_test.py
  keras/backend/torch/optimizers/torch_parallel_optimizer.py
  keras/optimizers/base_optimizer.py
  keras/optimizers/nadam.py
  keras/optimizers/optimizer.py
  keras/optimizers/optimizer_test.py
Labels: size:L, awaiting review

#18965 Validate cropping arg value for -ve ints
  keras/layers/reshaping/cropping2d.py
  keras/layers/reshaping/cropping3d.py
Labels: kokoro:force-run, ready to pull, size:S

#18967 Add a CTC loss class / function
  keras/backend/jax/nn.py
  keras/backend/tensorflow/nn.py
  keras/losses/__init__.py
  keras/losses/losses.py
  keras/losses/losses_test.py
  keras/ops/nn.py
Labels: size:M

#18968 Fix for https://github.com/keras-team/keras/issues/18941
  keras/backend/tensorflow/rnn.py
Labels: kokoro:force-run, ready to pull, size:XS

#18975 Fix compiled crossentropy
  keras/trainers/compile_utils.py
  keras/trainers/compile_utils_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18972 Fix EMA when using tensorflow backend
  keras/backend/tensorflow/optimizer.py
  keras/optimizers/optimizer_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18974 Correct the Error description in cropping layer APIs
  keras/layers/reshaping/cropping1d.py
  keras/layers/reshaping/cropping1d_test.py
  keras/layers/reshaping/cropping2d.py
  keras/layers/reshaping/cropping2d_test.py
  keras/layers/reshaping/cropping3d.py
  keras/layers/reshaping/cropping3d_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18982 Save "layers" first for subclassed Functional models
  keras/saving/saving_lib.py
  keras/saving/saving_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18978 Add `SwapEMAWeights`
  keras/callbacks/__init__.py
  keras/callbacks/swap_ema_weights.py
  keras/callbacks/swap_ema_weights_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18986 Fix `clipnorm` for TF models with `Embedding` layer(s).
  keras/backend/tensorflow/optimizer.py
  keras/optimizers/adam_test.py
  keras/optimizers/base_optimizer.py
Labels: kokoro:force-run, ready to pull, size:S

#18988 Fix `ops.split` in torch and tensorflow
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18977 chore: override item removal methods in tracking
  keras/utils/tracking.py
  keras/utils/tracking_test.py
Labels: ready to pull, size:M

#18991 Add `JAXEpochIterator` and speed up `get_numpy_iterator`
  keras/backend/jax/trainer.py
  keras/backend/torch/trainer.py
  keras/trainers/data_adapters/tf_dataset_adapter.py
  keras/trainers/data_adapters/torch_data_loader_adapter.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18994 Remove reliance on Tensorflow enable_numpy_behavior for some ops.
  keras/backend/tensorflow/numpy.py
  keras/metrics/confusion_metrics_test.py
  keras/ops/nn_test.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18998 Replace `tfnp` with native tf ops wherever possible
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L
