Repository keras-team/keras, pull requests merged in 2023-02, with the labels that each got.

#17396 Fix timeseries_dataset_from_array counts when sequence_stride > 1
  keras/utils/timeseries_dataset.py
  keras/utils/timeseries_dataset_test.py
Labels: ready to pull, size:XS

#17432 Fix doc for MultiHeadAttention's output_shape arg
  keras/layers/attention/multi_head_attention.py
Labels: ready to pull, size:XS

#17540 Added a link to the TextVectorization API Reference Page.
  keras/layers/preprocessing/string_lookup.py
Labels: ready to pull, size:XS

#17544 Fix ConvNeXt classifier activation bug
  keras/applications/applications_test.py
  keras/applications/convnext.py
Labels: ready to pull, size:S

#17550 Perform all ops in apply_gradient in a given tf.name_scope.
  keras/optimizers/optimizer.py
Labels: ready to pull, keras-team-review-pending, size:S

#17501 Bugfix/normalization invert
  keras/layers/preprocessing/normalization.py
  keras/layers/preprocessing/normalization_test.py
Labels: ready to pull, size:S

#17463 OptimizerV2: Allow deepcopy
  keras/optimizers/legacy/optimizer_v2.py
  keras/optimizers/legacy/optimizer_v2_test.py
Labels: ready to pull, size:S

#17465 keras.models.clone_model creates different weight names for RNN layers
  keras/layers/rnn/base_conv_lstm.py
  keras/layers/rnn/gru.py
  keras/layers/rnn/gru_test.py
  keras/layers/rnn/gru_v1.py
  keras/layers/rnn/lstm.py
  keras/layers/rnn/lstm_test.py
  keras/layers/rnn/lstm_v1.py
  keras/layers/rnn/simple_rnn.py
  keras/layers/rnn/simple_rnn_test.py
Labels: ready to pull, keras-team-review-pending, size:S

#17568 Fix spelling error in Initializer warning
  keras/initializers/initializers.py
Labels: ready to pull, size:XS

#17547 LayerScale fix to support pretrained ConvNeXt models with mixed precision
  keras/applications/convnext.py
Labels: ready to pull, size:XS

#17571 Softmax fix in Mixed Precision
  keras/layers/activation/softmax.py
Labels: ready to pull, size:XS

#17591 Less restrictive fallback logic
  keras/layers/rnn/gru_lstm_utils.py
Labels: ready to pull, keras-team-review-pending, size:XS

#17587 Less restrictive ROCm+GRU/LSTM fallback logic
  keras/layers/rnn/gru_lstm_utils.py
Labels: ready to pull, keras-team-review-pending, size:XS

#17522 Update security section.
  CONTRIBUTING.md
Labels: ready to pull, size:XS

#17498 Fix serialization error with EfficientNet
  keras/applications/efficientnet.py
Labels: ready to pull, size:XS
