Repository keras-team/keras, pull requests merged in 2023-11, with the labels that each got.

#18715 Fix page rendering issue for Adam Optimizer docs
  keras/optimizers/base_optimizer.py
Labels: kokoro:force-run, ready to pull, size:S

#18717 Multi-worker dataset distribution for model+data parallel distribution.
  keras/distribution/distribution_lib.py
  keras/distribution/distribution_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18714 Apply `backend.result_type` to `arc*`, `cos*`, `divide`, `sin*`, `sum` and `tan*`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:L

#18719 Add support for Tensorflow SparseTensors: data adapters.
  keras/trainers/data_adapters/generator_data_adapter.py
  keras/trainers/data_adapters/generator_data_adapter_test.py
  keras/trainers/data_adapters/tf_dataset_adapter.py
  keras/trainers/data_adapters/tf_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18720 Change weight_decay arg description for AdamW
  keras/optimizers/base_optimizer.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18701 updrage to keras 3.0 for metric learning example
  examples/keras_io/tensorflow/vision/metric_learning.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18721 Add data input distribution for model+data parallel.
  keras/backend/jax/distribution_lib.py
Labels: size:M, awaiting review

#18724 fix `class_names` arg checking thinko
  keras/utils/dataset_utils.py
Labels: kokoro:force-run, ready to pull, size:XS

#18726 Bump to 2.16 nightlies for requirements
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18723 fix tests for channels_first
  keras/layers/convolutional/conv_transpose_test.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18727 Increase test coverage for `regularizers_test`
  keras/regularizers/regularizers_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18739 Use TENSORFLOW_VERSION when available during pip_build script
  pip_build.py
Labels: ready to pull, size:XS, awaiting review

#18740 Update image_classification_with_vision_transformer.py
  examples/keras_io/vision/image_classification_with_vision_transformer.py
Labels: ready to pull, size:XS, awaiting review

#18738 Update image_classification_with_vision_transformer.py
  examples/keras_io/vision/image_classification_with_vision_transformer.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18733 Add init_scope to Variable initialization in TF backend.
  keras/backend/tensorflow/core.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:S

#18737 fixes TypeError
  keras/saving/saving_api.py
  keras/utils/file_utils.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:XS

#18731 added diff op
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18732 Made clone_model return have same input/output structure
  keras/models/cloning.py
  keras/models/cloning_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:S, awaiting review

#18722 Validate decay_steps for Learning rate schedulers
  keras/optimizers/schedules/learning_rate_schedule.py
  keras/optimizers/schedules/learning_rate_schedule_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18745 Add support for Tensorflow SparseTensors: end to end flow.
  keras/backend/tensorflow/sparse.py
  keras/models/functional.py
  keras/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:M, awaiting review

#18749 Implement missing pieces from Trackable interface for TF-based variable.
  keras/backend/tensorflow/core.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:S

#18744 Added solve() function to all backends.
  keras/backend/jax/math.py
  keras/backend/numpy/math.py
  keras/backend/tensorflow/math.py
  keras/backend/torch/math.py
  keras/ops/math.py
  keras/ops/math_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:M

#18750 Remove spurious print statement.
  keras/layers/preprocessing/text_vectorization.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18751 Add support for Tensorflow SparseTensors: public API to densify.
  keras/backend/jax/core.py
  keras/backend/numpy/core.py
  keras/backend/tensorflow/core.py
  keras/backend/torch/core.py
  keras/models/functional.py
  keras/ops/core.py
  keras/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18757 Remove duplicate in nightly github action
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
Labels: kokoro:force-run, ready to pull, size:M

#18756 Add ops.is_tensor to the public API
  keras/ops/core.py
  keras/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18760 Fix metric name for metrics with custom metric function.
  keras/trainers/compile_utils.py
  keras/trainers/compile_utils_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18752 Apply `backend.result_type` to `array` and `convert_to_tensor`
  keras/backend/numpy/core.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/core.py
  keras/backend/torch/numpy.py
  keras/ops/core_test.py
  keras/ops/numpy_test.py
  keras/optimizers/schedules/learning_rate_schedule.py
Labels: size:M, awaiting review

#18765 Added missing get_config on select LossFunctionWrappers
  keras/losses/losses.py
  keras/losses/losses_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18764 Added jax support for standardize_dtype
  keras/backend/common/variables.py
  keras/backend/common/variables_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18768 Revert "Remove duplicate in nightly github action"
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
Labels: size:M, awaiting review

#18762 Add security policy
  SECURITY.md
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:XS

#18773 Fix torch breakage for convert_to_tensor([])
  keras/backend/common/dtypes.py
  keras/backend/common/dtypes_test.py
  keras/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18774 Fix tensorflow convert_to_tensor for boolean types
  keras/backend/tensorflow/core.py
  keras/ops/core_test.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18775 Bug fix for the JAX ops.arange warning
  keras/backend/jax/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#18776 Enable channels_first for image_dataset_from_directory
  keras/utils/image_dataset_utils.py
  keras/utils/image_dataset_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18780 Improve speedup test in `py_dataset_adapter`
  keras/trainers/data_adapters/py_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18777 Enable channels_first for random_crop
  keras/layers/preprocessing/random_crop.py
  keras/layers/preprocessing/random_crop_test.py
Labels: ready to pull, size:M, awaiting review

#18778 enable channels_first for center_crop
  keras/layers/preprocessing/center_crop_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:M, awaiting review

#18785 Remove unnecessary `print` statement
  keras/metrics/confusion_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#18779 Apply `backend.result_type` to `append`, `average`, `broadcast_to`, `concatenate`, `copy`, `count_nonzero`, `cross`, `diag*`, `diff` and `digitize`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/core_test.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:L, awaiting review

#18789 Fix speedup test
  keras/trainers/data_adapters/py_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18790 Minor docstring fixes
  keras/activations/activations.py
  keras/layers/attention/grouped_query_attention.py
  keras/layers/convolutional/separable_conv1d.py
  keras/metrics/confusion_metrics.py
  keras/ops/core.py
  keras/ops/nn.py
Labels: kokoro:force-run, ready to pull, size:S

#18787 Revisit tf's numpy api
  keras/backend/tensorflow/numpy.py
Labels: kokoro:force-run, ready to pull, size:M

#18782 enable channels_first for random_zoom
  keras/layers/preprocessing/random_zoom_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18792 Fix for layers.Reshape when using -1 and a dynamic batch size.
  keras/layers/reshaping/reshape.py
  keras/layers/reshaping/reshape_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18783 enable channels_first for resizing
  keras/layers/preprocessing/resizing_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18781 enable channels_first for random_roation
  keras/layers/preprocessing/random_rotation_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18791 Apply `backend.result_type` to `einsum`, `expand_dims`, `flip`, `floor`, `full_like`, `hstack`, `is*`, `meshgrid` and `moveaxis`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L

#18800 Fix the device conversion logic for keras.distribute.list_devices()
  keras/backend/jax/distribution_lib.py
  keras/backend/jax/distribution_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18803 Use set comparisons for serialization errors
  keras/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:XS

#18805 Fix regression in Reshape layer when using -1.
  keras/layers/reshaping/reshape.py
  keras/layers/reshaping/reshape_test.py
Labels: ready to pull, size:S, awaiting review

#18802 Support channels_first in SpatialDropout
  keras/layers/regularization/spatial_dropout_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18804 Support channels_first in reshaping layers
  keras/layers/reshaping/cropping2d_test.py
  keras/layers/reshaping/cropping3d_test.py
  keras/layers/reshaping/flatten_test.py
  keras/layers/reshaping/up_sampling2d_test.py
  keras/layers/reshaping/up_sampling3d_test.py
  keras/layers/reshaping/zero_padding2d_test.py
  keras/layers/reshaping/zero_padding3d_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18806 Support channels_first in rnn layers
  keras/layers/rnn/conv_lstm1d_test.py
  keras/layers/rnn/conv_lstm2d_test.py
  keras/layers/rnn/conv_lstm3d_test.py
  keras/layers/rnn/conv_lstm_test.py
  keras/layers/rnn/time_distributed_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18807 Support channels_first in normalization
  keras/layers/normalization/spectral_normalization_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18808 Support channels_first in tensorboard
  keras/callbacks/tensorboard_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18809 Enable channels_first for torch CI tests
  .github/workflows/actions.yml
  .github/workflows/config/jax/keras.json
  .github/workflows/config/numpy/keras.json
  .github/workflows/config/tensorflow/keras.json
  .github/workflows/config/torch/keras.json
Labels: kokoro:force-run, ready to pull, size:S

#18794 Add tests in `keras/ops/math.py`
  keras/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18793 Add the batch_norm op
  keras/backend/jax/nn.py
  keras/backend/numpy/nn.py
  keras/backend/tensorflow/nn.py
  keras/backend/torch/nn.py
  keras/layers/normalization/batch_normalization.py
  keras/ops/nn.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18766 Set noise_shape to None in attention.py
  keras/layers/attention/additive_attention_test.py
  keras/layers/attention/attention.py
  keras/layers/attention/attention_test.py
Labels: stat:awaiting keras-eng, size:XS

#18812 Add save and restore config tests to address TODO items.
  keras/metrics/reduction_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18814 Added config save and restore tests to Accuracy metrics and Hinge met…
  keras/metrics/accuracy_metrics_test.py
  keras/metrics/hinge_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18813 added dtype arg to cumsum/cumprod, fixes inconsistency bug
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#18795 Fix numerical issues in TF and JAX `moments` implementation.
  keras/backend/jax/nn.py
  keras/backend/tensorflow/nn.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18816 Apply `backend.result_type` to `ones_like`, `outer`, `pad`, `prod`, `ravel`, `repeat`, `reshape`, `roll`, `round`, `sign`, `sort`, `split`, `square`, `squeeze`, `stack`, `std`, `swapaxes` and `zeros_like`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L

#18820 Improve dtype inference of `add`, `divide`, `maximum`, `minimum`, `multiply` and `subtract` when using python native dtypes
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/layers/normalization/unit_normalization.py
  keras/layers/preprocessing/normalization.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L

#18824 Fix torch's `sort` with cuda
  keras/backend/torch/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#18826 Change Conv layers Doc string wrt padding.
  keras/layers/convolutional/base_conv.py
  keras/layers/convolutional/base_depthwise_conv.py
  keras/layers/convolutional/base_separable_conv.py
  keras/layers/convolutional/conv1d.py
  keras/layers/convolutional/conv2d.py
  keras/layers/convolutional/conv2d_transpose.py
  keras/layers/convolutional/conv3d.py
  keras/layers/convolutional/conv3d_transpose.py
  keras/layers/convolutional/depthwise_conv1d.py
  keras/layers/convolutional/depthwise_conv2d.py
  keras/layers/convolutional/separable_conv1d.py
  keras/layers/convolutional/separable_conv2d.py
Labels: kokoro:force-run, ready to pull, size:M

#18815 Added constant_values support to pad
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: ready to pull, size:M, awaiting review

#18828 Fixed layer.losses such that it recurses into sublayer losses
  keras/layers/layer.py
  keras/layers/layer_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#18831 Apply `backend.result_type` to `cumprod`, `cumsum`, `nonzero`, `power`, `take`, `take_along_axis`, `tensordot`, `tile`, `trace`, `transpose`, `tril`, `triu`, `vdot`, `vstack`, `where`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: ready to pull, size:L

#18835 Bug fix for TF backend using random zoom with flatten
  keras/backend/tensorflow/image.py
  keras/layers/preprocessing/random_zoom_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18848 Fix glitch in documentation for the `split` operation.
  keras/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#18847 Add support for Tensorflow SparseTensors: preserve static shapes.
  keras/backend/tensorflow/core.py
  keras/backend/tensorflow/numpy.py
  keras/backend/tensorflow/sparse.py
  keras/backend/tests/compute_output_spec_test.py
  keras/ops/numpy.py
  keras/ops/operation_utils.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:L, awaiting review

#18843 Adding stop_evaluating and stop_predicting attributes for Callbacks
  keras/backend/jax/trainer.py
  keras/backend/numpy/trainer.py
  keras/backend/tensorflow/trainer.py
  keras/backend/torch/trainer.py
  keras/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:S

#18837 Add keras.backend.device() API for device scope
  keras/backend/jax/__init__.py
  keras/backend/jax/core.py
  keras/backend/tensorflow/__init__.py
  keras/backend/tensorflow/core.py
  keras/backend/tests/device_test.py
  keras/backend/torch/__init__.py
  keras/backend/torch/core.py
  keras/layers/preprocessing/normalization_test.py
Labels: ready to pull, size:M, awaiting review

#18851 support dict items in PyDataset
  keras/trainers/data_adapters/py_dataset_adapter.py
  keras/trainers/data_adapters/py_dataset_adapter_test.py
Labels: ready to pull, size:XS

#18850 support numpy int dtypes in shapes
  keras/backend/common/variables.py
  keras/layers/core/input_layer_test.py
Labels: ready to pull, size:XS

#18852 Add hardswish
  .github/workflows/actions.yml
  keras/activations/__init__.py
  keras/activations/activations.py
  keras/activations/activations_test.py
  keras/applications/applications_test.py
  keras/applications/imagenet_utils_test.py
  keras/applications/mobilenet_v3.py
Labels: ready to pull, size:M

#18834 Add dependabot to update GHA and Python deps
  .github/dependabot.yml
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:S, awaiting review
