Repository keras-team/keras, pull requests merged in 2023-06, with the labels that each got.

#18140 Consistently use "pickleable" instead of "picklable"
  keras/engine/training.py
  keras/engine/training_generator_v1.py
  keras/engine/training_v1.py
  keras/layers/rnn/dropout_rnn_cell_mixin.py
  keras/saving/pickle_utils_test.py
Labels: ready to pull, size:S, awaiting review

#18223 Update Argument padding for zero_padding1d.py
  keras/layers/reshaping/zero_padding1d.py
Labels: ready to pull, size:XS, awaiting review

#18133 RGB image data is not grayscale image data
  keras/datasets/cifar10.py
  keras/datasets/cifar100.py
Labels: ready to pull, keras-team-review-pending, size:XS, awaiting review

#18226 updated read.me
  README.md
Labels: ready to pull, keras-team-review-pending, size:XS, awaiting review

#18233 Fixed the typo in policy.py
  keras/mixed_precision/policy.py
Labels: ready to pull, size:XS, awaiting review

#18258 Cherrypick Sequential serialization bug fix for r2.13
  keras/engine/sequential.py
  keras/saving/legacy/hdf5_format.py
  keras/saving/legacy/save_test.py
Labels: ready to pull, size:M

#18234 Update example losses @ probabilistic_metrics.py
  keras/metrics/probabilistic_metrics.py
Labels: ready to pull, size:S, awaiting review

#18251 Fixed "reset_state" of R2Score metric
  keras/metrics/regression_metrics.py
Labels: ready to pull, size:XS, awaiting review

#18177 Ignore hidden folders for image_dataset_from_directory
  keras/utils/dataset_utils.py
Labels: ready to pull, size:XS, awaiting review
