Repository keras-team/keras, pull requests merged in 2023-09, with the labels that each got.

#18382 Update requirements.txt
  requirements.txt
Labels: ready to pull, size:XS, awaiting review

#18478 Update readme with more package info
  README.md
Labels: ready to pull, size:M

#18494 Fix TF optimizer with distribution strategy.
  keras/backend/tensorflow/optimizer.py
  keras/backend/tensorflow/optimizer_distribute_test.py
Labels: ready to pull, size:S, awaiting review

#18496 Avoid importing TF in trainer with other backends
  keras/trainers/epoch_iterator.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18490 Convert to Keras 3: `convmixer` example
  examples/keras_io/vision/convmixer.py
Labels: kokoro:force-run, ready to pull, size:L

#18493 Convert to Keras 3: `Knowledge Distillation` example
  examples/keras_io/vision/knowledge_distillation.py
Labels: kokoro:force-run, ready to pull, size:L

#18499 Add "A walk through latent space with Stable Diffusion" to multi backend keras
  examples/keras_io/vision/latent_walk.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18505 Convert to Keras 3: `super_resolution_sub_pixel` example
  examples/keras_io/vision/super_resolution_sub_pixel.py
Labels: kokoro:force-run, ready to pull, size:L

#18514 Update layout map to support tuple/list as the TensorLayout value when inserting.
  keras/distribution/distribution_lib.py
  keras/distribution/distribution_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18509 torch backend use torch dataloader directly
  keras/backend/torch/trainer.py
  keras/trainers/data_adapters/__init__.py
  keras/trainers/data_adapters/torch_data_loader_adapter.py
  keras/trainers/data_adapters/torch_data_loader_adapter_test.py
  keras/trainers/epoch_iterator.py
  keras/trainers/epoch_iterator_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:L, awaiting review

#18517 A few more README fixes
  README.md
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#18518 Make Dense and EinsumDense agree more closely
  keras/layers/core/dense.py
  keras/layers/core/dense_test.py
Labels: kokoro:force-run, ready to pull, size:S

#18519 Add variable.trainable setter so torch can set requires_grad
  keras/backend/common/variables.py
  keras/backend/common/variables_test.py
  keras/backend/torch/core.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#18482 Introduce `backend.result_type`
  conftest.py
  keras/backend/__init__.py
  keras/backend/common/__init__.py
  keras/backend/common/dtypes.py
  keras/backend/common/dtypes_test.py
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/layers/rnn/dropout_rnn_cell_test.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#18484 Remove hardcoded channels_last in efficientnet_v2 and replace with ba…
  keras/applications/applications_test.py
  keras/applications/efficientnet_v2.py
  keras/applications/imagenet_utils.py
  keras/applications/mobilenet_v3.py
  keras/applications/nasnet.py
Labels: kokoro:force-run, ready to pull, size:S

#18507 Add Keras trackable logic for TF backend (fixes list and dictionary deps)
  keras/backend/tensorflow/layer.py
  keras/backend/tensorflow/saved_model_test.py
  keras/backend/tensorflow/trackable.py
  keras/ops/function.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18501 Fix `model_checkpoint_test.py` + Improve `get_test_data`
  keras/callbacks/model_checkpoint_test.py
  keras/testing/test_utils.py
  keras/testing/test_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18524 Stale and Close issues/prs with 'awaiting' labels.
  .github/workflows/stale-issue-pr.yaml
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18530 Remove redundant call in ops.numpy.matmul
  keras/backend/tensorflow/numpy.py
  keras/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review
