Repository keras-team/keras, pull requests merged in 2023-05, with the labels that each got.

#18076 Update Python ver to 3.9 in Dockerfile
  .devcontainer/Dockerfile
Labels: kokoro:force-run, ready to pull, size:XS

#18081 Increase the version number for keras 2.13
  keras/__init__.py
  keras/tools/pip_package/setup.py
Labels: kokoro:force-run, ready to pull, size:XS

#18082 Cherrypick the release script fix for RC.
  pip_build.py
Labels: ready to pull, size:S

#17978 [keras/saving/legacy/saved_model] Standardise docstring usage of "Default to"
  keras/saving/legacy/saved_model/json_utils.py
  keras/saving/legacy/saved_model/save.py
Labels: ready to pull, size:S

#18045 Update example losses to bce- metrics/confusion_metrics.py
  keras/metrics/confusion_metrics.py
Labels: ready to pull, size:S

#17968 [keras/layers/regularization] Standardise docstring usage of "Default to"
  keras/layers/regularization/spatial_dropout2d.py
  keras/layers/regularization/spatial_dropout3d.py
Labels: ready to pull, size:S

#17758 [keras/applications/efficientnet.py] Standardise docstring usage of "Default to"
  keras/applications/efficientnet.py
Labels: ready to pull, keras-team-review-pending, size:S

#17974 [keras/models] Standardise docstring usage of "Default to"
  keras/models/cloning.py
  keras/models/sharpness_aware_minimization.py
Labels: ready to pull, size:S

#17973 [keras/mixed_precision] Standardise docstring usage of "Default to"
  keras/mixed_precision/loss_scale_optimizer.py
Labels: ready to pull, size:S

#18043 Update indentation level - losses.py
  keras/losses.py
Labels: ready to pull, size:XL

#18058 Remove github user sushreebarsa from assignees.
  .github/bot_config.yml
Labels: ready to pull, size:XS

#17977 [keras/preprocessing] Standardise docstring usage of "Default to"
  keras/preprocessing/image.py
  keras/preprocessing/text.py
Labels: ready to pull, size:S

#17979 [keras/testing_infra] Standardise docstring usage of "Default to"
  keras/testing_infra/test_combinations.py
  keras/testing_infra/test_utils.py
Labels: ready to pull, size:S

#17980 [keras/benchmarks/benchmark_util.py] Use var rather than string literal for `is None` checks on `measure_performance`
  keras/benchmarks/benchmark_util.py
Labels: ready to pull, size:XS

#18124 Some cleanup // Optimizers
  keras/optimizers/adadelta.py
  keras/optimizers/adafactor.py
  keras/optimizers/adagrad.py
  keras/optimizers/adam.py
  keras/optimizers/adamax.py
  keras/optimizers/adamw.py
  keras/optimizers/ftrl.py
  keras/optimizers/lion.py
  keras/optimizers/nadam.py
  keras/optimizers/rmsprop.py
  keras/optimizers/sgd.py
Labels: ready to pull, size:L, awaiting review

#18113 [keras/layers/preprocessing] fix comments in RandomWidth, change to 'horizontally' instead of 'vertically'
  keras/layers/preprocessing/image_preprocessing.py
Labels: ready to pull, size:XS, awaiting review

#17957 [keras/estimator] Standardise docstring usage of "Default to"
  keras/estimator/__init__.py
Labels: ready to pull, size:S

#18144 Fix CategoricalFocalCE documentation
  keras/losses.py
Labels: ready to pull, size:XS, awaiting review

#17953 [keras/utils] Standardise docstring usage of "Default to"
  keras/utils/conv_utils.py
  keras/utils/data_utils.py
  keras/utils/generic_utils.py
  keras/utils/image_dataset.py
  keras/utils/image_utils.py
  keras/utils/layer_utils.py
  keras/utils/losses_utils.py
  keras/utils/metrics_utils.py
Labels: ready to pull, size:M

#17966 [keras/layers/pooling] Standardise docstring usage of "Default to"
  keras/layers/pooling/average_pooling2d.py
  keras/layers/pooling/average_pooling3d.py
  keras/layers/pooling/global_average_pooling2d.py
  keras/layers/pooling/global_average_pooling3d.py
  keras/layers/pooling/global_max_pooling2d.py
  keras/layers/pooling/global_max_pooling3d.py
  keras/layers/pooling/max_pooling2d.py
  keras/layers/pooling/max_pooling3d.py
Labels: ready to pull, size:M, awaiting review

#18054 use io_utils.print_msg in datset_utils
  keras/utils/dataset_utils.py
Labels: ready to pull, size:XS

#18036 Update indentation level - activations.py
  keras/activations.py
Labels: ready to pull, size:M

#17971 [keras/legacy_tf_layers] Standardise docstring usage of "Default to"
  keras/legacy_tf_layers/base.py
  keras/legacy_tf_layers/migration_utils.py
  keras/legacy_tf_layers/variable_scope_shim.py
Labels: ready to pull, size:S
