Repository keras-team/keras, pull requests merged in 2023-01, with the labels that each got.

#17364 Fixed EfficientNetV2's MBConvBlock output phase.
  keras/applications/efficientnet_v2.py
Labels: ready to pull, size:S

#17374 Update README.md to fix wrong links
  README.md
Labels: ready to pull, size:XS

#17330 Warning if categorical crossentropy is used for 2 labels
  keras/losses.py
  keras/losses_test.py
Labels: ready to pull, size:S

#17428 Improved the CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: ready to pull, size:S

#17441 Updated Docs string of doc_utils.py with new apis
  keras/utils/data_utils.py
Labels: ready to pull, size:XS

#17461 Update MHA docstrings
  keras/layers/attention/multi_head_attention.py
Labels: ready to pull, keras-team-review-pending, size:M

#17462 Update docstrings in text_dataset
  keras/utils/text_dataset.py
Labels: ready to pull, keras-team-review-pending, size:M

#17415 Bugfix: Pass show_layer_activations to expand_nested calls
  keras/utils/vis_utils.py
Labels: ready to pull, size:XS

#17472 Use 4 spaces indent for Dense layer docstrings
  keras/layers/core/dense.py
Labels: ready to pull, size:S

#17467 keras.layers.Bidirectional constructor ignores trainable argument, causing models with trainable=False layers to incorrectly be cloned
  keras/layers/rnn/bidirectional.py
  keras/layers/rnn/bidirectional_test.py
Labels: ready to pull, size:S

#17485 Fix api_docs for `to_ordinal`
  keras/utils/np_utils.py
Labels: ready to pull, size:S
