Repository keras-team/keras, pull requests merged in 2023-07, with the labels that each got.

#18042 Improve error message for input data to fit.
  keras/engine/data_adapter.py
  keras/engine/data_adapter_test.py
  keras/engine/training_test.py
Labels: ready to pull, size:S, awaiting review

#18274 refactor: _log_epoch_metrics()
  keras/callbacks.py
Labels: ready to pull, size:S, awaiting review, pending internal tests

#18303 Refactor test cases to improve unit test quality
  keras/benchmarks/eager_microbenchmarks_test.py
  keras/tests/add_loss_correctness_test.py
  keras/tests/model_subclassing_test.py
Labels: ready to pull, size:S
