Repository keras-team/keras, pull requests merged in 2024-12, with the labels that each got.

#20575 Random seed doc
  keras/src/random/random.py
  keras/src/random/seed_generator.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20559 Add unravel_index op
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20580 Add support for jax named scope.
  keras/src/backend/jax/__init__.py
  keras/src/backend/jax/core.py
Labels: ready to pull, size:S

#20557 Better handling of variable creation with tensor as initializer.
  keras/src/backend/common/variables.py
  keras/src/backend/common/variables_test.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/core.py
  keras/src/regularizers/regularizers_test.py
  keras/src/utils/tracking_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20570 Add Equalization Layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/equalization.py
  keras/src/layers/preprocessing/image_preprocessing/equalization_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20587 Multiple Example title has been removed in OneHotIoU
  keras/src/metrics/iou_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#20586 [TextVectorization Layer] Added tests for testing the funtionality
  keras/src/layers/preprocessing/text_vectorization_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20594 Fix masking propagation when `_keras_mask` is unset during `call`
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20602 Fix the issue when using `Model.compile` multiple times
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20609 Fix loss scaling with `tf.distribute.MirroredStrategy` and `keras.regularizers`
  keras/src/backend/tensorflow/distribute_test.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/losses/loss.py
  keras/src/trainers/trainer.py
Labels: kokoro:force-run, ready to pull, size:M

#20590 Add implementations for mix_up
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/mix_up.py
  keras/src/layers/preprocessing/image_preprocessing/mix_up_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20614 Update for numpy 2.2 bool array changes
  keras/src/constraints/constraints_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20610 Unscale loss value in metrics in tensorflow
  keras/src/backend/tensorflow/distribute_test.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/losses/loss.py
  keras/src/trainers/compile_utils.py
Labels: kokoro:force-run, ready to pull, size:M

#20613 Fix issue with unsorted dict
  keras/src/models/functional.py
  keras/src/models/functional_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20615 Allow lower precision in `einsum` in `dot_product_attention`
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
Labels: kokoro:force-run, ready to pull, size:S

#20584 Fix confusion matrix type
  keras/src/metrics/iou_metrics.py
  keras/src/metrics/iou_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20623 fixes torch GPU test on mix_up
  keras/src/layers/preprocessing/image_preprocessing/mix_up.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20625 Update `distribution_lib` files docstrings
  keras/src/backend/jax/distribution_lib.py
  keras/src/distribution/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:S

#20630 Correct bug for MixUp initialization.
  keras/src/layers/preprocessing/image_preprocessing/mix_up.py
Labels: kokoro:force-run, ready to pull, size:S

#20626 Fix Layer normalization issue with scalar mean & variance
  keras/src/layers/preprocessing/normalization.py
  keras/src/layers/preprocessing/normalization_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20635 Add `IOU`, `CIOU` and minor fixes to bounding boxes
  keras/api/_tf_keras/keras/utils/bounding_boxes/__init__.py
  keras/api/utils/bounding_boxes/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/base_image_preprocessing_layer.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/bounding_box.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/converters.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/converters_test.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/iou.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/iou_test.py
  keras/src/layers/preprocessing/image_preprocessing/center_crop.py
  keras/src/layers/preprocessing/image_preprocessing/random_flip.py
  keras/src/layers/preprocessing/image_preprocessing/random_rotation.py
  keras/src/layers/preprocessing/image_preprocessing/random_translation.py
  keras/src/layers/preprocessing/image_preprocessing/random_zoom.py
  keras/src/layers/preprocessing/image_preprocessing/resizing.py
Labels: kokoro:force-run, ready to pull, size:XL

#20637 Fix GPU CI
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/bounding_box.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/converters_test.py
  keras/src/layers/preprocessing/image_preprocessing/mix_up_test.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20636 Fix typos in simple_rnn
  keras/src/layers/rnn/simple_rnn.py
Labels: kokoro:force-run, ready to pull, size:XS

#20620 Add implementations for random_hue
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_hue.py
  keras/src/layers/preprocessing/image_preprocessing/random_hue_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20599 FEAT add scikit-learn wrappers
  keras/__init__.py
  keras/api/__init__.py
  keras/api/_tf_keras/keras/__init__.py
  keras/api/_tf_keras/keras/wrappers/__init__.py
  keras/api/wrappers/__init__.py
  keras/src/wrappers/__init__.py
  keras/src/wrappers/fixes.py
  keras/src/wrappers/sklearn_test.py
  keras/src/wrappers/sklearn_wrapper.py
  keras/src/wrappers/utils.py
  requirements-common.txt
Labels: kokoro:force-run, ready to pull, size:L

#20631 Rework `Model.export` and `keras.export.ExportArchive` to support exporting in TFLite and ONNX formats in the future
  keras/src/backend/jax/export.py
  keras/src/backend/numpy/export.py
  keras/src/backend/tensorflow/export.py
  keras/src/backend/torch/export.py
  keras/src/export/export_lib.py
  keras/src/export/export_lib_test.py
  keras/src/layers/__init__.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/core/embedding_test.py
  keras/src/models/model.py
  keras/src/models/model_test.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
  keras/src/utils/jax_layer_test.py
Labels: ready to pull, size:L, awaiting review

#20643 Update example and logic for random_hue
  keras/src/layers/preprocessing/image_preprocessing/random_hue.py
Labels: kokoro:force-run, ready to pull, size:XS

#20644 Adds scikit-learn dependency to setup
  pyproject.toml
Labels: ready to pull, size:XS, awaiting review

#20642 Update example and logic for mix_up
  keras/src/layers/preprocessing/image_preprocessing/mix_up.py
Labels: kokoro:force-run, ready to pull, size:S

#20639 Add RandomGrayscale Layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py
  keras/src/layers/preprocessing/image_preprocessing/random_grayscale_test.py
Labels: size:M, awaiting review

#20652 Fix Randomhue
  keras/src/layers/preprocessing/image_preprocessing/random_hue.py
Labels: kokoro:force-run, ready to pull, size:S

#20638 test: add test for class weights (py_dataset adapter)
  keras/src/trainers/data_adapters/data_adapter_utils.py
  keras/src/trainers/data_adapters/data_adapter_utils_test.py
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20646 Add implementations for random_saturation
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_saturation.py
  keras/src/layers/preprocessing/image_preprocessing/random_saturation_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20655 Fix paths for pytest in contribution guide
  CONTRIBUTING.md
Labels: kokoro:force-run, ready to pull, size:XS

#19727 Add preliminary support of OpenVINO as Keras 3 backend
  .github/workflows/actions.yml
  .github/workflows/config/openvino/keras.json
  .github/workflows/nightly.yml
  conftest.py
  integration_tests/basic_full_flow.py
  integration_tests/import_test.py
  integration_tests/numerical_test.py
  keras/src/backend/__init__.py
  keras/src/backend/common/dtypes_test.py
  keras/src/backend/common/variables_test.py
  keras/src/backend/openvino/__init__.py
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/excluded_tests.txt
  keras/src/backend/openvino/export.py
  keras/src/backend/openvino/image.py
  keras/src/backend/openvino/layer.py
  keras/src/backend/openvino/linalg.py
  keras/src/backend/openvino/math.py
  keras/src/backend/openvino/nn.py
  keras/src/backend/openvino/numpy.py
  keras/src/backend/openvino/random.py
  keras/src/backend/openvino/rnn.py
  keras/src/backend/openvino/trainer.py
  keras/src/callbacks/remote_monitor_test.py
  keras/src/export/export_lib.py
  keras/src/initializers/constant_initializers_test.py
  keras/src/initializers/random_initializers_test.py
  keras/src/layers/layer.py
  keras/src/models/model.py
  keras/src/ops/operation_test.py
  keras/src/trainers/trainer_test.py
  keras/src/utils/backend_utils.py
  keras/src/wrappers/sklearn_test.py
  requirements-openvino.txt
Labels: ready to pull, size:XL, awaiting review

#20657 Make sklearn dependency optional
  keras/src/wrappers/fixes.py
  keras/src/wrappers/sklearn_test.py
  keras/src/wrappers/sklearn_wrapper.py
  keras/src/wrappers/utils.py
  pyproject.toml
Labels: size:M

#20650 Add a condition to verify training status during image processing
  keras/src/layers/preprocessing/image_preprocessing/mix_up.py
  keras/src/layers/preprocessing/image_preprocessing/mix_up_test.py
  keras/src/layers/preprocessing/image_preprocessing/random_hue.py
  keras/src/layers/preprocessing/image_preprocessing/random_hue_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20656 Fix recurrent dropout for GRU.
  keras/src/layers/rnn/gru.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20663 Change recurrent dropout implementation for LSTM.
  keras/src/layers/rnn/gru.py
  keras/src/layers/rnn/gru_test.py
  keras/src/layers/rnn/lstm.py
  keras/src/layers/rnn/lstm_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20664 Never pass enable_xla=False or native_serialization=False in tests
  keras/src/export/export_lib_test.py
Labels: ready to pull, size:XS, awaiting review

#20666 Fix up torch GPU failing test for mix up
  keras/src/layers/preprocessing/image_preprocessing/mix_up.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20671 Adjust value_range for random_contrast and random_hue
  keras/src/layers/preprocessing/image_preprocessing/random_contrast.py
  keras/src/layers/preprocessing/image_preprocessing/random_contrast_test.py
  keras/src/layers/preprocessing/image_preprocessing/random_hue.py
  keras/src/layers/preprocessing/image_preprocessing/random_hue_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20669 Multiple Example Title has removed in OneHotMeanIoU funtion
  keras/src/metrics/iou_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#20673 Add random_color_jitter processing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_color_jitter.py
  keras/src/layers/preprocessing/image_preprocessing/random_color_jitter_test.py
Labels: size:M, awaiting review

#20677 Add training status condition during image processing
  keras/src/layers/preprocessing/image_preprocessing/equalization.py
  keras/src/layers/preprocessing/image_preprocessing/random_crop.py
  keras/src/layers/preprocessing/image_preprocessing/random_flip.py
  keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py
  keras/src/layers/preprocessing/image_preprocessing/random_rotation.py
  keras/src/layers/preprocessing/image_preprocessing/random_translation.py
  keras/src/layers/preprocessing/image_preprocessing/random_zoom.py
  keras/src/layers/preprocessing/image_preprocessing/solarization.py
Labels: kokoro:force-run, ready to pull, size:L

#20682 Change the import order of pydot and its older forks
  keras/src/utils/model_visualization.py
Labels: kokoro:force-run, ready to pull, size:S

#20684 Fix: Return Attention Scores when `return_attention_scores=True`
  keras/src/layers/attention/attention.py
  keras/src/layers/attention/attention_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20679 Add random_color_degeneration processing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_color_degeneration.py
  keras/src/layers/preprocessing/image_preprocessing/random_color_degeneration_test.py
Labels: ready to pull, size:M

#20689 fix attention output with symbolic tensors and attention scores
  keras/src/layers/attention/attention.py
  keras/src/layers/attention/attention_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20694 minor: Fix Functional API guide
  guides/functional_api.py
Labels: kokoro:force-run, ready to pull, size:XS

#20685 Introduces support for exporting `SavedModel` in the torch backend using `torch-xla`
  .github/workflows/actions.yml
  .kokoro/github/ubuntu/gpu/build.sh
  keras/src/backend/torch/export.py
  keras/src/export/export_lib.py
  keras/src/export/export_lib_test.py
  keras/src/models/model_test.py
  keras/src/utils/module_utils.py
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:L

#20688 Add random_posterization processing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_posterization.py
  keras/src/layers/preprocessing/image_preprocessing/random_posterization_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20696 Fix torch gpu CI
  .kokoro/github/ubuntu/gpu/build.sh
  keras/src/export/export_lib_test.py
  keras/src/models/model_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20697 Add random_sharpness processing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_sharpness.py
  keras/src/layers/preprocessing/image_preprocessing/random_sharpness_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20702 Add random_shear processing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_shear.py
  keras/src/layers/preprocessing/image_preprocessing/random_shear_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20703 Fix the aggregation in the codebase
  keras/src/backend/common/variables.py
  keras/src/backend/tensorflow/distribute_test.py
  keras/src/layers/layer.py
  keras/src/optimizers/base_optimizer.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review
