Repository keras-team/keras, pull requests merged in 2024-05, with the labels that each got.

#19655 Revert "Bump the python group with 2 updates"
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: size:S

#19656 Fix static shape for `take_along_axis` with Tensorflow.
  keras/src/backend/tensorflow/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/operation_utils.py
Labels: kokoro:force-run, ready to pull, size:M

#19659 add packaging requirement
  requirements-common.txt
  setup.py
Labels: kokoro:force-run, ready to pull, size:XS

#19663 Fix bug in `model.export()` when inputs in a structure.
  keras/src/export/export_lib.py
  keras/src/export/export_lib_test.py
  keras/src/layers/layer.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19664 switch tensorflow for macOS
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS

#19643 Fix bug in layernorm with rms_scaling=True
  keras/src/layers/normalization/layer_normalization.py
Labels: stat:awaiting response from contributor, size:XS

#19666 mlx - handle int64 and uint64 for scatter and cum*
  keras/src/backend/mlx/core.py
  keras/src/backend/mlx/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19672 Update python example dtype in string_lookup.py
  keras/src/layers/preprocessing/string_lookup.py
Labels: kokoro:force-run, ready to pull, size:XS

#19680 mlx - add argpartition to numpy
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19679 Fix for rendering issues with Keras Layers API Documentation (Convolution and Pooling layers)
  keras/src/layers/convolutional/conv1d.py
  keras/src/layers/convolutional/conv1d_transpose.py
  keras/src/layers/convolutional/conv2d.py
  keras/src/layers/convolutional/conv2d_transpose.py
  keras/src/layers/convolutional/conv3d.py
  keras/src/layers/convolutional/conv3d_transpose.py
  keras/src/layers/convolutional/depthwise_conv1d.py
  keras/src/layers/convolutional/depthwise_conv2d.py
  keras/src/layers/convolutional/separable_conv1d.py
  keras/src/layers/convolutional/separable_conv2d.py
  keras/src/layers/pooling/average_pooling1d.py
  keras/src/layers/pooling/average_pooling2d.py
  keras/src/layers/pooling/average_pooling3d.py
  keras/src/layers/pooling/max_pooling1d.py
  keras/src/layers/pooling/max_pooling2d.py
  keras/src/layers/pooling/max_pooling3d.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19685 Fix masking in merge layers.
  keras/src/layers/layer.py
  keras/src/layers/merging/base_merge.py
  keras/src/layers/merging/concatenate.py
  keras/src/layers/merging/maximum.py
  keras/src/layers/merging/merging_test.py
  keras/src/layers/merging/minimum.py
  keras/src/layers/merging/multiply.py
Labels: kokoro:force-run, ready to pull, size:M

#19686 Fix dtype test for `trace`
  keras/src/backend/jax/numpy.py
  keras/src/layers/convolutional/conv1d.py
  keras/src/layers/convolutional/conv1d_transpose.py
  keras/src/layers/convolutional/conv2d.py
  keras/src/layers/convolutional/conv2d_transpose.py
  keras/src/layers/convolutional/conv3d.py
  keras/src/layers/convolutional/conv3d_transpose.py
  keras/src/layers/convolutional/depthwise_conv1d.py
  keras/src/layers/convolutional/depthwise_conv2d.py
  keras/src/layers/convolutional/separable_conv1d.py
  keras/src/layers/convolutional/separable_conv2d.py
  keras/src/layers/pooling/average_pooling1d.py
  keras/src/layers/pooling/average_pooling2d.py
  keras/src/layers/pooling/average_pooling3d.py
  keras/src/layers/pooling/max_pooling1d.py
  keras/src/layers/pooling/max_pooling2d.py
  keras/src/layers/pooling/max_pooling3d.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19681 Add `scan` op
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/core.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/torch/core.py
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: ready to pull, size:L

#19690 Fix unexpected dtype policy changes when quantization fails
  keras/src/dtype_policies/dtype_policy.py
  keras/src/dtype_policies/dtype_policy_test.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/core/embedding.py
  keras/src/layers/core/embedding_test.py
Labels: size:M

#19698 mlx - add linalg.norm
  keras/src/backend/mlx/__init__.py
  keras/src/backend/mlx/linalg.py
  keras/src/ops/linalg_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19707 Fix `ops.shape()` for `tf.RaggedTensor`.
  keras/src/backend/tensorflow/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19710 Improved docs to bring in clarity.
  keras/src/utils/torch_utils.py
Labels: kokoro:force-run, ready to pull, size:XS

#19695 Add `name` to MobileNetV3 to allow multiple instances in one model
  keras/src/applications/mobilenet_v3.py
Labels: kokoro:force-run, ready to pull, size:S

#19699 mlx - image.resize add `crop_to_aspect_ratio` argument
  keras/src/backend/mlx/image.py
  keras/src/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19714 mlx - fix diag and diagonal in numpy
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19711 Refactor `keras.dtype_policies`
  keras/src/dtype_policies/dtype_policy.py
  keras/src/dtype_policies/dtype_policy_test.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/layer.py
  keras/src/layers/preprocessing/hashing.py
  keras/src/layers/reshaping/zero_padding1d_test.py
  keras/src/layers/reshaping/zero_padding2d_test.py
  keras/src/layers/reshaping/zero_padding3d_test.py
Labels: ready to pull, size:M, awaiting review

#19673 Add axis parameter to dice loss
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
Labels: size:S, awaiting review

#19728 Tweaks for serialization of DTypePolicy in ops/layers.
  keras/src/dtype_policies/__init__.py
  keras/src/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19720 Fix export for subclass models with multiple inputs.
  keras/src/export/export_lib.py
  keras/src/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19729 Add more tests for `DTypePolicy`
  keras/src/dtype_policies/__init__.py
  keras/src/dtype_policies/dtype_policy_test.py
  keras/src/ops/operation_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19734 mlx - fix repeat and eye in numpy
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#19739 Fix one_hot for torch backend (MPS device)
  keras/src/backend/torch/nn.py
Labels: kokoro:force-run, ready to pull, size:XS

#19741 Don't mutate passed config dict in Operation.from_config()
  keras/src/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:XS

#19742 Consolidate implementations of category encoding and remove rank limit.
  keras/src/backend/tensorflow/nn.py
  keras/src/layers/preprocessing/category_encoding.py
  keras/src/layers/preprocessing/category_encoding_test.py
  keras/src/layers/preprocessing/discretization.py
  keras/src/layers/preprocessing/discretization_test.py
  keras/src/layers/preprocessing/hashed_crossing.py
  keras/src/layers/preprocessing/hashed_crossing_test.py
  keras/src/layers/preprocessing/hashing.py
  keras/src/layers/preprocessing/hashing_test.py
  keras/src/layers/preprocessing/index_lookup.py
  keras/src/layers/preprocessing/text_vectorization.py
  keras/src/utils/numerical_utils.py
  keras/src/utils/tf_utils.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19746 Fixing typos in doc
  keras/src/models/model.py
Labels: kokoro:force-run, ready to pull, size:S

#19750 Remove `convert_to_numpy` in confusion metrics and fix `ops.nonzero` …
  keras/src/backend/torch/numpy.py
  keras/src/metrics/confusion_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19751 Re-introduce `tf_utils.ensure_tensor` in preprocessing layers.
  keras/src/layers/preprocessing/hashed_crossing.py
  keras/src/layers/preprocessing/hashing.py
  keras/src/layers/preprocessing/index_lookup.py
  keras/src/layers/preprocessing/text_vectorization.py
  keras/src/utils/tf_utils.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19758 Give an error message with a description of the fix if a generator yi…
  keras/src/trainers/data_adapters/generator_data_adapter.py
  keras/src/trainers/data_adapters/generator_data_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19759 Added arctan2 operation
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#19752 Fix `dtype` serialization
  keras/src/dtype_policies/__init__.py
  keras/src/ops/operation.py
  keras/src/ops/operation_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19763 mlx - linalg ops
  keras/src/backend/mlx/linalg.py
Labels: kokoro:force-run, ready to pull, size:S

#19764 StringLookup layer can now take tf.SparseTensors as input.
  keras/src/layers/preprocessing/string_lookup.py
  keras/src/layers/preprocessing/string_lookup_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19775 Fix the `linspace` bug when `num` is a tensor in the tensorflow backend
  keras/src/backend/tensorflow/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19774 Leave `data_format` as `None` in `keras.ops.images` and add `data_format` support to `pad_images` and `crop_images`
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/tensorflow/image.py
  keras/src/backend/torch/image.py
  keras/src/ops/image.py
  keras/src/ops/image_test.py
Labels: size:L

#19777 Refactor `ops.image.*` and the tests
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/tensorflow/image.py
  keras/src/backend/torch/image.py
  keras/src/layers/preprocessing/feature_space_test.py
  keras/src/layers/preprocessing/random_rotation.py
  keras/src/ops/image.py
  keras/src/ops/image_test.py
  keras/src/utils/module_utils.py
Labels: kokoro:force-run, ready to pull, size:XL

#19773 Fix bug in StringLokkup when vocab is a tensor
  keras/src/layers/preprocessing/string_lookup.py
  keras/src/layers/preprocessing/string_lookup_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review
