Repository keras-team/keras, pull requests merged in 2024-09, with the labels that each got.

#20197 Fix the metrics issue in a nested trainer
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20195 Added parameter 'verbose' when exporting TF SavedModel
  keras/src/export/export_lib.py
  keras/src/models/model.py
Labels: kokoro:force-run, ready to pull, size:S

#20190 Add the logic to assert and remove files after running test
  integration_tests/model_visualization_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20205 Fix and improve the mechansim for removing metrics in `Trainer`
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20206 Replace `ValueError` with `AttributeError` in `Sequential`'s property
  keras/src/models/sequential.py
  keras/src/models/sequential_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20207 Fixing example code for binarycrossentropy in losses.py file
  keras/src/losses/losses.py
Labels: kokoro:force-run, ready to pull, size:XS

#20200 Logdet op, fix for Slogdet shape estimation
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/backend/jax/math.py
  keras/src/backend/numpy/math.py
  keras/src/backend/tensorflow/math.py
  keras/src/backend/torch/math.py
  keras/src/ops/math.py
  keras/src/ops/math_test.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20202 SaturateCast op
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20215 Fix load_model from hf:// preset
  keras/src/saving/saving_api.py
Labels: kokoro:force-run, ready to pull, size:XS

#20208 Add assert statement to check model structure on model_visualization_test
  integration_tests/model_visualization_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20223 [#20144] updated documentation for DenseNet, Xception, and ResNet
  keras/src/applications/densenet.py
  keras/src/applications/resnet.py
  keras/src/applications/xception.py
Labels: kokoro:force-run, ready to pull, size:XS

#20196 L2 normalize op
  keras/src/layers/normalization/unit_normalization.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20228 Fix test `test_output_mode_dict`
  keras/src/layers/preprocessing/feature_space_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20229 Improve performance of load and save
  keras/src/saving/saving_lib.py
Labels: kokoro:force-run, ready to pull, size:S

#20232 Add `ops.trunc`
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20231 Canonical type comparison
  keras/src/metrics/accuracy_metrics.py
  keras/src/utils/dataset_utils.py
Labels: kokoro:force-run, ready to pull, size:XS

#20213 Fix image resize conversion to original dtype
  keras/src/backend/tensorflow/image.py
  keras/src/layers/preprocessing/resizing.py
  keras/src/ops/core.py
  keras/src/ops/image.py
  keras/src/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20240 [#20238] updated devcontainer to include pip install
  .devcontainer/devcontainer.json
Labels: kokoro:force-run, ready to pull, size:XS

#20237 Solving issue #20221
  keras/src/layers/normalization/unit_normalization.py
Labels: ready to pull, size:S, awaiting review

#20248 `TestCase`'s `assertAllClose` and `assertAlmostEqual` now report the …
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20246 added validation checks in Group, Layer, Batch Normalization layers
  FE
  keras/src/layers/normalization/batch_normalization.py
  keras/src/layers/normalization/group_normalization.py
  keras/src/layers/normalization/layer_normalization.py
Labels: kokoro:force-run, ready to pull, size:M

#20247 Add public APIs for model variables
  keras/src/models/model.py
  keras/src/models/model_test.py
Labels: ready to pull, size:M, awaiting review

#20257 Fix numeric instability in `LayerNormalization`
  keras/src/layers/normalization/batch_normalization.py
  keras/src/layers/normalization/layer_normalization.py
Labels: kokoro:force-run, ready to pull, size:S

#20262 Fix typo in documentation for the extract_patches function.
  keras/src/ops/image.py
Labels: kokoro:force-run, ready to pull, size:XS

#20264 Allow AREA resize interpolation for TF backend
  keras/src/backend/tensorflow/image.py
Labels: kokoro:force-run, ready to pull, size:XS

#19872 Updated Complex dtype input support for layers
  keras/src/backend/common/custom_layer_test.py
  keras/src/backend/common/dtypes.py
  keras/src/backend/common/dtypes_test.py
  keras/src/backend/common/variables_test.py
  keras/src/ops/core_test.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20275 Provide a setter for `layers` in `Sequential` and `Functional`.
  keras/src/models/functional.py
  keras/src/models/functional_test.py
  keras/src/models/model_test.py
  keras/src/models/sequential.py
  keras/src/models/sequential_test.py
Labels: size:S

#20239 add list_layer_paths method for KerasFileEditor
  keras/src/saving/file_editor.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20280 Reimplement `eye` op on TF to support tensors as inputs.
  keras/src/backend/tensorflow/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20284 Add support for async callbacks
  keras/src/backend/jax/trainer.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/backend/torch/trainer.py
  keras/src/callbacks/callback.py
  keras/src/callbacks/callback_list.py
  keras/src/trainers/trainer.py
Labels: size:M

#20286 Add `ops.nn.dot_product_attention`
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20296 Fix `CompileLoss` with undefined `loss` argument
  keras/src/models/model_test.py
  keras/src/trainers/compile_utils.py
Labels: kokoro:force-run, ready to pull, size:M

#20295 Fix jax cuda requirements
  keras/src/backend/tests/device_scope_test.py
  requirements-jax-cuda.txt
Labels: kokoro:force-run, ready to pull, size:XS

#20300 fix device get for Jax CI
  keras/src/backend/tests/device_scope_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20298 Update "Transfer learning & fine-tuning(BM layer)" guide
  guides/transfer_learning.py
Labels: kokoro:force-run, ready to pull, size:S

#20301 Fix rendering issue
  keras/src/layers/attention/additive_attention.py
  keras/src/layers/attention/attention.py
Labels: kokoro:force-run, ready to pull, size:XS

#20302 Allow `ops.stop_gradient()` to take a variable.
  keras/src/backend/jax/core.py
  keras/src/backend/torch/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20305 Fix a typo in a docstring in activations.py:
  keras/src/activations/activations.py
Labels: kokoro:force-run, ready to pull, size:XS
