Repository keras-team/keras, pull requests merged in 2024-03, with the labels that each got.

#19236 Enable int8xint8->int32 `einsum`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: ready to pull, size:L, awaiting review

#19252 Refactor `axis` logic across all backends and add support for multiple axes in `expand_dims` and `squeeze`
  keras/backend/common/backend_utils.py
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
  keras/ops/operation_utils.py
  keras/ops/operation_utils_test.py
Labels: ready to pull, size:L, awaiting review

#19256 Auto-label 'gemma' Issues/PRs.
  .github/workflows/labeler.yaml
  .github/workflows/scripts/labeler.js
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19258 Add pad_to_aspect_ratio arg to image_dataset_from_directory
  keras/utils/image_dataset_utils.py
  keras/utils/image_dataset_utils_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19260 add numerical test to CI
  .github/workflows/actions.yml
  integration_tests/numerical_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19269 Fix `isinstance` check for tuple input in `pack_x_y_sample_weight`
  keras/trainers/data_adapters/data_adapter_utils.py
Labels: ready to pull, size:XS

#19273 Pin to TF 2.16
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19272 Update jax random shuffle API
  keras/backend/jax/random.py
Labels: kokoro:force-run, ready to pull, size:XS

#19275 fix typo in `keras.distribution.initialize` (`proceed_id` -> `process_id`)
  keras/distribution/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:XS

#19287 Unwrap variable values in all stateless calls.
  keras/backend/common/stateless_scope.py
  keras/backend/tensorflow/core.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19289 Fix `draw_seed` causing device discrepancy issue during `torch`'s symbolic execution
  keras/backend/torch/random.py
Labels: ready to pull, size:S

#19293 Fix TestCase.run_layer_test for multi-output layers
  keras/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:M

#19295 Sine docstring
  keras/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#19300 Fix `keras.ops.softmax` for the tensorflow backend
  keras/ops/nn.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19297 Fix mixed precision check in TestCase.run_layer_test: compare with output_spec dtype instead of hardcoded float16
  keras/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19298 ArrayDataAdapter no longer converts to NumPy and supports sparse tens…
  keras/backend/jax/core.py
  keras/backend/jax/trainer.py
  keras/backend/tensorflow/core.py
  keras/backend/tensorflow/trainer.py
  keras/backend/torch/trainer.py
  keras/trainers/data_adapters/array_data_adapter.py
  keras/trainers/data_adapters/array_data_adapter_test.py
  keras/trainers/data_adapters/array_slicing.py
  keras/trainers/data_adapters/data_adapter_utils.py
  keras/trainers/data_adapters/generator_data_adapter.py
  keras/utils/dataset_utils.py
  keras/utils/tree.py
Labels: kokoro:force-run, ready to pull, size:XL, awaiting review

#19312 add token to codecov
  .github/workflows/actions.yml
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19313 Add Tensorflow support for variable `scatter_update` in optimizers.
  keras/backend/tensorflow/optimizer.py
  keras/optimizers/optimizer_sparse_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19306 Replace `dm-tree` with `optree`
  keras/backend/tensorflow/core.py
  keras/backend/tensorflow/layer.py
  keras/backend/tensorflow/numpy.py
  keras/backend/tensorflow/trainer.py
  keras/export/export_lib.py
  keras/models/cloning.py
  keras/ops/core_test.py
  keras/utils/tracking.py
  keras/utils/tree.py
  keras/utils/tree_test.py
  requirements-common.txt
  setup.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19319 downgrade codecov to v3
  .github/workflows/actions.yml
Labels: kokoro:force-run, ready to pull, size:XS

#19318 Allow tensors in `tf.Dataset`s to have different dimensions.
  keras/trainers/data_adapters/data_adapter_utils.py
  keras/trainers/data_adapters/generator_data_adapter.py
  keras/trainers/data_adapters/generator_data_adapter_test.py
  keras/trainers/data_adapters/py_dataset_adapter.py
  keras/trainers/data_adapters/py_dataset_adapter_test.py
  keras/trainers/data_adapters/torch_data_loader_adapter.py
  keras/trainers/data_adapters/torch_data_loader_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19320 update codecov setting
  .github/workflows/actions.yml
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19327 Set dtype policy for uint8
  keras/dtype_policies/__init__.py
  keras/dtype_policies/dtype_policy.py
  keras/dtype_policies/dtype_policy_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19284 Use Value dim shape for Attention compute_output_shape
  keras/dtype_policies/dtype_policy.py
  keras/layers/attention/attention.py
  keras/layers/attention/attention_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19336 Fix output shape for channels_first
  keras/layers/reshaping/up_sampling2d.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19344 Standardize docstring
  keras/callbacks/tensorboard.py
  keras/layers/convolutional/conv1d.py
  keras/layers/convolutional/conv1d_transpose.py
  keras/layers/convolutional/conv2d.py
  keras/layers/convolutional/conv2d_transpose.py
  keras/layers/convolutional/conv3d.py
  keras/layers/convolutional/conv3d_transpose.py
  keras/layers/convolutional/depthwise_conv1d.py
  keras/layers/convolutional/depthwise_conv2d.py
  keras/layers/convolutional/separable_conv1d.py
  keras/layers/convolutional/separable_conv2d.py
  keras/layers/merging/dot.py
  keras/layers/preprocessing/random_brightness.py
  keras/layers/reshaping/cropping1d.py
  keras/layers/reshaping/cropping2d.py
  keras/layers/reshaping/cropping3d.py
  keras/layers/reshaping/up_sampling1d.py
  keras/layers/reshaping/up_sampling2d.py
  keras/layers/reshaping/zero_padding1d.py
  keras/layers/reshaping/zero_padding2d.py
  keras/layers/reshaping/zero_padding3d.py
  keras/layers/rnn/stacked_rnn_cells.py
  keras/metrics/accuracy_metrics.py
  keras/metrics/confusion_metrics.py
  keras/metrics/hinge_metrics.py
  keras/metrics/iou_metrics.py
  keras/metrics/metric.py
  keras/metrics/probabilistic_metrics.py
  keras/metrics/regression_metrics.py
  keras/models/cloning.py
  keras/models/model.py
  keras/optimizers/rmsprop.py
  keras/optimizers/schedules/learning_rate_schedule.py
  keras/trainers/data_adapters/data_adapter_utils.py
  keras/utils/backend_utils.py
  keras/utils/image_utils.py
  keras/utils/torch_utils.py
  keras/utils/tracking.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19342 Add `JaxLayer` and `FlaxLayer` to wrap JAX/Flax modules as layers.
  keras/utils/jax_layer.py
  keras/utils/jax_layer_test.py
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XL

#19353 Move Jax import to conditional
  keras/utils/jax_layer.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19349 Fix gpu CI by adding `flax` in the requirements
  keras/utils/jax_layer_test.py
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
Labels: size:XS

#19352 Allow save_model/load_model to accept a file-like object
  keras/saving/saving_lib.py
  keras/saving/saving_lib_test.py
Labels: ready to pull, size:M

#19347 Update `build` in `Dense` and `EinsumDense` for `QuantizedDTypePolicy`
  keras/layers/core/dense.py
  keras/layers/core/dense_test.py
  keras/layers/core/einsum_dense.py
  keras/layers/core/einsum_dense_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19302 Custom Gradients
  keras/backend/torch/core.py
  keras/ops/core.py
  keras/ops/core_test.py
Labels: keras-team-review-pending, size:M

#19359 Move `shape_utils.map_shape_structure` to `keras.utils.tree`.
  keras/layers/core/lambda_layer.py
  keras/layers/layer.py
  keras/testing/test_case.py
  keras/utils/jax_layer.py
  keras/utils/shape_utils.py
  keras/utils/tree.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19364 fix seed value when seed=0
  keras/initializers/random_initializers.py
  keras/layers/preprocessing/random_crop.py
Labels: kokoro:force-run, ready to pull, size:S

#19362 Fix type check for input
  keras/layers/merging/dot.py
Labels: kokoro:force-run, ready to pull, size:XS

#19368 Add more manual implementations for TF's `einsum`
  keras/backend/tensorflow/numpy.py
  keras/layers/core/dense_test.py
  keras/layers/core/einsum_dense_test.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19369 only save to temp directories in tests
  keras/saving/saving_lib_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19356 Introduce QLoRA-like technique
  keras/layers/core/dense.py
  keras/layers/core/dense_test.py
  keras/layers/core/einsum_dense.py
  keras/layers/core/einsum_dense_test.py
Labels: kokoro:force-run, ready to pull, size:L, Gemma

#19370 Bug fix, model.evaluate return metrics in order.
  keras/trainers/trainer.py
  keras/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19363 fix bug for numerical difference in losses
  keras/backend/jax/trainer.py
  keras/backend/numpy/trainer.py
  keras/backend/tensorflow/trainer.py
  keras/backend/torch/trainer.py
  keras/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19380 Change the numerical test to be more comprehensive.
  integration_tests/numerical_test.py
Labels: size:M

#19378 Add `dtype=float32` to PadSequencesTest
  keras/utils/sequence_utils_test.py
Labels: ready to pull, size:S

#19377 Add `quantize` to Embedding
  keras/layers/core/dense.py
  keras/layers/core/dense_test.py
  keras/layers/core/einsum_dense.py
  keras/layers/core/einsum_dense_test.py
  keras/layers/core/embedding.py
  keras/layers/core/embedding_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19382 Fix CentreCrop compute_output_shape
  keras/layers/preprocessing/center_crop.py
Labels: kokoro:force-run, ready to pull, size:XS

#19387 Fix `DTypePolicy` serialization
  keras/dtype_policies/dtype_policy.py
  keras/dtype_policies/dtype_policy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19385 Add sparse support to `ops.sum` and "sparse" option to `one_hot`, `mu…
  keras/backend/common/variables_test.py
  keras/backend/jax/nn.py
  keras/backend/jax/numpy.py
  keras/backend/numpy/nn.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/nn.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/nn.py
  keras/backend/torch/numpy.py
  keras/layers/merging/merging_test.py
  keras/layers/preprocessing/category_encoding.py
  keras/layers/preprocessing/category_encoding_test.py
  keras/ops/core_test.py
  keras/ops/nn.py
  keras/ops/nn_test.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
  keras/testing/test_case.py
Labels: size:L, awaiting review

#19384 Remove duplicate variable wrapping for JAX export
  keras/export/export_lib.py
Labels: size:XS

#19391 Reintroduce the option for autocasting to individual weights
  keras/backend/common/variables.py
  keras/backend/common/variables_test.py
  keras/layers/layer.py
  keras/layers/layer_test.py
  keras/layers/normalization/batch_normalization.py
  keras/layers/normalization/batch_normalization_test.py
  keras/layers/normalization/layer_normalization.py
  keras/layers/normalization/layer_normalization_test.py
Labels: size:M

#19388 fix compute_output_shape in CategoryEncoding layer
  keras/layers/preprocessing/category_encoding.py
  keras/layers/preprocessing/category_encoding_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19397 Fix dropout for recurrent dropout
  keras/layers/rnn/dropout_rnn_cell.py
Labels: kokoro:force-run, ready to pull, size:XS

#19399 Fix variables binding in JAX export.
  keras/export/export_lib.py
  keras/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19400 Fix `FlaxLayer` docstring.
  keras/utils/jax_layer.py
  keras/utils/jax_layer_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19401 Refactor dtypes and add float8_* dtypes
  keras/backend/common/dtypes.py
  keras/backend/common/dtypes_test.py
  keras/backend/common/variables.py
  keras/backend/common/variables_test.py
  keras/backend/torch/core.py
  keras/ops/core_test.py
  keras/ops/math_test.py
  keras/ops/nn_test.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19404 Fix for JAX export on GPU.
  keras/export/export_lib.py
Labels: kokoro:force-run, ready to pull, size:XS

#19405 Fix formatting in export_lib.
  keras/export/export_lib.py
Labels: kokoro:force-run, ready to pull, size:XS

#19310 ops/numpy.py: support key as list in GetItem
  keras/ops/numpy.py
  keras/saving/serialization_lib_test.py
Labels: size:XS
