Repository keras-team/keras, pull requests merged in 2024-11, with the labels that each got.

#20427 Move project metadata from setup.py to pyproject.toml
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  pip_build.py
  pyproject.toml
  setup.py
Labels: kokoro:force-run, ready to pull, size:M

#20434 Fix typos
  guides/transfer_learning.py
  keras/src/applications/convnext.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/math.py
  keras/src/backend/torch/math.py
  keras/src/backend/torch/nn.py
  keras/src/callbacks/model_checkpoint_test.py
  keras/src/initializers/constant_initializers.py
  keras/src/layers/attention/attention.py
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/preprocessing/stft_spectrogram.py
  keras/src/legacy/saving/legacy_h5_format_test.py
  keras/src/ops/linalg.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
  keras/src/optimizers/adamw.py
  keras/src/optimizers/base_optimizer.py
  keras/src/random/random.py
  keras/src/saving/file_editor.py
  keras/src/trainers/compile_utils.py
  keras/src/utils/jax_layer.py
Labels: kokoro:force-run, ready to pull, size:M

#20438 Fix keras.ops.quantile implementation for floating point inputs that are not tf.float32
  keras/src/backend/tensorflow/numpy.py
Labels: ready to pull, size:XS, awaiting review

#20439 Use temporary folder for testing model saving in file editor
  keras/src/saving/file_editor_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20443 Fix encoding issue
  keras/src/utils/io_utils.py
  keras/src/utils/io_utils_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20442 Replace isort and flake8 with Ruff checker
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
  keras/__init__.py
  keras/src/callbacks/tensorboard.py
  keras/src/models/functional_test.py
  keras/src/models/model.py
  keras/src/trainers/data_adapters/array_slicing.py
  keras/src/utils/sequence_utils.py
  pyproject.toml
  requirements-common.txt
  setup.cfg
  shell/format.sh
  shell/lint.sh
Labels: kokoro:force-run, ready to pull, size:M

#20447 adding `ifft2` method to ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/backend/jax/math.py
  keras/src/backend/numpy/math.py
  keras/src/backend/tensorflow/math.py
  keras/src/backend/torch/math.py
  keras/src/ops/math.py
  keras/src/ops/math_test.py
Labels: ready to pull, size:M, awaiting review

#20453 Fix for https://github.com/keras-team/keras/issues/20425
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
  keras/src/trainers/epoch_iterator.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20454 Tweaked documentation of `Model`'s `fit`, `evaluate` and `predict`.
  keras/src/trainers/trainer.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20456 Suppress warnings for mismatched tuples and lists in functional models
  keras/src/models/functional.py
  keras/src/models/functional_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20452 Add Circle Loss Function for Similarity/Metric Learning Tasks.
  keras/api/_tf_keras/keras/losses/__init__.py
  keras/api/losses/__init__.py
  keras/src/backend/jax/math.py
  keras/src/backend/numpy/math.py
  keras/src/backend/torch/math.py
  keras/src/losses/__init__.py
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
  keras/src/utils/numerical_utils.py
  keras/src/utils/numerical_utils_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20451 `TensorFlowTrainer`: Add low-level API `unrolled_steps_per_execution` parameter
  keras/src/backend/tensorflow/trainer.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20461 Fix steps for `TensorBoard` callback for evaluation and batch metrics.
  keras/src/callbacks/tensorboard.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20457 Add support for direct tensor as initializer
  keras/src/initializers/__init__.py
  keras/src/initializers/random_initializers_test.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/embedding.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20448 Enable flash attention
  keras/api/_tf_keras/keras/config/__init__.py
  keras/api/config/__init__.py
  keras/src/backend/jax/nn.py
  keras/src/backend/torch/nn.py
  keras/src/layers/attention/attention.py
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20468 Implement transform_bounding_boxes for random_flip
  keras/src/layers/preprocessing/image_preprocessing/random_flip.py
  keras/src/layers/preprocessing/image_preprocessing/random_flip_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20477 `CompileLoss`: fix for partially defined loss with different `y_pred` and `y_true` structures
  keras/src/trainers/compile_utils.py
  keras/src/trainers/compile_utils_test.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20476 Update CompileLoss to report unweighted metric values (breaking change)
  keras/src/trainers/compile_utils.py
  keras/src/trainers/compile_utils_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20470 Add hard_shrink activation function
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20465 Double backup
  keras/src/callbacks/backup_and_restore.py
  keras/src/callbacks/backup_and_restore_test.py
  keras/src/utils/file_utils.py
Labels: kokoro:force-run, ready to pull, size:M

#20480 Add tanh_shrink activation
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20482 remove arg `return_attention_scores` from `_compute_attention`
  keras/src/layers/attention/multi_head_attention.py
Labels: ready to pull, size:XS, awaiting review

#20484 Improve the consistency of the names of initializers
  keras/api/_tf_keras/keras/initializers/__init__.py
  keras/api/initializers/__init__.py
  keras/src/initializers/__init__.py
  keras/src/initializers/constant_initializers.py
  keras/src/initializers/constant_initializers_test.py
  keras/src/initializers/random_initializers.py
  keras/src/initializers/random_initializers_test.py
  keras/src/layers/preprocessing/stft_spectrogram.py
Labels: kokoro:force-run, ready to pull, size:M

#20488 Fix `attention_mask` computation in `MultiHeadAttention`
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
Labels: ready to pull, size:M

#20489 Refactor `dot_product_attention` to use flash attention when available
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20492 Fixing example code for BinaryFocalCrossentropy in losses.py file
  keras/src/losses/losses.py
Labels: kokoro:force-run, ready to pull, size:XS

#20494 Add soft_shrink activation
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20495 Enhance the robustness of the flash attention check
  keras/src/backend/jax/nn.py
  keras/src/backend/torch/nn.py
  keras/src/layers/attention/multi_head_attention_test.py
  requirements-common.txt
Labels: kokoro:force-run, ready to pull, size:M

#20499 Unpin coverage
  requirements-common.txt
Labels: kokoro:force-run, ready to pull, size:XS

#20491 implement transform_bounding_boxes for center_crop
  keras/src/layers/preprocessing/image_preprocessing/center_crop.py
  keras/src/layers/preprocessing/image_preprocessing/center_crop_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20501 Fix rendering issue
  keras/src/metrics/reduction_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#20506 Add exp2 op
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20503 More flexible output_shape computation in keras.layers.MultiHeadAttention
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
Labels: ready to pull, size:XS

#20510 Fix tensorflow `_dot_product_attention_xla` and update `enable_flash_attention`
  keras/src/backend/jax/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/layers/attention/attention.py
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/ops/nn.py
Labels: kokoro:force-run, ready to pull, size:M

#20508 Add squareplus activation
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20511 `MultiHeadAttention._compute_attention_mask()` always returns a bool …
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
Labels: ready to pull, size:S, awaiting review

#20513 Allow `convert_to_tensor` to take a value with the wrong `dtype` on T…
  keras/src/backend/tensorflow/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20512 Avoid call to deprecated xla_bridge.get_backend()
  keras/src/backend/tests/device_scope_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20514 Introduce flash attention to GQA and move the flash attention configs to `backend.config`
  keras/api/_tf_keras/keras/config/__init__.py
  keras/api/config/__init__.py
  keras/src/backend/config.py
  keras/src/layers/attention/attention.py
  keras/src/layers/attention/grouped_query_attention.py
  keras/src/layers/attention/grouped_query_attention_test.py
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20516 Make test resilient to spurious warnings.
  keras/src/models/functional_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20523 Fixing example code for CategoricalCrossentropy in losses.py file
  keras/src/losses/losses.py
Labels: kokoro:force-run, ready to pull, size:XS

#20522 Fix and update GQA tests
  keras/src/layers/attention/grouped_query_attention_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20525 Fix incorrect argument name and update description in RNN documentation
  keras/src/layers/rnn/rnn.py
Labels: kokoro:force-run, ready to pull, size:XS

#20528 Replace `np.iinfo` and `np.finfo` with `ml_dtypes`
  keras/src/backend/numpy/image.py
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20530 Raise an error when `save_weights` or `load_weights` is called on an unbuilt model
  keras/src/saving/saving_lib.py
  keras/src/saving/saving_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20533 Allow EarlyStopping to be reused between multiple `fit`s.
  keras/src/callbacks/early_stopping.py
  keras/src/callbacks/early_stopping_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20526 implement transform_bounding_boxes for random_zoom
  keras/src/layers/preprocessing/image_preprocessing/random_zoom.py
  keras/src/layers/preprocessing/image_preprocessing/random_zoom_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20534 Fix `BaseOptimizer` to handle a mix of `tf.Variable` and `KerasVariable`
  keras/src/optimizers/base_optimizer.py
  keras/src/optimizers/optimizer_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20539 Add support for symbolic tensors to `convert_to_tensor`.
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20540 implement transform_bounding_boxes for random_translation
  keras/src/layers/preprocessing/image_preprocessing/random_translation.py
  keras/src/layers/preprocessing/image_preprocessing/random_translation_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20541 Propagate the `aggregation` property when creating a `tf.Variable`
  keras/src/backend/common/variables.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/tensorflow/distribute_test.py
  keras/src/optimizers/loss_scale_optimizer.py
Labels: kokoro:force-run, ready to pull, size:S

#20532 Add inner op
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20543 Remove `output_shape` property in MHA
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/utils/summary_utils.py
  keras/src/utils/summary_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20550 Fix cloning of Sequential models w. input_tensors argument
  keras/src/models/cloning.py
  keras/src/models/cloning_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20553 Multiple Example Title has been removed
  keras/src/metrics/regression_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#20547 Add diagflat op
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: ready to pull, size:M, awaiting review

#20561 Update ModelCheckpoint support ".h5" support
  keras/src/callbacks/model_checkpoint.py
Labels: kokoro:force-run, ready to pull, size:S

#20558 Addition of Sparsemax activation
  .gitignore
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20563 Add parameter axis to tversky loss
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
Labels: size:S

#20537 FIX BUG in load_weights_from_hdf5_group_by_name" legacy_h5_format.py
  keras/src/legacy/saving/legacy_h5_format.py
  keras/src/legacy/saving/legacy_h5_format_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20481 Major rework of `optree_impl` and `dmtree_impl` for consistency.
  keras/api/_tf_keras/keras/tree/__init__.py
  keras/api/tree/__init__.py
  keras/src/models/cloning.py
  keras/src/models/functional.py
  keras/src/models/model_test.py
  keras/src/ops/function.py
  keras/src/trainers/compile_utils.py
  keras/src/trainers/compile_utils_test.py
  keras/src/tree/dmtree_impl.py
  keras/src/tree/optree_impl.py
  keras/src/tree/tree_api.py
  keras/src/tree/tree_test.py
  keras/src/utils/dataset_utils_test.py
  keras/src/utils/tracking.py
Labels: kokoro:force-run, ready to pull, size:M

#20555 Add threshold activation
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review
