Repository keras-team/keras, pull requests merged in 2024-06, with the labels that each got.

#19781 Add a conversion mechanism in `TFDataLayer` to better support different backends in `tf.data`
  keras/src/layers/preprocessing/feature_space_test.py
  keras/src/layers/preprocessing/normalization.py
  keras/src/layers/preprocessing/tf_data_layer.py
  keras/src/ops/linalg_test.py
  keras/src/utils/backend_utils.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19785 Fix `output_shape` deserialization in Lambda Layer (#19776)
  keras/src/layers/core/lambda_layer.py
Labels: ready to pull, size:XS

#19790 Fix `CategoryEncoding` generates output with 1 additional dimension in all backends except NumPy (#19724)
  keras/src/backend/numpy/nn.py
  keras/src/layers/preprocessing/category_encoding_test.py
  keras/src/ops/nn_test.py
  keras/src/utils/numerical_utils.py
Labels: ready to pull, size:S, awaiting review

#19801 Update auto-assignment.js
  .github/workflows/scripts/auto-assignment.js
Labels: kokoro:force-run, ready to pull, size:XS

#19802 Make example in documentation more obvious
  keras/src/layers/reshaping/permute.py
Labels: kokoro:force-run, ready to pull, size:XS

#19800 Fix `DynamicBackend`
  keras/src/utils/backend_utils.py
  keras/src/utils/backend_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19799 Enable `Sequential` and `Functional` model to be used as a submodel
  keras/src/models/functional.py
  keras/src/models/functional_test.py
  keras/src/models/sequential.py
  keras/src/models/sequential_test.py
  keras/src/ops/function.py
  keras/src/ops/function_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19805 perf: remove a redundant call to `Functional.__init__`
  keras/src/models/model.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19807 Fix `LayerNormalization.get_config`
  keras/src/layers/normalization/layer_normalization.py
Labels: kokoro:force-run, ready to pull, size:XS

#19782 Propagate kwargs through `keras.ops.isclose`
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19814 Faster in_top_k implementation for Jax backend
  keras/src/backend/jax/math.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19827 Fix TypeError in `Lambda.from_config`
  keras/src/layers/core/lambda_layer.py
Labels: kokoro:force-run, ready to pull, size:XS

#19822 fixing dmtree.is_nested() and parameterized tree test
  keras/src/tree/dmtree_impl.py
  keras/src/tree/tree_test.py
  keras/src/utils/module_utils.py
  requirements-common.txt
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19826 Fix `keras.ops.repeat` cannot return an expected shape when `x` is a …
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19830 `Metric.variables` is now recursive.
  keras/src/metrics/metric.py
  keras/src/metrics/metric_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19833 Fix `get_file` when the HTTP response has no `Content-Length` header
  keras/src/utils/file_utils.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19834 Add `ops.switch`
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/core.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/torch/core.py
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19842 Use `absl.testing.parameterized` for `tree_test.py`.
  keras/src/tree/tree_test.py
  requirements-common.txt
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19829 Make batch norm mask shape error more descriptive
  keras/src/layers/normalization/batch_normalization.py
Labels: ready to pull, size:XS

#19843 doc: `ops.slice`
  keras/src/ops/core.py
Labels: kokoro:force-run, ready to pull, size:XS

#19845 corrected the example code in unit_normalization.py
  keras/src/layers/normalization/unit_normalization.py
Labels: kokoro:force-run, ready to pull, size:XS

#19840 Add `training` argument to `Model.compute_loss()`.
  keras/src/backend/jax/trainer.py
  keras/src/backend/numpy/trainer.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/backend/torch/trainer.py
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19844 Fix the compatibility issues of `Orthogonal` and `GRU`
  keras/src/initializers/__init__.py
  keras/src/initializers/random_initializers_test.py
  keras/src/layers/rnn/gru.py
  keras/src/layers/rnn/gru_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19838 Fix inconsistent behavior of `losses.sparse_categorical_crossentropy`…
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19847 Fix bugs with `Mean`, `Accuracy` and `BinaryAccuracy` metrics.
  keras/src/metrics/accuracy_metrics.py
  keras/src/metrics/accuracy_metrics_test.py
  keras/src/metrics/reduction_metrics.py
  keras/src/metrics/reduction_metrics_test.py
Labels: ready to pull, size:M, awaiting review

#19849 Add `custom_gradient` (a pass-through) for the numpy backend
  keras/src/backend/numpy/core.py
  keras/src/backend/numpy/numpy.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19853 fix variable name when add in init function
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19850 Add `rgb_to_hsv` and `hsv_to_rgb`
  keras/api/_tf_keras/keras/ops/image/__init__.py
  keras/api/ops/image/__init__.py
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/tensorflow/image.py
  keras/src/backend/torch/image.py
  keras/src/ops/image.py
  keras/src/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19852 Improve `save_model` and `load_model`
  keras/src/saving/saving_lib.py
  keras/src/saving/saving_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19862 Fix code formatting error in docstring
  keras/src/layers/preprocessing/hashed_crossing.py
Labels: kokoro:force-run, ready to pull, size:XS

#19861 Exclude benchmarks directory from distribution
  setup.py
Labels: size:XS

#19863 Improve `Model.summary`
  keras/src/utils/summary_utils.py
  keras/src/utils/summary_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19864 Stop using import * from toplevel init
  api_gen.py
  keras/__init__.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19873 Fix typo in documentation
  keras/src/layers/reshaping/up_sampling1d.py
Labels: kokoro:force-run, ready to pull, size:XS

#19883 Fix torch.tile for int
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19885 Fix torch distributed training
  keras/src/backend/torch/layer.py
  keras/src/layers/layer_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19890 Fix issue with the explicit import in __init__
  api_gen.py
  keras/__init__.py
Labels: size:XS, awaiting review

#19892 Fix for broadcast in metrics reduction.
  keras/src/metrics/reduction_metrics.py
  keras/src/metrics/reduction_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19893 Add `dtype` argument to all losses and export `CTC`
  keras/src/losses/__init__.py
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
Labels: kokoro:force-run, ready to pull, size:L

#19858 Introduce `DTypePolicyMap`
  keras/api/_tf_keras/keras/dtype_policies/__init__.py
  keras/api/dtype_policies/__init__.py
  keras/src/dtype_policies/__init__.py
  keras/src/dtype_policies/dtype_policy.py
  keras/src/dtype_policies/dtype_policy_map.py
  keras/src/dtype_policies/dtype_policy_map_test.py
  keras/src/dtype_policies/dtype_policy_test.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/embedding.py
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
  keras/src/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19896 Fix `dtype` argument passed to `Layer` when it is a `FloatDTypePolicy` in config
  keras/src/dtype_policies/dtype_policy.py
  keras/src/dtype_policies/dtype_policy_map.py
  keras/src/dtype_policies/dtype_policy_test.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/core/embedding.py
  keras/src/layers/core/embedding_test.py
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
  keras/src/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:S

#19897 Add `keras.ops.dtype`
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/ops/core.py
Labels: kokoro:force-run, ready to pull, size:S

#19901 Fix for JAX exported model not updating non-trainable variables.
  keras/src/export/export_lib.py
  keras/src/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19902 Fix JAX export support of `TFDataLayer`.
  keras/src/export/export_lib_test.py
  keras/src/layers/preprocessing/tf_data_layer.py
  keras/src/utils/jax_utils.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19903 Add `ops.map`
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/core.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/torch/core.py
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19910 Fix `ops.Nonzero.compute_output_spec()`.
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19911 `keras.utils.split_dataset` now supports nested structures in dataset.
  keras/src/utils/dataset_utils.py
  keras/src/utils/dataset_utils_test.py
Labels: kokoro:force-run, ready to pull, size:L

#19915 Fix `export_lib.make_tensor_spec`
  keras/src/export/export_lib.py
  keras/src/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19918 Internally, replace `FloatDTypePolicy` with `DTypePolicy`
  keras/src/dtype_policies/__init__.py
  keras/src/dtype_policies/dtype_policy.py
  keras/src/dtype_policies/dtype_policy_map.py
  keras/src/dtype_policies/dtype_policy_map_test.py
  keras/src/dtype_policies/dtype_policy_test.py
  keras/src/layers/layer_test.py
  keras/src/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19923 Fix compatibility of `random.beta` in `tf.data`
  keras/src/backend/tensorflow/random.py
  keras/src/random/random_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19924 Fix `save_model` and `load_model`
  keras/src/saving/saving_lib.py
  keras/src/saving/saving_lib_test.py
Labels: ready to pull, size:S

#18945 Improve "Defaults to" by putting to end of arg in docstring and ensuring backticks have proper spacing
  keras/src/callbacks/backup_and_restore.py
  keras/src/ops/math.py
  keras/src/ops/nn.py
  keras/src/ops/numpy.py
  keras/src/utils/audio_dataset_utils.py
  keras/src/utils/image_dataset_utils.py
  keras/src/utils/image_utils.py
  keras/src/utils/sequence_utils.py
  keras/src/utils/text_dataset_utils.py
Labels: stat:awaiting keras-eng, kokoro:force-run, ready to pull, size:M

#19854 Add integration with the Hugging Face Hub
  keras/src/models/model.py
  keras/src/saving/saving_api.py
  keras/src/saving/saving_lib.py
Labels: ready to pull, size:M, awaiting review

#19927 Fix GPU CI and improve `save_model` and `load_model`
  keras/src/random/random_test.py
  keras/src/saving/saving_lib.py
  keras/src/saving/saving_lib_test.py
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:M

#19920 Prevent setting attributes on `KerasTensor`
  keras/src/backend/common/keras_tensor.py
  keras/src/backend/common/keras_tensor_test.py
  keras/src/dtype_policies/dtype_policy.py
  keras/src/ops/core.py
  keras/src/ops/function.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19931 Fix `ops.tril` and `ops.triu` for tensorflow backend
  keras/src/backend/tensorflow/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19928 configure random seed dtype based on backend
  keras/src/backend/jax/__init__.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/__init__.py
  keras/src/backend/numpy/core.py
  keras/src/backend/tensorflow/__init__.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/tensorflow/random.py
  keras/src/backend/torch/__init__.py
  keras/src/backend/torch/core.py
  keras/src/random/seed_generator.py
  keras/src/random/seed_generator_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19937 Improve consistency of the `dtype` argument across `Layer`, `Loss`, and `Metric`.
  keras/src/losses/loss.py
  keras/src/losses/loss_test.py
  keras/src/losses/losses.py
  keras/src/metrics/metric.py
  keras/src/metrics/metric_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19938 add associative_scan
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/backend/common/backend_utils.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/core.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/torch/core.py
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:L
