Repository keras-team/keras, pull requests merged in 2024-01, with the labels that each got.

#19010 Fix `inplace operation` in LSTM when using torch backend
  keras/layers/rnn/lstm.py
Labels: kokoro:force-run, ready to pull, size:XS

#19024 Use `convert_to_tensor` when moving to device for numpy
  keras/backend/torch/trainer.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19012 Update Cuda Reqs to align Cuda versions
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
Labels: kokoro:force-run, ready to pull, size:XS

#19020 Allow rank > 2 for input shapes in numerical_utils
  keras/layers/preprocessing/discretization_test.py
  keras/utils/numerical_utils.py
Labels: kokoro:force-run, ready to pull, size:S

#19028 Text Vectorization Preprocessing Layer - Fixes
  keras/layers/preprocessing/category_encoding.py
  keras/layers/preprocessing/hashed_crossing.py
  keras/layers/preprocessing/hashing.py
  keras/layers/preprocessing/integer_lookup.py
  keras/layers/preprocessing/string_lookup.py
  keras/layers/preprocessing/text_vectorization.py
  keras/layers/preprocessing/text_vectorization_test.py
  keras/utils/backend_utils.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#18942 Add initial LoRA implementation
  keras/layers/attention/multi_head_attention.py
  keras/layers/attention/multi_head_attention_test.py
  keras/layers/core/dense.py
  keras/layers/core/dense_test.py
  keras/layers/core/einsum_dense.py
  keras/layers/core/einsum_dense_test.py
  keras/layers/core/embedding.py
  keras/layers/core/embedding_test.py
Labels: size:M, awaiting review

#18997 Fix TensorShape bug in tensorflow backend
  keras/backend/common/variables.py
Labels: ready to pull, size:XS

#19030 Redirect deprecated function call
  keras/utils/numerical_utils.py
Labels: kokoro:force-run, ready to pull, size:XS

#19029 Implement a new unit test and correct some typos.
  keras/backend/common/variables_test.py
  keras/layers/preprocessing/discretization.py
  keras/layers/preprocessing/discretization_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19046 Rewrite triu and tril in tensorflow backend
  keras/backend/tensorflow/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:M

#19056 Update docstrings of confusion_metrics.py
  keras/metrics/confusion_metrics.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19057 raise exception on unknown padding for conv
  keras/ops/operation_utils.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19041 All DataAdapters can now create a native iterator for each backend.
  keras/backend/jax/core.py
  keras/backend/jax/trainer.py
  keras/backend/numpy/trainer.py
  keras/backend/tensorflow/core.py
  keras/backend/tensorflow/trainer.py
  keras/backend/torch/trainer.py
  keras/layers/normalization/batch_normalization_test.py
  keras/trainers/data_adapters/array_data_adapter.py
  keras/trainers/data_adapters/array_data_adapter_test.py
  keras/trainers/data_adapters/data_adapter.py
  keras/trainers/data_adapters/data_adapter_utils.py
  keras/trainers/data_adapters/generator_data_adapter.py
  keras/trainers/data_adapters/generator_data_adapter_test.py
  keras/trainers/data_adapters/py_dataset_adapter.py
  keras/trainers/data_adapters/py_dataset_adapter_test.py
  keras/trainers/data_adapters/tf_dataset_adapter.py
  keras/trainers/data_adapters/tf_dataset_adapter_test.py
  keras/trainers/data_adapters/torch_data_loader_adapter.py
  keras/trainers/data_adapters/torch_data_loader_adapter_test.py
  keras/trainers/epoch_iterator.py
  keras/trainers/epoch_iterator_test.py
Labels: stat:awaiting keras-eng, kokoro:force-run, ready to pull, size:L

#19074 Allow bfloat16 as default dtype
  keras/backend/config.py
Labels: ready to pull, size:XS

#19076 Fix repeat pytest in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kokoro:force-run, ready to pull, size:XS

#19066 Change implementation of numpy.min() of torch backend
  keras/backend/torch/numpy.py
  keras/ops/numpy_test.py
Labels: size:XS

#19079 Add tests for enabling LORA on a Dense and Embedding layer
  keras/layers/core/dense_test.py
  keras/layers/core/embedding_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19080 fix and add tests for /ops/math.py
  keras/ops/math.py
  keras/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19086 Let backend determine the data format by setting `data_format=None`
  keras/layers/pooling/average_pooling2d.py
  keras/layers/pooling/average_pooling3d.py
  keras/layers/pooling/base_global_pooling.py
  keras/layers/reshaping/up_sampling2d.py
  keras/layers/reshaping/up_sampling3d.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19088 Correct keras.ops.take behaviour with axis=None
  keras/backend/torch/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19096 Fix the numerical_test by using `tf_keras` instead of `tensorflow.keras`
  integration_tests/numerical_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19095 Fix for `py_dataset_adapter_test` on GPU.
  keras/trainers/data_adapters/py_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19098 Fix formatting.
  keras/backend/jax/trainer.py
  keras/random/__init__.py
  keras/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19097 Rename `ops.reshape` argument from `new_shape` to `newshape`.
  keras/backend/common/keras_tensor.py
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/metrics/accuracy_metrics.py
  keras/ops/numpy.py
  keras/ops/operation_utils.py
  keras/ops/operation_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19091 Attempt to add support for saving/loading bfloat16
  keras/backend/jax/core.py
  keras/backend/numpy/core.py
  keras/backend/tensorflow/core.py
  keras/backend/torch/core.py
  keras/layers/core/dense.py
  keras/layers/core/einsum_dense.py
  keras/layers/layer.py
  keras/saving/saving_api_test.py
  requirements-common.txt
  setup.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19093 Fix for `_calculate_score_mask` in Attention Layer
  keras/layers/attention/attention.py
  keras/layers/attention/attention_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19102 Fix wrong gradients for torch batch_norm and moments
  integration_tests/numerical_test.py
  keras/backend/torch/nn.py
Labels: size:S, awaiting review

#19099 Add `ops.math.norm`
  keras/backend/jax/math.py
  keras/backend/numpy/math.py
  keras/backend/tensorflow/math.py
  keras/backend/torch/math.py
  keras/ops/math.py
  keras/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19075 [keras/applications/mobilenet.py] `_conv_block` & `_depthwise_conv_block` now conformed to 'Google style docstrings' format
  keras/applications/mobilenet.py
Labels: kokoro:force-run, ready to pull, size:XS

#19101 bug fix in scatter update for jax backend
  keras/backend/jax/core.py
  keras/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19107 Add `erfinv` op
  keras/backend/jax/math.py
  keras/backend/numpy/math.py
  keras/backend/tensorflow/math.py
  keras/backend/torch/math.py
  keras/ops/math.py
  keras/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19111 Cast avg to float in progbar
  keras/utils/progbar.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19113 Refactor tf's `norm` and apply `result_type` to `norm`
  keras/backend/jax/math.py
  keras/backend/numpy/math.py
  keras/backend/tensorflow/math.py
  keras/backend/torch/math.py
  keras/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19115 Improve contributing.md
  CONTRIBUTING.md
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19109 Add support for sparse tensors with the JAX backend.
  keras/backend/jax/core.py
  keras/backend/jax/numpy.py
  keras/backend/jax/sparse.py
  keras/backend/tensorflow/numpy.py
  keras/backend/tests/compute_output_spec_test.py
  keras/layers/core/dense_test.py
  keras/layers/core/embedding_test.py
  keras/layers/core/identity.py
  keras/layers/merging/merging_test.py
  keras/layers/reshaping/flatten_test.py
  keras/layers/reshaping/permute_test.py
  keras/ops/core_test.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
  keras/optimizers/optimizer_sparse_test.py
  keras/testing/test_case.py
  keras/trainers/trainer_test.py
  keras/utils/jax_utils.py
Labels: kokoro:force-run, ready to pull, size:XL

#19117 When monitor metric size >1 fallback to save_best_only=False in ModelCheckpoint
  keras/callbacks/model_checkpoint.py
Labels: kokoro:force-run, ready to pull, size:XS

#19119 Fix AttributeError in `_check_output_spec` Method of `keras.ops.core.Cond` Class" + Add tests
  keras/ops/core.py
  keras/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:L

#19122 Fix TensorFlow sparse tests on GPU.
  keras/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19118 Fix bug in broadcast_to Op with Jax backend when keras variable as input
  keras/backend/jax/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#19125 Add TFDatasetAdapter and GeneratorDataAdapter sparse support for JAX.
  keras/trainers/data_adapters/generator_data_adapter.py
  keras/trainers/data_adapters/generator_data_adapter_test.py
  keras/trainers/data_adapters/tf_dataset_adapter.py
  keras/trainers/data_adapters/tf_dataset_adapter_test.py
  keras/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review
