Repository keras-team/keras, pull requests merged in 2024-04, with the labels that each got.

#19409 feat(losses): add Dice loss implementation
  keras/losses/__init__.py
  keras/losses/losses.py
  keras/losses/losses_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19415 Remove dead code in saving lib
  keras/saving/saving_lib.py
Labels: size:XS

#19417 Silu simpler
  keras/backend/tensorflow/nn.py
  keras/backend/torch/nn.py
Labels: kokoro:force-run, ready to pull, size:XS

#19419 Fix print_fn for custom function
  keras/utils/summary_utils.py
Labels: ready to pull, size:XS

#19331 Fix compute_output_shape in bidirectional.py
  keras/layers/rnn/bidirectional.py
  keras/layers/rnn/bidirectional_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19421 feat(ops): support `np.correlate`
  keras/backend/jax/numpy.py
  keras/backend/numpy/numpy.py
  keras/backend/tensorflow/numpy.py
  keras/backend/torch/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L

#19424 Add tests for model serialization and empty inputs/outputs in function
  keras/ops/function_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19429 Enhance Testing Coverage for `keras/metrics/accuracy_metrics.py`
  keras/metrics/accuracy_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19435 Enhance Testing Coverage for `keras/metrics/f_score_metrics.py`
  keras/metrics/f_score_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19434 Add support for aliases and finer control over `jax2tf` in export.
  keras/export/export_lib.py
  keras/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19443 Fix `quantile` and `median` for JAX backend with jax 0.4.26.
  keras/backend/jax/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19444 Update keras/losses/__init__.py to include Binary and Categorical Focal Crossentropy
  keras/losses/__init__.py
Labels: ready to pull, size:XS

#19446 test(layers): increase test coverage for zero padding
  keras/layers/reshaping/zero_padding1d_test.py
  keras/layers/reshaping/zero_padding2d_test.py
  keras/layers/reshaping/zero_padding3d_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19450 Fix a crash with PyTorch backend when using `weighted_metrics` with a GPU.
  keras/metrics/reduction_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#19449 Fix example code in embedding.py
  keras/layers/core/embedding.py
Labels: kokoro:force-run, ready to pull, size:XS

#19452 Remove print from saving lib
  keras/saving/saving_lib.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19447 Add test files for `keras/datasets`
  integration_tests/dataset_tests/boston_housing_test.py
  integration_tests/dataset_tests/california_housing_test.py
  integration_tests/dataset_tests/cifar100_test.py
  integration_tests/dataset_tests/cifar10_test.py
  integration_tests/dataset_tests/fashion_mnist_test.py
  integration_tests/dataset_tests/imdb_test.py
  integration_tests/dataset_tests/mnist_test.py
  integration_tests/dataset_tests/reuters_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19459 Fix dtype inconsistency in `keras.random`
  keras/backend/numpy/random.py
  keras/backend/tensorflow/random.py
  keras/backend/torch/random.py
  keras/layers/regularization/alpha_dropout_test.py
  keras/layers/regularization/dropout_test.py
  keras/layers/regularization/gaussian_dropout.py
  keras/layers/regularization/gaussian_dropout_test.py
  keras/layers/regularization/gaussian_noise.py
  keras/layers/regularization/gaussian_noise_test.py
  keras/random/random_test.py
Labels: size:M

#19462 Add support for dynamic dimensions with model export.
  keras/export/export_lib.py
  keras/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#19463 Update links to Flax documentation in `FlaxLayer`.
  keras/utils/jax_layer.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19464 Fix type annotation for `Model`, `Sequential` and `Functional`
  keras/models/functional.py
  keras/models/model.py
  keras/models/sequential.py
Labels: kokoro:force-run, ready to pull, size:S

#19465 Add docstrings for `KerasVariable` #19266
  keras/backend/common/variables.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19466 Add symbolic shape to nonzero
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19467 Add sum gradient reduction to optimizer in tf.distribute case
  keras/backend/tensorflow/optimizer.py
Labels: ready to pull, size:M

#19468 add the Identity initializer to be get by its name
  keras/initializers/__init__.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19477 Doc bug fix for hard_sigmoid op
  keras/activations/activations.py
Labels: kokoro:force-run, ready to pull, size:XS

#19481 Add full `bincount` and `digitize` sparse support.
  keras/backend/jax/numpy.py
  keras/ops/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19485 Fix for `distribution_lib.list_device()` for TensorFlow backend.
  keras/backend/tensorflow/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19484 Fix issue with using a callable as a learning rate
  keras/optimizers/base_optimizer.py
  keras/optimizers/optimizer_test.py
Labels: ready to pull, size:S

#19470 Add missing tests `ops/nn.py`
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19393 Added `rgb_to_grayscale`
  keras/backend/jax/image.py
  keras/backend/numpy/image.py
  keras/backend/tensorflow/image.py
  keras/backend/torch/image.py
  keras/ops/image.py
  keras/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19493 Add missing tests for `ops/math.py`
  keras/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19497 Workaround for Tensorflow unit test crash on GPU.
  keras/backend/tensorflow/core.py
  keras/backend/tensorflow/sparse.py
  keras/ops/numpy_test.py
  keras/trainers/data_adapters/array_slicing.py
Labels: kokoro:force-run, ready to pull, size:S

#19438 fix loading layers with lambda in from .h5 files #19151
  keras/saving/saving_api.py
Labels: ready to pull, size:XS

#19495 Fix path of the states in `SeedGenerator` and tracking of `torch_params`
  keras/backend/torch/layer.py
  keras/layers/attention/grouped_query_attention_test.py
  keras/layers/attention/multi_head_attention_test.py
  keras/layers/core/dense_test.py
  keras/layers/core/einsum_dense_test.py
  keras/layers/core/embedding_test.py
  keras/layers/layer.py
  keras/layers/preprocessing/discretization.py
  keras/layers/regularization/alpha_dropout.py
  keras/layers/regularization/dropout.py
  keras/layers/regularization/gaussian_dropout.py
  keras/layers/regularization/gaussian_noise.py
  keras/layers/rnn/stacked_rnn_cells_test.py
  keras/ops/operation.py
  keras/random/seed_generator.py
  keras/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19507 Fix `MapCoordinates` class and Add Tests for Uncovered Areas in `keras/ops/image.py`
  keras/ops/image.py
  keras/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19323 Update nn.py to use jnp.add rather than + operand.
  keras/backend/jax/nn.py
Labels: kokoro:force-run, ready to pull, size:XS

#19488 Introduce float8 training
  keras/backend/common/variables.py
  keras/backend/common/variables_test.py
  keras/dtype_policies/__init__.py
  keras/dtype_policies/dtype_policy.py
  keras/dtype_policies/dtype_policy_test.py
  keras/layers/core/dense.py
  keras/layers/core/dense_test.py
  keras/layers/core/einsum_dense.py
  keras/layers/core/einsum_dense_test.py
  keras/layers/core/embedding.py
  keras/layers/core/embedding_test.py
  keras/layers/layer.py
  keras/layers/layer_test.py
  keras/models/model.py
  keras/models/model_test.py
  keras/ops/operation.py
  keras/optimizers/base_optimizer.py
  keras/optimizers/optimizer_test.py
  keras/quantizers/__init__.py
  keras/quantizers/quantizers.py
  keras/quantizers/quantizers_test.py
Labels: ready to pull, size:XL, awaiting review, Gemma

#19516 Add LoRA to ConvND layers
  keras/layers/convolutional/base_conv.py
  keras/layers/convolutional/conv_test.py
Labels: kokoro:force-run, ready to pull, size:L

#19511 feat(losses): add Tversky loss implementation
  keras/losses/__init__.py
  keras/losses/losses.py
  keras/losses/losses_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19522 Models and layers now return owned metrics recursively.
  keras/layers/layer.py
  keras/layers/layer_test.py
  keras/trainers/trainer.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19513 Fix `RandomBrightness`, Enhance `IndexLookup` Initialization and Expand Test Coverage for `Preprocessing Layers`
  keras/layers/preprocessing/category_encoding_test.py
  keras/layers/preprocessing/hashing_test.py
  keras/layers/preprocessing/index_lookup_test.py
  keras/layers/preprocessing/normalization_test.py
  keras/layers/preprocessing/random_brightness.py
  keras/layers/preprocessing/random_brightness_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19529 Added metrics from custom `train_step`/`test_step` are now returned.
  keras/src/backend/jax/trainer.py
  keras/src/backend/numpy/trainer.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/backend/torch/trainer.py
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
Labels: size:M, awaiting review

#19533 Use temp dir and abs path in `api_gen.py`
  README.md
  api_gen.py
Labels: ready to pull, size:M, awaiting review

#19531 Update APIs
  keras/src/dtype_policies/dtype_policy.py
  keras/src/quantizers/quantizers.py
  keras/src/version.py
Labels: size:S

#19534 Fix gradient accumulation when using `overwrite_with_gradient` during float8 training
  keras/src/backend/jax/optimizer.py
  keras/src/backend/tensorflow/optimizer.py
  keras/src/backend/torch/optimizers/torch_parallel_optimizer.py
  keras/src/optimizers/adadelta.py
  keras/src/optimizers/adafactor.py
  keras/src/optimizers/adagrad.py
  keras/src/optimizers/adam.py
  keras/src/optimizers/adamax.py
  keras/src/optimizers/adamw.py
  keras/src/optimizers/base_optimizer.py
  keras/src/optimizers/ftrl.py
  keras/src/optimizers/lion.py
  keras/src/optimizers/nadam.py
  keras/src/optimizers/optimizer_test.py
  keras/src/optimizers/rmsprop.py
  keras/src/optimizers/sgd.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19537 Fix CI: Update code path in ignore path
  .kokoro/github/ubuntu/gpu/build.sh
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19538 Add operations per run
  .github/workflows/stale-issue-pr.yaml
Labels: kokoro:force-run, ready to pull, size:XS

#19541 Fix incorrect usage of `quantize`
  keras/src/layers/core/dense.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/core/embedding.py
  keras/src/layers/core/embedding_test.py
  keras/src/layers/layer.py
Labels: kokoro:force-run, ready to pull, size:M

#19543 implement batch_normalization
  keras/backend/exports.py
  keras/backend/mlx/core.py
  keras/backend/mlx/nn.py
  keras/backend/mlx/numpy.py
  keras/backend/mlx/trainer.py
Labels: kokoro:force-run, ready to pull, size:S

#19545 Fix small bug in model.save_weights
  keras/src/models/model.py
Labels: kokoro:force-run, ready to pull, size:XS

#19551 API Gen - copy keras/api/__init__.py to keras/__init__.py
  api_gen.py
  keras/__init__.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19552 Revert "API Gen - copy keras/api/__init__.py to keras/__init__.py"
  api_gen.py
  keras/__init__.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19556 Remove the dependency on `tensorflow.experimental.numpy` and support negative indices for `take` and `take_along_axis`
  keras/src/backend/jax/numpy.py
  keras/src/backend/tensorflow/linalg.py
  keras/src/backend/tensorflow/math.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/tensorflow/random.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: ready to pull, size:L

#19563 Make `ops.abs` and `ops.absolute` consistent between backends.
  keras/src/backend/jax/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#19555 Add pickle support for Keras model
  keras/src/models/model.py
  keras/src/models/model_test.py
Labels: ready to pull, size:S, awaiting review

#19564 Ellipsis Serialization and tests
  keras/src/saving/serialization_lib.py
  keras/src/saving/serialization_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19566 Added tensordot
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#19570 Fix the bug in `_int8_call` of `EinsumDense`
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
Labels: kokoro:force-run, ready to pull, size:S, Gemma

#19568 Implemented `median(...)` function.
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#19569 mlx - add mx.round and fix numpy args
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#19572 mlx - minor fixes in nn.py
  keras/src/backend/mlx/nn.py
Labels: kokoro:force-run, ready to pull, size:XS

#19366 CTC Decoding for JAX and Tensorflow
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19575 list insert requires index
  keras/src/utils/tracking.py
Labels: kokoro:force-run, ready to pull, size:XS

#19578 mlx - add missing convert_to_tensor
  keras/src/backend/mlx/math.py
  keras/src/backend/mlx/nn.py
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:XL

#19576 mlx - skip float64 tests in nn_test.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:XL

#19580 Fix the apis of `dtype_polices`
  keras/api/_tf_keras/keras/dtype_policies/__init__.py
  keras/api/dtype_policies/__init__.py
  keras/src/dtype_policies/__init__.py
  keras/src/dtype_policies/dtype_policy.py
  keras/src/dtype_policies/dtype_policy_test.py
  keras/src/losses/__init__.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19598 Convert return type imdb.load_data to np array
  keras/src/datasets/imdb.py
Labels: kokoro:force-run, ready to pull, size:XS

#19590 fix api_gen.py for legacy
  api_gen.py
  keras/api/__init__.py
  keras/api/_tf_keras/keras/__init__.py
  keras/api/_tf_keras/keras/backend/__init__.py
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/_tf_keras/keras/losses/__init__.py
  keras/api/_tf_keras/keras/metrics/__init__.py
  keras/api/_tf_keras/keras/preprocessing/__init__.py
  keras/api/_tf_keras/keras/preprocessing/image/__init__.py
  keras/api/_tf_keras/keras/preprocessing/sequence/__init__.py
  pip_build.py
Labels: ready to pull, size:L

#19595 Reduce int8 quantization error for `Embedding` layer
  keras/src/layers/core/embedding.py
Labels: kokoro:force-run, ready to pull, size:S

#19603 pin torch < 2.3.0 (pre-release ver) to resolve 'Parameter' object has no attribute 'fget'
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements.txt
Labels: size:XS, awaiting review

#19599 mlx - fix for ops/core_test.py
  keras/src/backend/mlx/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19604 Clean up duplicated `inputs_quantizer`
  keras/src/layers/core/dense.py
  keras/src/layers/core/einsum_dense.py
Labels: kokoro:force-run, ready to pull, size:XS

#19608 output format changes and errors in github
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  shell/api_gen.sh
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19606 Provide write permission to action for cache management.
  .github/workflows/stale-issue-pr.yaml
Labels: kokoro:force-run, ready to pull, size:XS

#19609 mlx - add rgb_to_grayscale
  keras/src/backend/mlx/image.py
Labels: kokoro:force-run, ready to pull, size:S

#19592 Pickle support for all saveables
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
  keras/src/losses/loss.py
  keras/src/losses/loss_test.py
  keras/src/metrics/metric.py
  keras/src/metrics/metric_test.py
  keras/src/models/functional.py
  keras/src/models/model.py
  keras/src/models/sequential.py
  keras/src/models/sequential_test.py
  keras/src/optimizers/base_optimizer.py
  keras/src/optimizers/optimizer_test.py
  keras/src/saving/keras_saveable.py
  keras/src/saving/saving_lib.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19574 Implement missing functions in mlx backend
  keras/src/backend/mlx/math.py
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19611 Refactor CTC APIs
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/losses/losses.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:L

#19613 mlx - numpy fix scalar handling and skip float 64 tests
  keras/src/backend/mlx/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:XL

#19617 update the namex version requirements
  requirements-common.txt
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19616 Add `PSNR` API
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19618 Remove `PYTORCH_ENABLE_MPS_FALLBACK` flag requirement for mps
  keras/src/backend/torch/core.py
Labels: size:XS, awaiting review

#19610 Implement custom layer insertion in clone_model.
  keras/src/models/cloning.py
  keras/src/models/cloning_test.py
  keras/src/ops/function.py
Labels: size:M

#19621 Making extract_patches compatible with images of dtype float16 along with float32
  keras/src/ops/image.py
Labels: ready to pull, size:XS

#19624 Add support for infinite `PyDataset`s.
  keras/src/trainers/data_adapters/__init__.py
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19625 Speed up `DataAdapter` tests by testing only the current backend.
  keras/src/trainers/data_adapters/array_data_adapter_test.py
  keras/src/trainers/data_adapters/generator_data_adapter_test.py
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
  keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
  keras/src/trainers/data_adapters/torch_data_loader_adapter_test.py
Labels: size:M

#19588 feat(ops): support np.argpartition
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19628 feat(math): support erfinv on mlx
  keras/src/backend/mlx/math.py
  keras/src/backend/mlx/trainer.py
Labels: kokoro:force-run, ready to pull, size:XS

#19635 fix(ops): specify `NonZero` output dtype and add test coverage
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19633 Fix `ops.ctc_decode`
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19636 Ensure the same rule applies for np arrays in autocasting
  keras/src/dtype_policies/dtype_policy.py
  keras/src/layers/layer_test.py
  keras/src/layers/normalization/spectral_normalization_test.py
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:M

#19641 support conv3d on cpu for TF
  keras/src/backend/tensorflow/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:S
