Repository keras-team/keras, pull requests merged in 2024-10, with the labels that each got.

#20316 [Keras Ops] Add Histogram Operation
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/backend/jax/math.py
  keras/src/backend/numpy/math.py
  keras/src/backend/tensorflow/math.py
  keras/src/backend/torch/math.py
  keras/src/ops/math.py
  keras/src/ops/math_test.py
Labels: size:M

#20315 Disable XLA with TensorFlow determinisim
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20326 Fix deprecated AlphaDropout layer, seed=... was in wrong place
  keras/src/legacy/layers.py
Labels: kokoro:force-run, ready to pull, size:XS

#20313 Added a new Spectrogram layer based on Conv1D operations, supporting GPU-parallelization and fine-tuning
  keras/api/_tf_keras/keras/initializers/__init__.py
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/initializers/__init__.py
  keras/api/layers/__init__.py
  keras/src/initializers/__init__.py
  keras/src/initializers/constant_initializers.py
  keras/src/initializers/constant_initializers_test.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/stft_spectrogram.py
  keras/src/layers/preprocessing/stft_spectrogram_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20152 Flash attention support.
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: ready to pull, size:M

#20331 Fix typos in documentation Initializer
  keras/src/initializers/initializer.py
Labels: kokoro:force-run, ready to pull, size:XS

#20338 Update RNN doc on fixed batch size (re: #20327)
  keras/src/layers/rnn/rnn.py
Labels: kokoro:force-run, ready to pull, size:XS

#20337 Fix `set_tensor_attr` so that setting `None` clears the attribute.
  keras/src/backend/common/masking_test.py
  keras/src/backend/common/tensor_attributes.py
Labels: kokoro:force-run, ready to pull, size:M

#20330 Move public exports from `exports.py` to `backend/__init__py`.
  keras/api/__init__.py
  keras/api/_tf_keras/keras/__init__.py
  keras/src/backend/__init__.py
  keras/src/backend/exports.py
  keras/src/backend/jax/__init__.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/__init__.py
  keras/src/backend/numpy/core.py
  keras/src/backend/tests/device_scope_test.py
  keras/src/backend/torch/__init__.py
  keras/src/backend/torch/core.py
  keras/src/layers/preprocessing/normalization_test.py
  keras/src/random/seed_generator.py
  keras/src/utils/torch_utils.py
Labels: kokoro:force-run, ready to pull, size:M

#20340 Remove MultiHeadAttention assertion that last dims of Q and V need to be equal
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20321 Pass config to constructor when reviving custom functional model
  keras/src/models/functional.py
  keras/src/models/model_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20345 Fix absence of filtering in CompileLoss when not built
  keras/src/trainers/compile_utils.py
Labels: kokoro:force-run, ready to pull, size:S

#20348 Restrict the inputs of `ops.pad()`
  keras/src/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#20349 Allow passing custom dataset adapters.
  keras/src/layers/core/embedding.py
  keras/src/trainers/data_adapters/__init__.py
Labels: kokoro:force-run, ready to pull, size:XS

#20353 stop_gradient in SpectralNormalization wrapper
  keras/src/layers/normalization/spectral_normalization.py
Labels: kokoro:force-run, ready to pull, size:XS

#20352 Clarification: new mean option is synonym with sum_over_batch_size in loss function base class
  keras/src/losses/loss.py
  keras/src/losses/loss_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20292 Modified example in DepthwiseConv2D file
  keras/src/layers/convolutional/depthwise_conv2d.py
Labels: size:XS, awaiting review

#20364 Added two new correlation metrics, Pearson and Concordance Correlation Coefficients.
  keras/api/_tf_keras/keras/metrics/__init__.py
  keras/api/metrics/__init__.py
  keras/src/metrics/__init__.py
  keras/src/metrics/correlation_metrics.py
  keras/src/metrics/correlation_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20367 Fix deserializing pipeline layers
  keras/src/layers/preprocessing/pipeline.py
  keras/src/layers/preprocessing/pipeline_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20374 Fix `set_tensor_attr` bug related to garbage collection.
  keras/src/backend/common/tensor_attributes.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20380 Refactor `pythonify_logs` and add custom fit integration tests.
  .github/workflows/actions.yml
  integration_tests/jax_custom_fit_test.py
  integration_tests/tf_custom_fit_test.py
  integration_tests/torch_custom_fit_test.py
  keras/src/backend/numpy/trainer.py
  keras/src/callbacks/callback_list.py
  keras/src/trainers/trainer.py
  keras/src/utils/python_utils.py
Labels: kokoro:force-run, ready to pull, size:L

#20379 Preserve tuple type in json dump/load
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:S

#20377 Addressed variable names mismatch in example code in softmax.py
  keras/src/layers/activations/softmax.py
Labels: kokoro:force-run, ready to pull, size:XS

#20383 Added `IS_THREAD_SAFE` backend flag
  keras/src/backend/common/thread_safe_test.py
  keras/src/backend/jax/__init__.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/__init__.py
  keras/src/backend/numpy/core.py
  keras/src/backend/tensorflow/__init__.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/torch/__init__.py
  keras/src/backend/torch/core.py
  keras/src/callbacks/callback_list.py
Labels: ready to pull, size:S

#20358 Enable Structured Losses
  keras/src/losses/losses.py
  keras/src/models/model_test.py
  keras/src/trainers/compile_utils.py
  keras/src/trainers/compile_utils_test.py
  keras/src/tree/optree_impl.py
Labels: size:L, awaiting review

#20385 Fix GroupNormalization compute dtype
  keras/src/layers/normalization/group_normalization.py
Labels: kokoro:force-run, ready to pull, size:S

#20384 Add celu activation layer for each nn.py
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20396 `EpochIterator`, `TensorFlowTrainer` : refactoring and fixes
  keras/src/backend/jax/trainer.py
  keras/src/backend/numpy/trainer.py
  keras/src/backend/tensorflow/distribute_test.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/backend/torch/trainer.py
  keras/src/trainers/epoch_iterator.py
  keras/src/trainers/epoch_iterator_test.py
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20368 [Bounding Boxes] Add Support for Bounding Box Transformations during Image Resizing
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/_tf_keras/keras/utils/__init__.py
  keras/api/_tf_keras/keras/utils/bounding_boxes/__init__.py
  keras/api/layers/__init__.py
  keras/api/utils/__init__.py
  keras/api/utils/bounding_boxes/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/auto_contrast.py
  keras/src/layers/preprocessing/image_preprocessing/base_image_preprocessing_layer.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/bounding_box.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/converters.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/validation.py
  keras/src/layers/preprocessing/image_preprocessing/max_num_bounding_box.py
  keras/src/layers/preprocessing/image_preprocessing/max_num_bounding_box_test.py
  keras/src/layers/preprocessing/image_preprocessing/random_brightness.py
  keras/src/layers/preprocessing/image_preprocessing/random_contrast.py
  keras/src/layers/preprocessing/image_preprocessing/random_crop.py
  keras/src/layers/preprocessing/image_preprocessing/random_flip.py
  keras/src/layers/preprocessing/image_preprocessing/random_rotation.py
  keras/src/layers/preprocessing/image_preprocessing/random_translation.py
  keras/src/layers/preprocessing/image_preprocessing/random_zoom.py
  keras/src/layers/preprocessing/image_preprocessing/resizing.py
  keras/src/layers/preprocessing/image_preprocessing/resizing_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20386 Allow some TF kernels fusion: tf.nn.bias_add as special case of tf.add
  keras/src/backend/tensorflow/numpy.py
  keras/src/layers/convolutional/base_conv.py
  keras/src/layers/convolutional/base_conv_transpose.py
  keras/src/layers/convolutional/base_depthwise_conv.py
  keras/src/layers/convolutional/base_separable_conv.py
  keras/src/layers/convolutional/conv1d.py
Labels: kokoro:force-run, ready to pull, size:S

#20392 Add GLU activation
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20403 Updated keras.layers.activations.ReLU API with keras.layers.ReLU in E…
  keras/src/layers/activations/relu.py
Labels: kokoro:force-run, ready to pull, size:XS

#20401 [Visualization utils] Add visualization utils for plotting images(plain, with bounding boxes and segmentation masks)
  keras/__init__.py
  keras/api/__init__.py
  keras/api/_tf_keras/keras/__init__.py
  keras/api/_tf_keras/keras/visualization/__init__.py
  keras/api/visualization/__init__.py
  keras/src/__init__.py
  keras/src/visualization/__init__.py
  keras/src/visualization/draw_bounding_boxes.py
  keras/src/visualization/draw_segmentation_masks.py
  keras/src/visualization/plot_bounding_box_gallery.py
  keras/src/visualization/plot_image_gallery.py
  keras/src/visualization/plot_segmentation_mask_gallery.py
Labels: kokoro:force-run, ready to pull, size:L

#20406 Fix serialization / deserialization.
  keras/src/saving/saving_lib_test.py
  keras/src/saving/serialization_lib.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20404 Fixed the Value error in Example from activation.py
  keras/src/layers/activations/activation.py
Labels: kokoro:force-run, ready to pull, size:XS

#20405 Add hard_tanh activation function
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20413 Patch to fix TF1 shape comparison in add function
  keras/src/backend/tensorflow/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#20410 Add `mean_with_sample_weight` reduction to `Loss`
  keras/src/backend/numpy/numpy.py
  keras/src/losses/loss.py
  keras/src/losses/loss_test.py
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20412 Jax tracing fix
  keras/src/backend/jax/trainer.py
  keras/src/trainers/data_adapters/generator_data_adapter.py
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20416 Add log_sigmoid activation
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/activations/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20417 correct misspelling and test case
  keras/src/activations/activations_test.py
  keras/src/ops/nn.py
Labels: kokoro:force-run, ready to pull, size:XS

#20422 Fix additional shape comparison for TF1 compatibility
  keras/src/backend/tensorflow/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#20431 Add `tree.flatten_with_path` and `tree.assert_same_paths` methods.
  keras/api/_tf_keras/keras/tree/__init__.py
  keras/api/tree/__init__.py
  keras/src/tree/__init__.py
  keras/src/tree/dmtree_impl.py
  keras/src/tree/optree_impl.py
  keras/src/tree/tree_api.py
  keras/src/tree/tree_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20426 `CompileLoss`: Allow different but reconcilable structures for `y_true` and `y_pred`
  keras/src/models/model_test.py
  keras/src/trainers/compile_utils.py
  keras/src/trainers/compile_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20433 Add `from_sorted_ids` option to `SparseTopKCategoricalAccuracy`.
  keras/src/metrics/accuracy_metrics.py
  keras/src/metrics/accuracy_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review
