Repository keras-team/keras, pull requests merged in 2024-02, with the labels that each got.

#19126 Fixed formatting that preventing error message from printing.
  keras/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:XS

#19133 Fix performance regression for ArrayDataAdapter with Torch backend.
  keras/trainers/data_adapters/array_data_adapter.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19136 Add `self._jax_state_synced` in `__init__` in jax's trainer
  keras/backend/jax/trainer.py
  keras/callbacks/callback.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19135 Support nested structures in while loops
  keras/backend/jax/core.py
  keras/backend/numpy/core.py
  keras/backend/tensorflow/core.py
  keras/backend/torch/core.py
  keras/ops/core.py
  keras/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19123 Add unit tests to `backend/common/dtypes_test.py`
  keras/backend/common/dtypes_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19138 Fixing typos in doc
  benchmarks/model_benchmark/bert_benchmark.py
  examples/demo_jax_distributed.py
Labels: kokoro:force-run, ready to pull, size:XS

#19142 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready to pull, size:XS

#19144 [keras/ops/numpy.py] Use a more standard docstring format for `meshgrid`
  keras/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#19158 Show billions of parameters in model summary
  keras/utils/summary_utils.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19161 Fix JAX GPU CI Cuda error by fixing JAX version
  requirements-jax-cuda.txt
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19162 Fix for `keras.metrics.Mean` when the sum of weights is negative.
  keras/metrics/reduction_metrics.py
  keras/metrics/reduction_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19165 Wrap JAX export variables in TF variable, add test for JAX with TF function endpoint
  keras/export/export_lib.py
  keras/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19166 Fixes JAX-native serialization bug
  keras/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19169 #19168: Fix a typo
  keras/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#19170 Minor cleanup for the unnecessary tf.summary.record_if(True) (no_op)
  keras/callbacks/tensorboard.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19172 Disable Dependabot auto-update for JAX GPU
  .github/dependabot.yml
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19176 Add support for `IterableDataset` to `TorchDataLoaderAdapter`.
  keras/backend/jax/trainer.py
  keras/backend/tensorflow/trainer.py
  keras/backend/torch/trainer.py
  keras/trainers/data_adapters/tf_dataset_adapter.py
  keras/trainers/data_adapters/torch_data_loader_adapter.py
  keras/trainers/data_adapters/torch_data_loader_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19154 Add `normalize` ops
  keras/ops/nn.py
  keras/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19184 Add weights param to category_encoding
  keras/layers/preprocessing/category_encoding.py
  keras/layers/preprocessing/category_encoding_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19185 Fix Functional model slicing
  keras/models/functional.py
  keras/models/functional_test.py
  keras/ops/function.py
Labels: size:M

#19186 Add `convert_to_tensor` in certain ops in JAX
  keras/backend/jax/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#19188 Numpy backend requires torch
  keras/backend/numpy/linalg.py
Labels: kokoro:force-run, ready to pull, size:XS

#19190 Fix(preprocessing): resolve `ValueError` for `ngrams` tuple
  keras/layers/preprocessing/text_vectorization.py
  keras/layers/preprocessing/text_vectorization_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19157 Add `ops.image.crop_images`
  keras/ops/image.py
  keras/ops/image_test.py
Labels: ready to pull, size:M

#19201 Fix typo in keras.distribution.initialize
  keras/backend/jax/distribution_lib.py
  keras/backend/jax/distribution_lib_test.py
Labels: ready to pull, size:S

#19202 Check raised regex in convolutional tests
  keras/layers/convolutional/base_depthwise_conv.py
  keras/layers/convolutional/base_separable_conv.py
  keras/layers/convolutional/conv_test.py
  keras/layers/convolutional/conv_transpose_test.py
  keras/layers/convolutional/depthwise_conv_test.py
  keras/layers/convolutional/separable_conv_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19205 Adds psutil deps for CI Log Reader
  .kokoro/github/ubuntu/gpu/build.sh
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19206 Add `_untrack_variable` to `Layer` and explicitly define `constraint` and `regularizer` to `KerasVariable`
  keras/backend/common/variables.py
  keras/layers/core/dense.py
  keras/layers/core/einsum_dense.py
  keras/layers/core/embedding.py
  keras/layers/layer.py
  keras/layers/layer_test.py
  keras/optimizers/base_optimizer.py
  keras/utils/tracking.py
Labels: ready to pull, size:M, awaiting review

#18962 Adds initial support for an MLX backend
  .github/workflows/actions.yml
  .github/workflows/config/mlx/keras.json
  integration_tests/import_test.py
  keras/backend/common/variables.py
  keras/backend/mlx/__init__.py
  keras/backend/mlx/core.py
  keras/backend/mlx/image.py
  keras/backend/mlx/layer.py
  keras/backend/mlx/math.py
  keras/backend/mlx/nn.py
  keras/backend/mlx/numpy.py
  keras/backend/mlx/random.py
  keras/backend/mlx/rnn.py
  keras/backend/mlx/trainer.py
  keras/layers/layer.py
  keras/models/model.py
  keras/trainers/trainer_test.py
  requirements.txt
Labels: stat:awaiting keras-eng, kokoro:force-run, ready to pull, size:XL, awaiting review

#19207 Support `torch._int_mm` in torch's `ops.matmul`
  keras/backend/torch/numpy.py
  keras/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19217 Fix `test_case.run_layer` which was not training with `training=True`.
  keras/layers/normalization/spectral_normalization.py
  keras/layers/regularization/alpha_dropout.py
  keras/layers/rnn/rnn.py
  keras/testing/test_case.py
Labels: size:M

#19212 Add workflow test for multiple unknown JAX dimensions
  keras/backend/common/variables.py
  keras/backend/common/variables_test.py
  keras/export/export_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19222 Update CI to TF 2.16 RC0
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#19194 Add: `MelSpectrogram` layer
  keras/layers/__init__.py
  keras/layers/preprocessing/audio_preprocessing.py
  keras/layers/preprocessing/audio_preprocessing_test.py
Labels: ready to pull, size:L

#19228 Remove prints from image dataset from directory
  keras/utils/dataset_utils.py
  keras/utils/image_dataset_utils.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19181 [keras/saving/object_registration.py] Set `CustomObjectScope` dictionary arg type to `str` rather than `name`
  keras/saving/object_registration.py
Labels: kokoro:force-run, ready to pull, size:XS

#19232 Fix for TF XLA compilation error for `SpectralNormalization`.
  keras/backend/tensorflow/linalg.py
  keras/layers/normalization/spectral_normalization_test.py
  keras/ops/linalg.py
  keras/ops/linalg_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19233 Decorate `binomial` and `beta` functions with `keras_export`
  keras/random/random.py
Labels: kokoro:force-run, ready to pull, size:XS

#19240 Disable TFSMLayer for all backends except TF
  keras/export/export_lib.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review
