Repository keras-team/keras, pull requests merged in 2024-07, with the labels that each got.

#19940 resolve torch device placement issue for associative_scan
  keras/src/backend/torch/core.py
Labels: kokoro:force-run, ready to pull, size:XS

#19941 address zero division in crops
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/tensorflow/image.py
  keras/src/backend/torch/image.py
  keras/src/layers/preprocessing/center_crop_test.py
  keras/src/layers/preprocessing/resizing_test.py
  keras/src/utils/image_utils.py
Labels: kokoro:force-run, ready to pull, size:S

#19945 Fix `Trainer._symbolic_build`
  keras/src/trainers/trainer.py
Labels: kokoro:force-run, ready to pull, size:S

#19946 Fix for a change in JAX's promotion rules for `floor` and `ceil`.
  keras/src/backend/jax/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19948 Fix `tf.save_model.save()` for models which take an input structure a…
  keras/src/backend/tensorflow/layer.py
  keras/src/backend/tensorflow/saved_model_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19947 Enable distribution test
  .kokoro/github/ubuntu/gpu/build.sh
Labels: ready to pull, size:XS, awaiting review, Gemma

#19950 Fix docstring: typo for setting environment variables
  keras/src/distribution/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:XS

#19949 Add `type_check` for `quantize`
  keras/src/layers/core/dense.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/core/embedding.py
  keras/src/layers/core/embedding_test.py
  keras/src/layers/layer.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19955 Improve `keras.Variable`'s dtype consistency and add `__int__`, `__float__` and `__round__`
  keras/src/backend/common/keras_tensor.py
  keras/src/backend/common/variables.py
  keras/src/backend/common/variables_test.py
  keras/src/backend/exports.py
  keras/src/backend/torch/core.py
  keras/src/random/seed_generator.py
Labels: kokoro:force-run, ready to pull, size:L

#19956 Remove upperbound for torch version
  keras/src/backend/torch/core.py
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19922 Add keras.ops.searchsorted
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19958 add on_epoch_begin for dataset
  guides/training_with_built_in_methods.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/trainers/data_adapters/data_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/epoch_iterator.py
  keras/src/trainers/epoch_iterator_test.py
Labels: ready to pull, size:M

#19968 Fix `_to_jax_device()`
  keras/src/backend/jax/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#19966 Cast random.categorical seed to int32 in TF backend
  keras/src/backend/tensorflow/random.py
  keras/src/backend/tensorflow/random_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19963 fixing segment_max edge cases and add more exception handling
  keras/src/backend/numpy/math.py
  keras/src/backend/tensorflow/math.py
  keras/src/backend/torch/math.py
  keras/src/ops/math.py
  keras/src/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:L

#19972 Add `bool` support to `ops.nn.one_hot` and `ops.nn.multi_hot` for the…
  keras/src/backend/tensorflow/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19975 Fix TF's GPU CI
  keras/src/backend/tensorflow/random_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19973 More robust MHA errors for mismatched shapes
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19978 Fix dtype inconsistency of random seed in tensorflow backend
  keras/src/backend/tensorflow/random.py
  keras/src/backend/tensorflow/random_test.py
  keras/src/random/random_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19980 Updated docstring for `Model.compute_metrics()`.
  keras/src/trainers/trainer.py
Labels: kokoro:force-run, ready to pull, size:S

#19979 Fix torch average pooling
  keras/src/backend/torch/nn.py
  keras/src/layers/pooling/average_pooling_test.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19981 add lamb optimizer
  keras/api/_tf_keras/keras/optimizers/__init__.py
  keras/api/optimizers/__init__.py
  keras/src/optimizers/lamb.py
  keras/src/optimizers/lamb_test.py
Labels: kokoro:force-run, ready to pull, size:M

#19969 Actually sum gradient for tf distribute
  keras/src/backend/tensorflow/optimizer.py
  keras/src/backend/tensorflow/optimizer_distribute_test.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#19987 Change dtypes for test_dtypes test case.
  integration_tests/dataset_tests/cifar100_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20002 Extend support to `Sequential._maybe_build` for functional/sequential models
  keras/src/models/sequential.py
  keras/src/models/sequential_test.py
  keras/src/utils/summary_utils.py
Labels: ready to pull, size:M

#20007 Use Numpy arrays in data adapters for JAX backend.
  keras/src/backend/jax/distribution_lib.py
  keras/src/trainers/data_adapters/array_data_adapter.py
  keras/src/trainers/data_adapters/array_data_adapter_test.py
  keras/src/trainers/data_adapters/array_slicing.py
  keras/src/trainers/data_adapters/data_adapter.py
  keras/src/trainers/data_adapters/data_adapter_utils.py
  keras/src/trainers/data_adapters/generator_data_adapter.py
  keras/src/trainers/data_adapters/generator_data_adapter_test.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
  keras/src/trainers/data_adapters/tf_dataset_adapter.py
  keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
  keras/src/trainers/data_adapters/torch_data_loader_adapter.py
  keras/src/trainers/data_adapters/torch_data_loader_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20009 Correct test case for ImdbLoadDataTest
  integration_tests/dataset_tests/imdb_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#19998 Fix gradient accumulation
  keras/src/backend/jax/optimizer.py
  keras/src/backend/tensorflow/optimizer_distribute_test.py
  keras/src/optimizers/base_optimizer.py
  keras/src/optimizers/optimizer_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20008 Fix conv + channel_first + tensorflow + CPU
  keras/src/backend/tensorflow/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19989 Avoid exceptions in `save_model` and `load_model`
  keras/src/saving/saving_lib.py
  keras/src/saving/saving_lib_test.py
  keras/src/utils/summary_utils.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20013 Remove duplicated code from rnn.py
  keras/src/layers/rnn/rnn.py
Labels: kokoro:force-run, ready to pull, size:XS

#20014 Revert to the original default behavior of `dtype` in `Loss` and `Metric`
  keras/src/losses/loss.py
  keras/src/losses/loss_test.py
  keras/src/metrics/metric.py
  keras/src/metrics/metric_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20015 Simplify and improve `CompileLoss`
  keras/src/models/model_test.py
  keras/src/trainers/compile_utils.py
Labels: kokoro:force-run, ready to pull, size:L

#20017 Rollback tf distribute change
  keras/src/backend/tensorflow/optimizer.py
  keras/src/backend/tensorflow/optimizer_distribute_test.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/ops/nn_test.py
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20022 Fixing issue #20021: Unexpected result on keras.ops.nn.softmax when running with tuple axis
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20025 Fix test_softmax_correctness_with_axis_tuple test case failed on torch gpu ci.
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20026 Fix `reset_state` for some metrics
  guides/training_with_built_in_methods.py
  keras/src/metrics/metric_test.py
  keras/src/metrics/reduction_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#20029 Fix QLoRA saving/loading
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
Labels: kokoro:force-run, ready to pull, size:S, Gemma

#20018 Faster host to device transfer on Jax backend
  keras/src/backend/jax/trainer.py
  keras/src/distribution/distribution_lib.py
Labels: ready to pull, size:S, awaiting review

#20033 Fix jax's `in_top_k` and numpy's `top_k`
  keras/src/backend/jax/math.py
  keras/src/backend/numpy/math.py
  keras/src/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20028 Fix log_softmax logic for tuple axis
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:S

#19954 Simplify the implementation of quantization-related methods
  keras/src/backend/torch/layer.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/embedding.py
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
  keras/src/models/model.py
  keras/src/models/model_test.py
  keras/src/quantizers/quantizers.py
Labels: ready to pull, size:M, awaiting review

#20034 Add clear deprecation error message for add_metric()
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20023 Bring back loss information for multiple outputs
  keras/__init__.py
  keras/api/__init__.py
  keras/api/_tf_keras/keras/__init__.py
  keras/src/backend/__init__.py
  keras/src/backend/common/symbolic_scope.py
  keras/src/backend/common/symbolic_scope_test.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/core.py
  keras/src/backend/numpy/trainer.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/torch/core.py
  keras/src/layers/layer.py
  keras/src/models/model_test.py
  keras/src/trainers/compile_utils.py
  keras/src/trainers/trainer.py
  keras/src/trainers/trainer_test.py
  keras/src/utils/torch_utils.py
  keras/src/utils/torch_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20040 Return value on KerasVariable assignment
  keras/src/backend/common/variables.py
  keras/src/backend/common/variables_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20041 Zero pad 1D data format parameter
  keras/src/layers/reshaping/zero_padding1d.py
  keras/src/layers/reshaping/zero_padding1d_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20042 Support torch `convert_to_numpy` for all devices
  keras/src/backend/torch/core.py
Labels: kokoro:force-run, ready to pull, size:XS

#20043 Remove non-used param & add initial value for callback.py
  keras/src/callbacks/callback.py
Labels: kokoro:force-run, ready to pull, size:XS

#20049 Migrate numpy namespace to numpy 2.0
  keras/src/callbacks/model_checkpoint.py
  keras/src/callbacks/reduce_lr_on_plateau.py
  keras/src/utils/sequence_utils.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20051 Reland tf distribute fix
  keras/src/backend/tensorflow/optimizer.py
  keras/src/backend/tensorflow/optimizer_distribute_test.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/ops/nn_test.py
  keras/src/trainers/trainer_test.py
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:M

#20057 Update batch_normalization.py
  keras/src/layers/normalization/batch_normalization.py
Labels: kokoro:force-run, ready to pull, size:S

#20059 2D CNN's and 3D CNN's description update.
  keras/src/layers/convolutional/conv2d.py
  keras/src/layers/convolutional/conv3d.py
Labels: kokoro:force-run, ready to pull, size:XS

#20062 Let Tensorflow call the initializer of variables when callable.
  keras/src/backend/common/variables.py
  keras/src/backend/tensorflow/core.py
Labels: kokoro:force-run, ready to pull, size:S

#20035 Fix Data+Model Distribution Issues
  keras/src/backend/jax/distribution_lib.py
  keras/src/backend/jax/distribution_lib_test.py
  keras/src/distribution/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:M

#20065 Fix dtype issue in `abs_max_quantize`
  keras/src/quantizers/quantizers.py
  keras/src/quantizers/quantizers_test.py
Labels: kokoro:force-run, ready to pull, size:S
