Repository keras-team/keras, pull requests merged in 2024-08, with the labels that each got.

#20076 Fix `input_shape` in `Sequential` model
  keras/src/layers/core/input_layer.py
  keras/src/models/sequential.py
  keras/src/models/sequential_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20079 Add numpy `scale` and `offset` support to `Rescaling`
  keras/src/layers/preprocessing/rescaling.py
  keras/src/layers/preprocessing/rescaling_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20082 Improve error handling in distribution lib
  keras/src/backend/jax/distribution_lib.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20088 Do not adapt TextVectorization preprocessor if provided with vocabulary in FeatureSpace.
  keras/src/layers/preprocessing/feature_space.py
  keras/src/layers/preprocessing/feature_space_test.py
  keras/src/layers/preprocessing/text_vectorization.py
Labels: kokoro:force-run, ready to pull, size:XS

#20089 Added dropout support in `ConvLSTMCell`.
  keras/src/layers/rnn/conv_lstm.py
  keras/src/layers/rnn/dropout_rnn_cell.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20091 Fix unbound local error in torch backend when a call to `train_step` generates no training logs
  keras/src/backend/torch/trainer.py
Labels: kokoro:force-run, ready to pull, size:XS

#20099 chore: fix typo
  keras/src/layers/preprocessing/string_lookup.py
Labels: kokoro:force-run, ready to pull, size:XS

#20107 Fix default value of `logs` in Trainer
  keras/src/backend/jax/trainer.py
  keras/src/backend/numpy/trainer.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/backend/torch/trainer.py
Labels: kokoro:force-run, ready to pull, size:S

#20101 Remove threshold limits in BinaryAccuracy()
  keras/src/metrics/accuracy_metrics.py
  keras/src/metrics/accuracy_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20110 Fix divide_no_nan jax op to be differentiable
  keras/src/backend/jax/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#20064 Handled nested structures for TensorFlow backend for keras.ops.map.
  keras/src/backend/tensorflow/core.py
  keras/src/backend/tensorflow/nestedstructure_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20114 Add `/readahead` to the list of recognized remote paths
  keras/src/utils/file_utils.py
  keras/src/utils/file_utils_test.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20121 TF cond with plain bool's
  keras/src/backend/tensorflow/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20122 Fix `svd` with `compute_uv=False`
  keras/src/backend/tensorflow/linalg.py
  keras/src/backend/torch/linalg.py
  keras/src/ops/linalg_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20120 Fix functional model output type after deserialization
  keras/src/models/functional.py
  keras/src/models/functional_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20125 Fix `ops.stop_gradient` for `KerasTensor`
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20126 Add bitwise ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20129 Fix JAX's `bitwise_*_shift` and `bitwise_invert`
  keras/src/backend/jax/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20123 Allow infinite `PyDataset`s to use multithreading/multiprocessing.
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20131 Fix `numpy` dtype CI
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20135 Allow more dtypes in layer test
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:S

#20137 Bug fix in `metrics_utils.py` when using Tensorflow.
  keras/src/metrics/metrics_utils.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20149 Fix `typing.cast` when using subclassing
  keras/src/models/functional.py
  keras/src/models/model.py
  keras/src/models/sequential.py
Labels: kokoro:force-run, ready to pull, size:XS

#20156 _get_node_attribute_at_index() raising AttributeError instead of ValueError
  keras/src/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:XS

#20159 Update pydot exception to match latest version
  keras/src/utils/model_visualization.py
Labels: kokoro:force-run, ready to pull, size:XS

#20157 [keras/src/{export/export_lib.py,models/model.py,utils/file_utils_test.py}] `os.path.join`
  keras/src/utils/file_utils_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20161 Fix duplicated filtering in CompileLoss when not built
  keras/src/trainers/compile_utils.py
Labels: kokoro:force-run, ready to pull, size:S

#20151 Added SparseTensor check on convert_to_np_if_not_ragged.
  keras/src/backend/tensorflow/trainer.py
  keras/src/backend/tensorflow/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20170 Add a warning for mismatched inputs structure in `Functional`
  keras/src/models/functional.py
  keras/src/models/functional_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20171 Simplify TF armax/argmin
  keras/src/backend/tensorflow/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#20168 Calling finalize_state() when loading legacy h5 weights
  keras/src/legacy/saving/legacy_h5_format.py
  keras/src/saving/saving_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20176 Correct failed test case for model_visualization_test.py
  keras/src/utils/model_visualization.py
Labels: kokoro:force-run, ready to pull, size:S

#20175 Mark layers with no state as built.
  keras/src/backend/torch/layer.py
  keras/src/layers/activations/activation.py
  keras/src/layers/activations/activation_test.py
  keras/src/layers/activations/elu.py
  keras/src/layers/activations/elu_test.py
  keras/src/layers/activations/leaky_relu.py
  keras/src/layers/activations/leaky_relu_test.py
  keras/src/layers/activations/relu.py
  keras/src/layers/activations/relu_test.py
  keras/src/layers/activations/softmax.py
  keras/src/layers/activations/softmax_test.py
  keras/src/layers/core/identity.py
  keras/src/layers/core/identity_test.py
  keras/src/layers/core/masking.py
  keras/src/layers/core/masking_test.py
  keras/src/layers/layer_test.py
  keras/src/layers/normalization/unit_normalization.py
  keras/src/layers/normalization/unit_normalization_test.py
  keras/src/layers/pooling/average_pooling_test.py
  keras/src/layers/pooling/base_global_pooling.py
  keras/src/layers/pooling/base_pooling.py
  keras/src/layers/pooling/global_average_pooling_test.py
  keras/src/layers/pooling/global_max_pooling_test.py
  keras/src/layers/pooling/max_pooling_test.py
  keras/src/layers/regularization/activity_regularization.py
  keras/src/layers/regularization/activity_regularization_test.py
  keras/src/layers/regularization/alpha_dropout.py
  keras/src/layers/regularization/alpha_dropout_test.py
  keras/src/layers/regularization/dropout.py
  keras/src/layers/regularization/dropout_test.py
  keras/src/layers/regularization/gaussian_dropout.py
  keras/src/layers/regularization/gaussian_dropout_test.py
  keras/src/layers/regularization/gaussian_noise.py
  keras/src/layers/regularization/gaussian_noise_test.py
  keras/src/layers/regularization/spatial_dropout_test.py
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:M

#20179 Update embedding.py
  keras/src/layers/core/embedding.py
Labels: kokoro:force-run, ready to pull, size:XS

#20185 fix: upload cifar10 and cifar100 datasets
  keras/src/datasets/cifar10.py
  keras/src/datasets/cifar100.py
Labels: kokoro:force-run, ready to pull, size:S

#20187 Updated classes details in Densenet Documentation
  keras/src/applications/densenet.py
Labels: kokoro:force-run, ready to pull, size:XS

#20186 Typo / spelling fixes
  .github/workflows/scripts/labeler.js
  guides/training_with_built_in_methods.py
  keras/src/applications/efficientnet.py
  keras/src/backend/common/backend_utils.py
  keras/src/backend/common/backend_utils_test.py
  keras/src/backend/common/variables_test.py
  keras/src/backend/jax/distribution_lib.py
  keras/src/backend/jax/distribution_lib_test.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/tensorflow/random.py
  keras/src/backend/torch/linalg.py
  keras/src/callbacks/model_checkpoint.py
  keras/src/distribution/distribution_lib.py
  keras/src/export/export_lib.py
  keras/src/layers/attention/grouped_query_attention_test.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/layers/convolutional/conv_transpose_test.py
  keras/src/layers/merging/merging_test.py
  keras/src/layers/preprocessing/hashed_crossing_test.py
  keras/src/layers/preprocessing/normalization.py
  keras/src/layers/preprocessing/text_vectorization.py
  keras/src/losses/losses_test.py
  keras/src/models/cloning.py
  keras/src/models/functional.py
  keras/src/ops/core.py
  keras/src/ops/linalg.py
  keras/src/ops/nn.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
  keras/src/optimizers/adamax.py
  keras/src/optimizers/loss_scale_optimizer.py
  keras/src/optimizers/optimizer_sparse_test.py
  keras/src/quantizers/quantizers.py
  keras/src/random/random.py
  keras/src/saving/object_registration.py
  keras/src/trainers/compile_utils.py
  keras/src/trainers/data_adapters/data_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/data_adapters/tf_dataset_adapter.py
  keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
  keras/src/trainers/trainer.py
  keras/src/utils/audio_dataset_utils_test.py
  keras/src/utils/dataset_utils.py
  keras/src/utils/numerical_utils_test.py
  keras/src/utils/timeseries_dataset_utils_test.py
Labels: kokoro:force-run, ready to pull, size:L
