Repository keras-team/keras, pull requests merged in 2025-10, with the labels that each got.

#21701 Fix deadlock in `CallbackList`.
  keras/src/callbacks/callback_list.py
Labels: ready to pull, size:M, awaiting review

#21716 Fix the Doc of the combination relation in func `keras.layers.Normalization()`
  keras/src/layers/preprocessing/normalization.py
Labels: kokoro:force-run, ready to pull, size:XS

#21719 Remove reliance on `__jax_array__` to unwrap variables.
  keras/src/backend/jax/nn.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/jax/optimizer.py
  keras/src/layers/attention/attention.py
  keras/src/layers/layer_test.py
  keras/src/layers/normalization/layer_normalization_test.py
  keras/src/layers/normalization/rms_normalization_test.py
  keras/src/layers/rnn/gru.py
  keras/src/layers/rnn/lstm.py
  keras/src/layers/rnn/simple_rnn.py
  keras/src/ops/core_test.py
  keras/src/ops/nn.py
  keras/src/optimizers/adafactor.py
  keras/src/optimizers/base_optimizer.py
  keras/src/optimizers/loss_scale_optimizer.py
Labels: ready to pull, size:M, awaiting review

#21613 Add linspace and logspace implementations in OpenVINO NumPy backend
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: ready to pull, size:M, backend:OpenVino

#21720 Add jvp op
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/linalg/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/linalg/__init__.py
  keras/src/backend/jax/linalg.py
  keras/src/backend/numpy/linalg.py
  keras/src/backend/openvino/linalg.py
  keras/src/backend/tensorflow/linalg.py
  keras/src/backend/torch/linalg.py
  keras/src/ops/linalg.py
  keras/src/ops/linalg_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21685 Add unfold op
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/openvino/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21566 Add daily Python 3.13 CPU-only tests to nightly workflow
  .github/workflows/nightly.yml
Labels: ready to pull, size:M, awaiting review
