Repository keras-team/keras, pull requests merged in 2025-04, with the labels that each got.

#21136 fixed torch version issue for macOS
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS

#21142 Add alpha argument description to elu docstring
  keras/src/activations/activations.py
Labels: kokoro:force-run, ready to pull, size:XS

#21141 [OpenVINO backend] Support numpy.expm1
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#21134 Fix Functional model graph under global dtype policy.
  keras/src/layers/layer.py
  keras/src/models/functional_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21083 [OpenVINO backend]: Implement numpy.identity
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21104 Enable SparseCategoricalCrossentropy to accept and propagate axis
  keras/src/backend/torch/nn.py
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
Labels: ready to pull, size:L

#21125 Modified Example code in numerical_utils
  keras/src/utils/numerical_utils.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#21139 Add configurable lora_alpha parameter for LoRA in multiple Keras layers
  keras/src/layers/convolutional/base_conv.py
  keras/src/layers/convolutional/conv_test.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/core/embedding.py
  keras/src/layers/core/embedding_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21060 Add OpenVINO backend support for argmin and argmax
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#21148 Add support for dynamic dimensions for ops handling `tf.IndexedSlices`.
  keras/src/backend/tensorflow/sparse.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#21138 [OpenVINO backend] Added support for numpy.isclose operation
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#21149 Aligns Softmax masking behavior with JAX for fully masked axis
  keras/src/layers/activations/softmax.py
  keras/src/layers/activations/softmax_test.py
Labels: size:M, awaiting review

#21157 Add verification to remat tests. (#21102)
  keras/src/layers/layer_test.py
Labels: ready to pull, size:M, awaiting review

#21164 Removing references to jax.config.spmd_mode('allow_all').
  keras/src/backend/jax/trainer.py
Labels: kokoro:force-run, ready to pull

#21160 allow TorchModuleWrapper compute output shape
  keras/src/utils/torch_utils.py
  keras/src/utils/torch_utils_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21165 Add details when `TestCase.run_layer_test` output verification fails.
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21170 Improve `tf.RaggedTensor` support in `DataAdapter`s.
  keras/src/trainers/data_adapters/data_adapter_utils.py
  keras/src/trainers/data_adapters/generator_data_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21135 WIP: Add PyTorch backend support for LSTM with CuDNN optimization
  keras/src/backend/torch/rnn.py
  pyproject.toml
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#21171 Add `tf.RaggedTensor` support to `Embedding` layer.
  keras/src/backend/tensorflow/numpy.py
  keras/src/layers/core/embedding.py
  keras/src/layers/core/embedding_test.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21176 [OpenVINO Backend]: support numpy.ndim
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:XS

#21177 Fix Embedding test with ragged tensors on GPU.
  keras/src/testing/test_case.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21175 Add sparse_sigmoid activation
  keras/api/_tf_keras/keras/activations/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/activations/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/activations/__init__.py
  keras/src/activations/activations.py
  keras/src/activations/activations_test.py
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: ready to pull, size:M

#21163 [OpenVINO BACKEND] - feat: implement numpy.nonzero for openvino backend
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:XS

#21181 Add sparse support to `ops.ones_like` and `ops.zeros_like`.
  keras/src/backend/jax/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21184 Fix dtype detection for JAX types.
  keras/src/backend/common/variables.py
Labels: ready to pull, size:XS

#21180 `mlx` - test updates and signbit implementation
  .github/workflows/actions.yml
  keras/api/__init__.py
  keras/api/_tf_keras/keras/__init__.py
  keras/src/backend/common/variables_test.py
  keras/src/backend/mlx/core.py
  keras/src/backend/mlx/image.py
  keras/src/backend/mlx/math.py
  keras/src/backend/mlx/nn.py
  keras/src/backend/mlx/numpy.py
  keras/src/initializers/constant_initializers_test.py
  keras/src/layers/activations/activation.py
  keras/src/layers/activations/elu.py
  keras/src/layers/core/identity.py
  keras/src/layers/pooling/base_global_pooling.py
  keras/src/layers/pooling/base_pooling.py
  keras/src/layers/regularization/activity_regularization.py
  keras/src/layers/regularization/alpha_dropout.py
  keras/src/layers/regularization/dropout.py
  keras/src/layers/regularization/gaussian_dropout.py
  keras/src/layers/regularization/gaussian_noise.py
  keras/src/ops/numpy_test.py
  keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:M

#21192 Fix `Embedding.compute_output_spec` with a non-`KerasTensor` input.
  keras/src/layers/core/embedding.py
  keras/src/trainers/data_adapters/generator_data_adapter_test.py
Labels: ready to pull, size:XS, awaiting review

#21195 Allow `Embedding` subclasses to only override `compute_output_shape`.
  keras/src/layers/core/embedding.py
Labels: ready to pull, size:XS, awaiting review

#21194 Return explicitly layout if already set on variable.
  keras/src/distribution/distribution_lib.py
  keras/src/distribution/distribution_lib_test.py
Labels: ready to pull, size:S

#21193 Don't scale gradients if overwriting variable with gradient.
  keras/src/optimizers/base_optimizer.py
  keras/src/optimizers/loss_scale_optimizer.py
  keras/src/optimizers/loss_scale_optimizer_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21197 Add back shell/format.sh, but it just runs pre-commit
  shell/format.sh
Labels: kokoro:force-run, ready to pull, size:S

#21198 Add openvino to the basic requirements file
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  README.md
  requirements-common.txt
  requirements-openvino.txt
Labels: kokoro:force-run, ready to pull, size:S

#21129 [Keras 3 OpenVINO Backend]: Support numpy.log1p operation #29487
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#21199 Add pre-commit to the common requirements file
  requirements-common.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XS

#21202 `mlx` - new image ops implemented
  keras/src/backend/mlx/image.py
  keras/src/backend/mlx/random.py
Labels: kokoro:force-run, ready to pull, size:L

#21203 Fix nightly releases
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
Labels: ready to pull, size:S, awaiting review

#21204 Adds Support For Custom Call-Context Arguments
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
  keras/src/models/functional.py
  keras/src/models/sequential.py
Labels: ready to pull, size:M, awaiting review

#21211 Recognize /tfhub as a remote location.
  keras/src/utils/file_utils.py
  keras/src/utils/file_utils_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#21212 Fix Trainer.get_compile_config base case (empty dict)
  keras/src/trainers/trainer.py
Labels: kokoro:force-run, ready to pull, size:XS

#21200 Implement angle function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: size:M, awaiting review

#21186 [OpenVINO Backend] : add support for numpy.nan_to_num
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:M

#21233 Clear static loss-scale for inner optimizer in LossScaleOptimizer.
  keras/src/optimizers/loss_scale_optimizer.py
  keras/src/optimizers/loss_scale_optimizer_test.py
Labels: kokoro:force-run, ready to pull, size:S

#21220 Update conftest.py
  conftest.py
Labels: kokoro:force-run, ready to pull, size:XS

#21222 Adds `_register_call_context_args` to declare and use call-context arguments.
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21227 Updated confusion_metrics.py
  keras/src/metrics/confusion_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#21232 Don't create unused optimizer variables.
  keras/src/backend/torch/optimizers/torch_parallel_optimizer.py
  keras/src/optimizers/adadelta.py
  keras/src/optimizers/adafactor.py
  keras/src/optimizers/adagrad.py
  keras/src/optimizers/adam.py
  keras/src/optimizers/adamax.py
  keras/src/optimizers/base_optimizer.py
  keras/src/optimizers/ftrl.py
  keras/src/optimizers/lamb.py
  keras/src/optimizers/lion.py
  keras/src/optimizers/loss_scale_optimizer.py
  keras/src/optimizers/muon.py
  keras/src/optimizers/nadam.py
  keras/src/optimizers/rmsprop.py
  keras/src/optimizers/sgd.py
Labels: ready to pull, size:L

#21214 Implement bartlett function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: ready to pull, size:M
