Repository keras-team/keras, pull requests merged in 2025-03, with the labels that each got.

#20951 [OpenVINO backend] Support numpy.append
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:S, awaiting review

#20916 Fix PyTorch stateful RNN/LSTM gradient computation error resolves #20875
  keras/src/layers/rnn/rnn.py
Labels: kokoro:force-run, ready to pull, size:S

#20911 [Keras Ops and Layer] Add keras.ops.rms_norm() and keras.layers.RMSNormalization()
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/layers/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/normalization/layer_normalization.py
  keras/src/layers/normalization/rms_normalization.py
  keras/src/layers/normalization/rms_normalization_test.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: ready to pull, size:M, awaiting review

#20983 Enable cuDNN RNNs when dropout is set and `training=True`
  keras/src/layers/rnn/gru.py
  keras/src/layers/rnn/lstm.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20971 Fix `Discretization` serialization when `num_bins` is used.
  keras/src/layers/preprocessing/discretization.py
  keras/src/layers/preprocessing/discretization_test.py
Labels: size:M, awaiting review

#20897 Add access to native mesh and layout distribution objects.
  keras/src/backend/jax/core.py
  keras/src/backend/jax/distribution_lib.py
  keras/src/backend/jax/distribution_lib_test.py
  keras/src/backend/jax/trainer.py
  keras/src/backend/tensorflow/distribution_lib.py
  keras/src/distribution/distribution_lib.py
Labels: ready to pull, size:M, awaiting review

#20989 Don't require jax on the numpy backend
  keras/src/backend/numpy/image.py
Labels: kokoro:force-run, ready to pull, size:XS

#20993 Fixes inconsistent serialization logic for inputs
  keras/src/models/functional.py
  keras/src/models/functional_test.py
Labels: ready to pull, size:S

#20994 Fix flash attention TPU error
  keras/src/backend/jax/nn.py
Labels: size:M

#20996 `mlx` - updates post compilation
  keras/src/backend/mlx/core.py
  keras/src/backend/mlx/export.py
  keras/src/backend/mlx/math.py
  keras/src/backend/mlx/nn.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/normalization/spectral_normalization.py
  keras/src/layers/preprocessing/normalization.py
  keras/src/layers/reshaping/up_sampling2d_test.py
  keras/src/losses/losses.py
  keras/src/models/model_test.py
  keras/src/optimizers/loss_scale_optimizer.py
Labels: kokoro:force-run, ready to pull, size:L

#20999 Add optional arg for attention logits soft cap for jax tpu backend
  keras/src/backend/jax/nn.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/torch/nn.py
  keras/src/ops/nn.py
Labels: ready to pull, size:S

#21000 Removed jax dependency from numpy image layer
  keras/src/backend/numpy/image.py
Labels: kokoro:force-run, ready to pull, size:M

#20995 Wrap tf variables in keras variables for TFSMLayer
  keras/src/backend/tensorflow/core.py
  keras/src/export/tfsm_layer.py
  keras/src/export/tfsm_layer_test.py
Labels: ready to pull, size:S, awaiting review

#21006 [OpenVINO Backend] Support numpy exp and expand_dims
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#20982 [Good First Issue][Keras 3 OpenVINO Backend]: Support numpy.dot operation #29119
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20977 Add elastic_transform processing for image.py
  keras/api/_tf_keras/keras/ops/image/__init__.py
  keras/api/ops/image/__init__.py
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/tensorflow/image.py
  keras/src/backend/torch/image.py
  keras/src/ops/image.py
  keras/src/ops/image_test.py
Labels: ready to pull, size:L

#20880 Ensures that the layer is marked as built when the `build` is not overriden
  keras/src/backend/tensorflow/saved_model_test.py
  keras/src/export/tfsm_layer.py
  keras/src/layers/activations/activation.py
  keras/src/layers/activations/elu.py
  keras/src/layers/activations/leaky_relu.py
  keras/src/layers/activations/prelu.py
  keras/src/layers/activations/relu.py
  keras/src/layers/activations/softmax.py
  keras/src/layers/attention/additive_attention.py
  keras/src/layers/attention/attention.py
  keras/src/layers/attention/grouped_query_attention.py
  keras/src/layers/attention/multi_head_attention.py
  keras/src/layers/convolutional/base_conv_transpose.py
  keras/src/layers/convolutional/base_depthwise_conv.py
  keras/src/layers/convolutional/base_separable_conv.py
  keras/src/layers/core/identity.py
  keras/src/layers/core/masking.py
  keras/src/layers/core/wrapper.py
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
  keras/src/layers/merging/base_merge.py
  keras/src/layers/merging/concatenate.py
  keras/src/layers/merging/dot.py
  keras/src/layers/normalization/batch_normalization.py
  keras/src/layers/normalization/layer_normalization.py
  keras/src/layers/normalization/unit_normalization.py
  keras/src/layers/pooling/base_global_pooling.py
  keras/src/layers/pooling/base_pooling.py
  keras/src/layers/preprocessing/discretization.py
  keras/src/layers/preprocessing/index_lookup.py
  keras/src/layers/preprocessing/normalization.py
  keras/src/layers/preprocessing/stft_spectrogram.py
  keras/src/layers/regularization/activity_regularization.py
  keras/src/layers/regularization/alpha_dropout.py
  keras/src/layers/regularization/dropout.py
  keras/src/layers/regularization/gaussian_dropout.py
  keras/src/layers/regularization/gaussian_noise.py
  keras/src/layers/reshaping/reshape.py
  keras/src/layers/rnn/bidirectional.py
  keras/src/layers/rnn/conv_lstm.py
  keras/src/layers/rnn/dropout_rnn_cell_test.py
  keras/src/layers/rnn/gru.py
  keras/src/layers/rnn/lstm.py
  keras/src/layers/rnn/rnn.py
  keras/src/layers/rnn/rnn_test.py
  keras/src/layers/rnn/simple_rnn.py
  keras/src/layers/rnn/stacked_rnn_cells.py
  keras/src/layers/rnn/time_distributed.py
  keras/src/models/sequential.py
  keras/src/testing/test_case.py
  keras/src/utils/jax_layer.py
Labels: size:M, awaiting review

#21007 Fix typos and add a test case for elastic_transform
  keras/src/backend/tensorflow/image.py
  keras/src/backend/torch/image.py
  keras/src/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20940 [OpenVINO backend]: Support numpy.bincount
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:S, awaiting review

#20913 [OpenVINO backend] Support numpy.argsort
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:S, awaiting review

#21014 Fix incorrect argument in JAX flash attention.
  keras/src/backend/jax/nn.py
Labels: ready to pull, size:XS, awaiting review

#21019 Restore variables on `fit()` interrupt with Jax backend
  keras/src/backend/jax/trainer.py
Labels: ready to pull, size:M

#21008 [OpenVINO backend] Support numpy.full_like
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:S

#21010 [OpenVINO backend] Support numpy.empty
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:XS, awaiting review

#21023 `mlx` - data adapters and saving
  keras/src/backend/mlx/core.py
  keras/src/saving/saving_api_test.py
  keras/src/saving/serialization_lib_test.py
  keras/src/trainers/data_adapters/array_slicing.py
  keras/src/trainers/data_adapters/data_adapter_utils.py
  keras/src/trainers/data_adapters/tf_dataset_adapter.py
Labels: kokoro:force-run, ready to pull, size:S

#21018 Add RandomElasticTransform layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/backend/tensorflow/image.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_elastic_transform.py
  keras/src/layers/preprocessing/image_preprocessing/random_elastic_transform_test.py
Labels: ready to pull, size:L, awaiting review

#21033 Make `import_test.py` debuggable from console output.
  integration_tests/import_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#21032 Make code compatible with Numpy >= 2.1.
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/torch/image.py
Labels: ready to pull, size:XS, awaiting review

#21034 Fix bitwise `left_shift` and `right_shift` result dtype...
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21038 [OpenVINO Backend] Get back tests for exp and expand_dims to precommit
  keras/src/backend/openvino/excluded_concrete_tests.txt
Labels: kokoro:force-run, ready to pull, size:XS

#21036 [Documentation] Updated Binary Focal Crossentropy Loss Docstring
  keras/src/losses/losses.py
Labels: kokoro:force-run, ready to pull, size:S

#21049 Fix optree regsitration
  keras/src/tree/optree_impl.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21056 Fix typo in Lion optimizer
  keras/src/optimizers/lion.py
Labels: kokoro:force-run, ready to pull, size:XS

#21053 Add support for torch tensors on meta device
  keras/src/backend/tests/device_scope_test.py
  keras/src/backend/torch/core.py
Labels: kokoro:force-run, ready to pull, size:XS

#21024 feat: add Categorical Generalized Cross Entropy (GCE) loss
  keras/api/_tf_keras/keras/losses/__init__.py
  keras/api/losses/__init__.py
  keras/src/losses/losses.py
  keras/src/losses/losses_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#21063 Fix torch gpu tests
  keras/src/backend/tests/device_scope_test.py
Labels: kokoro:force-run, ready to pull, size:S

#21022 Introduce weights sharding
  keras/src/models/model.py
  keras/src/saving/saving_api.py
  keras/src/saving/saving_api_test.py
  keras/src/saving/saving_lib.py
  keras/src/saving/saving_lib_test.py
Labels: size:L, awaiting review

#21067 Remove the empty H5 groups in `H5IOStore`
  keras/src/saving/saving_lib.py
Labels: kokoro:force-run, ready to pull, size:M

#21072 Allow synchronization value to be set on Variables
  keras/src/backend/common/variables.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/tensorflow/distribute_test.py
  keras/src/metrics/metric.py
Labels: ready to pull, size:M

#21074 Add pre-commit hooks
  .github/workflows/actions.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  keras/src/optimizers/muon.py
  requirements.txt
  shell/api_gen.sh
  shell/format.sh
  shell/lint.sh
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21077 Use tf.int32.min rather than relying on integer overflow
  keras/src/backend/tensorflow/numpy.py
Labels: ready to pull, size:XS

#21020 various numpy_test changes
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21081 Special handling of Torch DDP in callback
  keras/src/callbacks/callback.py
Labels: kokoro:force-run, ready to pull, size:S

#21079 fix muon document
  keras/src/optimizers/muon.py
  keras/src/optimizers/muon_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#21042 [OpenVINO backend] Support numpy.log10
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:S

#20705 Raise error if inputs are not connected with output in functional model
  keras/src/backend/tensorflow/saved_model_test.py
  keras/src/ops/function.py
  keras/src/ops/function_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21093 Version bump to 3.9.1
  keras/src/version.py
Labels: ready to pull, size:XS, awaiting review

#21048 [OpenVino BackEnd] support np.log2 for ov BackEnd
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21095 Fix `Model.export` to Saved Model for models with dict inputs.
  keras/src/export/export_utils.py
  keras/src/export/saved_model_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21101 Fix scatter_update bug for torch
  keras/src/backend/torch/core.py
Labels: ready to pull, size:XS, awaiting review

#21100 Resolve two bugs in keras.callbacks.ModelCheckpoint
  keras/src/callbacks/model_checkpoint.py
Labels: kokoro:force-run, ready to pull, size:M

#21102 Add verification to remat tests.
  keras/src/layers/layer_test.py
Labels: ready to pull, size:M, awaiting review

#21094 Fix Remat error when called with a model
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
  keras/src/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review, Gemma

#21106 `TrackingTest` no longer assigns None to variables
  keras/src/utils/tracking_test.py
Labels: kokoro:force-run, ready to pull, size:XS
