Repository keras-team/keras, pull requests merged in 2025-07, with the labels that each got.

#21438 Fix `rms_normalization` and `layer_normalization` to ensure consistent precision in computations.
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#21449 Ensures mask kwarg is used for output mask propagation
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21453 Implement cbrt function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: ready to pull, size:M

#21407 update a small feature in __getitem__ for openvino backend
  keras/src/backend/openvino/core.py
Labels: size:S

#21414 Improve error message for class_weight with PyTorch DataLoaders
  keras/src/trainers/data_adapters/__init__.py
Labels: kokoro:force-run, ready to pull, keras-team-review-pending, size:XS, awaiting review

#21317 [OpenVINO backend] Update `ndim` behavior
  keras/src/backend/openvino/numpy.py
Labels: size:XS, awaiting review

#21464 fix argument description for on_train_batch callbacks in LambdaCallback
  keras/src/callbacks/lambda_callback.py
Labels: kokoro:force-run, ready to pull, size:XS

#21475 Pin onnxscript version to `0.3.1`.
  requirements-common.txt
Labels: kokoro:force-run, ready to pull, size:XS

#21436 [OpenVINO backend] support tob_k and enable tests
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/excluded_tests.txt
  keras/src/backend/openvino/math.py
Labels: size:M

#21411 [OpenVINO backend] supporting mul with bools
  keras/src/backend/openvino/core.py
Labels: size:XS

#21480 Fix LogSumExp Implementation for OpenVINO backend.
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/math.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#21471 Adds int4 quantization support to EinsumDense
  keras/src/layers/core/dense.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
Labels: ready to pull, size:L, awaiting review, Gemma

#21499 Fix RandAugment behavior in tf graph mode
  keras/src/layers/preprocessing/image_preprocessing/rand_augment.py
  keras/src/layers/preprocessing/image_preprocessing/rand_augment_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21501 Support shape -1 for `slice` op in the jax backend
  keras/src/backend/jax/core.py
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:S

#21503 Docs - Fixed Syntax Error in vectorized_map function example
  keras/src/ops/core.py
Labels: kokoro:force-run, ready to pull, size:XS

#21493 docs: enhance clarity and consistency in README by correcting platform capitalization
  README.md
Labels: kokoro:force-run, ready to pull, size:XS

#21490 Update compute_output_spec method to support cbrt operation
  keras/src/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21415 `mlx` - more changes to tests to pass CI
  examples/demo_custom_mlx_workflow.py
  keras/src/layers/preprocessing/stft_spectrogram_test.py
  keras/src/ops/nn_test.py
  keras/src/trainers/trainer_test.py
Labels: size:M, awaiting review

#21408 [OpenVINO backend] support tri, triu, and tril
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:M, awaiting review

#21494 Add Grain integration.
  keras/src/backend/common/keras_tensor.py
  keras/src/backend/jax/trainer.py
  keras/src/trainers/data_adapters/__init__.py
  keras/src/trainers/data_adapters/data_adapter.py
  keras/src/trainers/data_adapters/data_adapter_utils.py
  keras/src/trainers/data_adapters/grain_dataset_adapter.py
  keras/src/trainers/data_adapters/grain_dataset_adapter_test.py
  keras/src/trainers/data_adapters/tf_dataset_adapter.py
  keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
  keras/src/trainers/data_adapters/torch_data_loader_adapter.py
  keras/src/trainers/data_adapters/torch_data_loader_adapter_test.py
  keras/src/trainers/trainer_test.py
  requirements-common.txt
Labels: ready to pull, size:L, awaiting review

#21498 [OpenVINO backend] fix numpy conversions
  keras/src/backend/openvino/core.py
Labels: size:S

#21496 [OpenVINO backend] fix_transpose
  keras/src/backend/openvino/numpy.py
Labels: size:XS

#21495 [OpenVINO backend] add supporting for lists and tuples in get_ov_output
  keras/src/backend/openvino/core.py
Labels: size:XS

#21252 Keras <> NNX integration
  .github/workflows/actions.yml
  .github/workflows/config/jax/keras.json
  integration_tests/import_test.py
  keras/api/_tf_keras/keras/config/__init__.py
  keras/api/config/__init__.py
  keras/src/backend/common/variables.py
  keras/src/backend/config.py
  keras/src/backend/jax/__init__.py
  keras/src/backend/jax/core.py
  keras/src/backend/jax/core_test.py
  keras/src/backend/jax/layer.py
  keras/src/backend/jax/trainer.py
  keras/src/layers/layer.py
  keras/src/ops/function.py
  keras/src/ops/operation.py
  keras/src/optimizers/base_optimizer.py
  requirements.txt
Labels: size:M, awaiting review

#21505 fix torch module wrapper serialization error
  keras/src/utils/torch_utils.py
  keras/src/utils/torch_utils_test.py
Labels: size:S, awaiting review

#21512 Fix `_can_use_flash_attention`.
  keras/src/backend/jax/nn.py
Labels: kokoro:force-run, ready to pull, size:S

#21456 Fix: UpSampling2D bilinear set_image_data_format(channels_first) bug
  keras/src/layers/reshaping/up_sampling2d.py
  keras/src/layers/reshaping/up_sampling2d_test.py
Labels: ready to pull, size:S, awaiting review

#21526 [OpenVINO backend] fix openvino model exported names to match keras names
  keras/src/export/openvino.py
Labels: ready to pull, size:S

#21527 Update flax
  .github/workflows/actions.yml
Labels: kokoro:force-run, ready to pull, size:XS

#21532 Bug fix with serialization when walking through operations.
  keras/src/saving/saving_lib.py
Labels: ready to pull, size:XS

#21535 Version bump 3.11.1
  keras/src/saving/saving_lib.py
  keras/src/version.py
Labels: ready to pull, size:XS, awaiting review
