Repository keras-team/keras, pull requests merged in 2025-01, with the labels that each got.

#20709 fix: Torch MPS backend failing test
  keras/src/utils/backend_utils_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20704 implement transform_bounding_boxes for random_shear
  keras/src/layers/preprocessing/image_preprocessing/random_shear.py
  keras/src/layers/preprocessing/image_preprocessing/random_shear_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20714 Update BackupAndRestore class example
  keras/src/callbacks/backup_and_restore.py
Labels: kokoro:force-run, ready to pull, size:XS

#20710 Refactor `keras/src/export/export_lib` and add `export_onnx`
  .kokoro/github/ubuntu/gpu/build.sh
  keras/api/_tf_keras/keras/export/__init__.py
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/export/__init__.py
  keras/api/layers/__init__.py
  keras/src/backend/torch/export.py
  keras/src/export/__init__.py
  keras/src/export/export_utils.py
  keras/src/export/onnx.py
  keras/src/export/onnx_test.py
  keras/src/export/saved_model.py
  keras/src/export/saved_model_test.py
  keras/src/export/tfsm_layer.py
  keras/src/export/tfsm_layer_test.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/core/embedding_test.py
  keras/src/layers/layer.py
  keras/src/models/model.py
  keras/src/models/model_test.py
  keras/src/utils/module_utils.py
  requirements-common.txt
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:XL

#20725 Patch `tf2onnx` to ensure compatibility with `numpy>=2.0.0`
  keras/src/export/onnx.py
  keras/src/export/saved_model.py
  keras/src/export/tf2onnx_lib.py
  requirements-common.txt
Labels: kokoro:force-run, ready to pull, size:M

#20729 Add build method to supress warning
  keras/src/layers/preprocessing/image_preprocessing/random_color_jitter.py
Labels: kokoro:force-run, ready to pull, size:S

#20728 Specified window_length dtype requirement in tf.keras.ops.istft in math.py
  keras/src/ops/math.py
Labels: kokoro:force-run, ready to pull, size:XS

#20716 Add rand_augment processing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/rand_augment.py
  keras/src/layers/preprocessing/image_preprocessing/rand_augment_test.py
  keras/src/layers/preprocessing/image_preprocessing/random_brightness_test.py
  keras/src/layers/preprocessing/image_preprocessing/random_rotation.py
Labels: ready to pull, size:L, awaiting review

#20674 Fixing batch_dim_name attribute
  keras/src/backend/jax/distribution_lib.py
  keras/src/backend/jax/distribution_lib_test.py
  keras/src/backend/jax/trainer.py
  keras/src/distribution/distribution_lib.py
  keras/src/distribution/distribution_lib_test.py
Labels: ready to pull, size:S, Gemma

#20732 Add support for `dtype` / `DTypePolicy` to `JaxLayer` and `FlaxLayer`.
  keras/src/backend/jax/export.py
  keras/src/layers/layer.py
  keras/src/utils/jax_layer.py
  keras/src/utils/jax_layer_test.py
Labels: ready to pull, size:M, awaiting review

#20736 Allow dynamic shape in `STFTSpectrogram` layer.
  keras/src/layers/preprocessing/stft_spectrogram.py
  keras/src/layers/preprocessing/stft_spectrogram_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20735 Remove duplicate export tests in `model_test`.
  keras/src/models/model_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20739 Add OpenVINO into README.md
  README.md
Labels: kokoro:force-run, ready to pull, size:XS

#20738 Multiple Example Title has been removed in metrics.MeanIoU method
  keras/src/metrics/iou_metrics.py
Labels: ready to pull, size:XS, awaiting review

#20741 merge master
  README.md
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/backend/jax/distribution_lib.py
  keras/src/backend/jax/distribution_lib_test.py
  keras/src/backend/jax/export.py
  keras/src/backend/jax/trainer.py
  keras/src/distribution/distribution_lib.py
  keras/src/distribution/distribution_lib_test.py
  keras/src/layers/__init__.py
  keras/src/layers/layer.py
  keras/src/layers/preprocessing/image_preprocessing/rand_augment.py
  keras/src/layers/preprocessing/image_preprocessing/rand_augment_test.py
  keras/src/layers/preprocessing/image_preprocessing/random_brightness_test.py
  keras/src/layers/preprocessing/image_preprocessing/random_rotation.py
  keras/src/layers/preprocessing/stft_spectrogram.py
  keras/src/layers/preprocessing/stft_spectrogram_test.py
  keras/src/metrics/iou_metrics.py
  keras/src/models/model_test.py
  keras/src/ops/math.py
  keras/src/utils/jax_layer.py
  keras/src/utils/jax_layer_test.py
Labels: size:L

#20749 Fix JAX GPU CI and make formatter happy
  examples/demo_custom_torch_workflow.py
  examples/demo_torch_multi_gpu.py
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/nn.py
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/linalg.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/callbacks/csv_logger.py
  keras/src/callbacks/swap_ema_weights_test.py
  keras/src/export/export_utils.py
  keras/src/export/onnx.py
  keras/src/layers/activations/leaky_relu.py
  keras/src/layers/attention/grouped_query_attention.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/layers/convolutional/base_conv.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/embedding.py
  keras/src/layers/layer.py
  keras/src/layers/normalization/layer_normalization_test.py
  keras/src/layers/preprocessing/hashed_crossing.py
  keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py
  keras/src/layers/preprocessing/integer_lookup.py
  keras/src/layers/preprocessing/string_lookup.py
  keras/src/layers/preprocessing/text_vectorization.py
  keras/src/metrics/metric.py
  keras/src/ops/image.py
  keras/src/ops/linalg.py
  keras/src/ops/numpy.py
  keras/src/random/seed_generator.py
  keras/src/saving/file_editor.py
  keras/src/testing/test_case.py
  keras/src/trainers/compile_utils.py
  keras/src/utils/dataset_utils.py
  keras/src/utils/jax_layer_test.py
  keras/src/utils/model_visualization.py
Labels: kokoro:force-run, ready to pull, size:XS

#20751 Added checks to serialization.
  keras/src/models/functional.py
  keras/src/saving/serialization_lib.py
Labels: kokoro:force-run, ready to pull, size:S

#20745 feat(ops): Add keras.ops.numpy.rot90 operation (#20723)
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20756 Fix flaky `JaxLayer` test.
  keras/src/utils/jax_layer_test.py
Labels: ready to pull, size:XS, awaiting review

#20755 Fix serialization of domain packages.
  keras/src/saving/serialization_lib.py
Labels: ready to pull, size:XS, awaiting review

#20757 Preliminary parts needed for ragged support, including densification.
  keras/src/backend/common/keras_tensor.py
  keras/src/backend/common/keras_tensor_test.py
  keras/src/backend/jax/__init__.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/__init__.py
  keras/src/backend/numpy/core.py
  keras/src/backend/openvino/__init__.py
  keras/src/backend/openvino/core.py
  keras/src/backend/tensorflow/__init__.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/torch/__init__.py
  keras/src/backend/torch/core.py
  keras/src/layers/core/input_layer.py
  keras/src/layers/core/input_layer_test.py
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: ready to pull, size:M, awaiting review

#20758 Implemented more generic asset tracking mechanism in saved model export.
  keras/src/export/saved_model.py
  keras/src/export/saved_model_test.py
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20733 [Keras Ops] Add einops-style `rearrange()` to `keras.ops`
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/ops/einops.py
  keras/src/ops/einops_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20762 Remove all type annotations for consistency.
  keras/src/backend/common/backend_utils.py
  keras/src/backend/common/dtypes_test.py
  keras/src/backend/common/variables_test.py
  keras/src/backend/torch/layer.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/bounding_box.py
  keras/src/ops/core_test.py
  keras/src/ops/image_test.py
  keras/src/ops/math_test.py
  keras/src/ops/nn_test.py
  keras/src/ops/numpy_test.py
  keras/src/random/random_test.py
  keras/src/saving/saving_lib_test.py
  keras/src/visualization/draw_segmentation_masks.py
  keras/src/wrappers/sklearn_test.py
  keras/src/wrappers/sklearn_wrapper.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20641 Porting TF fake_quant_with_min_max functions
  keras/api/_tf_keras/keras/quantizers/__init__.py
  keras/api/quantizers/__init__.py
  keras/src/quantizers/__init__.py
  keras/src/quantizers/quantizers.py
  keras/src/quantizers/quantizers_test.py
Labels: kokoro:force-run, ready to pull, size:XL, awaiting review

#20759 Add aug_mix processing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/aug_mix.py
  keras/src/layers/preprocessing/image_preprocessing/aug_mix_test.py
Labels: ready to pull, size:L, awaiting review

#20767 `JaxLayer` now uses the global dtype policy by default.
  keras/src/utils/jax_layer.py
Labels: ready to pull, size:XS, awaiting review

#20768 fix(ops): Fix issue with map_coordinates for uint8 dtype
  keras/src/backend/tensorflow/image.py
  keras/src/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20775 Multiple Example Title has been removed in metrics.BinaryIoU
  keras/src/metrics/iou_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#20777 mlx fft implementation
  keras/src/backend/mlx/math.py
Labels: kokoro:force-run, ready to pull, size:XS

#20774 fix(ops): Fix inconsistent padding calculation in PyTorch backend ops
  keras/src/backend/torch/nn.py
  keras/src/layers/pooling/average_pooling_test.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20772 Improve `fake_quant_with_min_max_vars`
  keras/api/_tf_keras/keras/quantizers/__init__.py
  keras/api/quantizers/__init__.py
  keras/src/quantizers/quantizers.py
  keras/src/quantizers/quantizers_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20779 Fix memory leaks in `model.evaluate`.
  keras/src/backend/jax/trainer.py
  keras/src/backend/numpy/trainer.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/backend/torch/trainer.py
  keras/src/callbacks/callback_list.py
Labels: ready to pull, size:S

#20781 mlx - implement `fft2`, `rfft`, and `irfft` and fix `fft`
  keras/src/backend/mlx/math.py
Labels: kokoro:force-run, ready to pull, size:S

#20786 mlx - `rnn`
  keras/src/backend/mlx/linalg.py
  keras/src/backend/mlx/numpy.py
  keras/src/backend/mlx/rnn.py
Labels: ready to pull, size:L

#20785 fix(applications): Improve validation and error handling for ConvNeXt weights and fix broadcasting in EfficientNetV2
  keras/src/applications/convnext.py
  keras/src/applications/efficientnet_v2.py
Labels: kokoro:force-run, ready to pull, size:S

#20784 fix ciou implementation bug in bounding_boxes/iou.py
  keras/src/layers/preprocessing/image_preprocessing/bounding_boxes/iou.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#20776 Add cut_mix processing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/cut_mix.py
  keras/src/layers/preprocessing/image_preprocessing/cut_mix_test.py
Labels: ready to pull, size:L, awaiting review

#20787 Add random_invert layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_invert.py
  keras/src/layers/preprocessing/image_preprocessing/random_invert_test.py
Labels: ready to pull, size:M

#20782 fix(metrics): Fix BinaryAccuracy metric to handle boolean inputs
  keras/src/metrics/reduction_metrics.py
  keras/src/metrics/reduction_metrics_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20792 `mlx.nn.conv` implementation
  keras/src/backend/mlx/nn.py
Labels: kokoro:force-run, ready to pull, size:M

#20791 Fix issue with Masking layer with Tensor as `mask_value`
  keras/src/layers/core/masking.py
  keras/src/layers/core/masking_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20807 `mlx` - more conv
  keras/src/backend/common/backend_utils.py
  keras/src/backend/mlx/nn.py
Labels: kokoro:force-run, ready to pull, size:M

#20805 extract metrics update logic into a helper method
  keras/src/backend/jax/trainer.py
Labels: kokoro:force-run, ready to pull, size:M

#20803 Refactoring: turn the attribute `_return_attention_scores` into an argument
  keras/src/layers/attention/multi_head_attention.py
Labels: kokoro:force-run, ready to pull, size:XS

#20798 Add random_erasing layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_erasing.py
  keras/src/layers/preprocessing/image_preprocessing/random_erasing_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20797 fix torch backend resize with `pad_to_aspectio_ratio` is set to `True`
  keras/src/backend/numpy/image.py
  keras/src/backend/torch/image.py
  keras/src/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20796 Update fill_mode argument default value in RandomZoom class
  keras/src/layers/preprocessing/image_preprocessing/random_zoom.py
Labels: kokoro:force-run, ready to pull, size:XS

#20808 fix(ops): Handle floating-point edge cases in ops.argmax()
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20811 implement remaining functions in `mlx.nn.py` excluding pooling
  keras/src/backend/mlx/core.py
  keras/src/backend/mlx/linalg.py
  keras/src/backend/mlx/nn.py
  keras/src/backend/mlx/rnn.py
Labels: kokoro:force-run, ready to pull, size:L

#20812 fix(ops): Fix ops.argmin() handling of subnormal float values in Keras backends
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20816 implement remaining functions in `mlx.numpy.py`
  keras/src/backend/mlx/linalg.py
  keras/src/backend/mlx/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20817 Add random_gaussian_blur layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_gaussian_blur.py
  keras/src/layers/preprocessing/image_preprocessing/random_gaussian_blur_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20815 fix(layers): Fix incorrect masked mean/variance in BatchNormalization layer
  keras/src/layers/normalization/batch_normalization.py
  keras/src/layers/normalization/batch_normalization_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20814 Add max_pool and average_pool for MLX
  keras/src/backend/mlx/nn.py
Labels: kokoro:force-run, ready to pull, size:M

#20819 mlx - fix error with loading models with h5 and update `mlx.core.while_loop`
  keras/src/backend/mlx/core.py
Labels: kokoro:force-run, ready to pull, size:S

#20825 mlx - patch for pytest to run
  keras/src/backend/__init__.py
  keras/src/backend/mlx/__init__.py
  keras/src/backend/mlx/export.py
  keras/src/backend/mlx/nn.py
  keras/src/export/saved_model.py
Labels: kokoro:force-run, ready to pull, size:S

#20824 Fix for deserializing custom functions serialized with Keras <= 3.6.
  keras/src/saving/serialization_lib.py
  keras/src/saving/serialization_lib_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20827 Fix jax version
  requirements-jax-cuda.txt
Labels: kokoro:force-run, ready to pull, size:XS

#20828 Fix CI breakage with torch-xla.
  requirements.txt
Labels: ready to pull, size:XS

#20821 Add `signbit` and fix `argmin` and `argmax`
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
  keras/src/testing/test_case.py
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:L

#20834 Pin version of torch-xla to 2.5.1.
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: ready to pull, size:S

#20832 mlx - `nn` and `core` updates post merge
  keras/src/backend/mlx/__init__.py
  keras/src/backend/mlx/core.py
  keras/src/backend/mlx/nn.py
  keras/src/backend/mlx/rnn.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/ops/core_test.py
  keras/src/ops/nn_test.py
  model.keras
Labels: kokoro:force-run, ready to pull, size:L

#20829 fix(trainers): Add support for DistributedDatasetsFromFunction in data adapters
  keras/src/trainers/data_adapters/__init__.py
  keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review
