Repository keras-team/keras, pull requests merged in 2025-02, with the labels that each got.

#20843 feat(linalg): support eigh on mlx
  keras/src/backend/mlx/linalg.py
Labels: kokoro:force-run, ready to pull, size:XL

#20845 [OpenVINO backend] Provide more granular tests exclusion mechanism
  conftest.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/excluded_tests.txt
Labels: kokoro:force-run, ready to pull, size:M

#20846 Use Python 3.10 for testing environment
  .github/workflows/actions.yml
  .github/workflows/nightly.yml
  .kokoro/github/ubuntu/gpu/build.sh
  keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
  requirements-jax-cuda.txt
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20852 rolling back #20827
  requirements-jax-cuda.txt
Labels: size:XS

#20851 Don't duplicate frozen parameters during predict()
  keras/src/backend/jax/trainer.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20853 provided y_true or y_pred add labels for plot image gallery method
  keras/src/visualization/plot_image_gallery.py
Labels: kokoro:force-run, ready to pull, size:S

#20856 MLX segment_sum and segment_max implementation
  keras/src/backend/mlx/math.py
Labels: kokoro:force-run, ready to pull, size:S

#20854 Fix convnext to work with any custom input tensors
  keras/src/applications/applications_test.py
  keras/src/applications/convnext.py
Labels: kokoro:force-run, ready to pull, size:S

#20859 Prevent information leakage and improve the ONNX export for the torch backend
  keras/src/export/onnx.py
  keras/src/export/saved_model.py
  keras/src/models/model.py
  keras/src/utils/torch_utils.py
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:M

#20743 Add Rematerialization to Keras
  keras/__init__.py
  keras/api/__init__.py
  keras/api/_tf_keras/keras/__init__.py
  keras/src/backend/common/remat.py
  keras/src/backend/common/remat_test.py
  keras/src/backend/jax/core.py
  keras/src/backend/numpy/core.py
  keras/src/backend/openvino/core.py
  keras/src/backend/tensorflow/core.py
  keras/src/backend/torch/core.py
  keras/src/layers/layer.py
  keras/src/layers/layer_test.py
  keras/src/ops/operation.py
Labels: size:M, awaiting review, Gemma

#20836 Add random_perspective layer
  keras/api/_tf_keras/keras/layers/__init__.py
  keras/api/layers/__init__.py
  keras/src/layers/__init__.py
  keras/src/layers/preprocessing/image_preprocessing/random_perspective.py
  keras/src/layers/preprocessing/image_preprocessing/random_perspective_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review

#20865 Clear JAX state sharding after `fit`, `evaluate` and `predict`.
  keras/src/backend/jax/trainer.py
Labels: ready to pull, size:S

#20863 add backticks to docstring string code keywords
  keras/src/backend/common/remat.py
Labels: size:S

#20867 fix(layers): Update Conv2D docstring to clarify numerical precision across backends
  keras/src/layers/convolutional/conv2d.py
Labels: kokoro:force-run, ready to pull, size:S

#20868 Remove `torchvision` dep and simplify `resize` and `rgb_to_grayscale` in torch backend
  integration_tests/import_test.py
  keras/src/backend/torch/image.py
  keras/src/utils/module_utils.py
  requirements-common.txt
  requirements-jax-cuda.txt
  requirements-tensorflow-cuda.txt
  requirements-torch-cuda.txt
  requirements.txt
Labels: kokoro:force-run, ready to pull, size:L

#20765 fix time_distributed layer with mask and partial_batch_size
  keras/src/layers/rnn/time_distributed.py
  keras/src/layers/rnn/time_distributed_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20877 Fix Torch GPU CI
  keras/src/layers/preprocessing/image_preprocessing/random_perspective.py
Labels: kokoro:force-run, ready to pull, size:S

#20879 [Fix] solve method on linalg
  keras/src/backend/tensorflow/linalg.py
Labels: kokoro:force-run, ready to pull, size:XS

#20862 mlx - passing most layers tests
  keras/src/backend/mlx/core.py
  keras/src/backend/mlx/image.py
  keras/src/backend/mlx/linalg.py
  keras/src/backend/mlx/math.py
  keras/src/backend/mlx/nn.py
  keras/src/backend/mlx/numpy.py
  keras/src/backend/mlx/random.py
  keras/src/layers/attention/grouped_query_attention_test.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/layer_test.py
  keras/src/layers/merging/merging_test.py
  keras/src/layers/preprocessing/image_preprocessing/random_crop.py
  keras/src/layers/preprocessing/stft_spectrogram_test.py
  keras/src/layers/reshaping/up_sampling2d_test.py
  keras/src/ops/image_test.py
  keras/src/random/random_test.py
  keras/src/utils/tf_utils.py
  model.keras
Labels: ready to pull, size:XL

#20883 [OpenVINO backend] Support numpy.amax and numpy.amin
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#20889 `HashedCrossing` layer preserves the static batch size when known.
  keras/src/layers/preprocessing/hashed_crossing.py
  keras/src/layers/preprocessing/hashed_crossing_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20892 `TextVectorization` with `output_sequence_length` returns outputs wit…
  keras/src/layers/preprocessing/text_vectorization.py
  keras/src/layers/preprocessing/text_vectorization_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20882 fix(ops): Fix TensorFlow backend keras.ops.rot90 shape transformation and improve test coverage
  keras/src/backend/tensorflow/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20905 fix ifft2 op with TF backend
  keras/src/backend/tensorflow/math.py
Labels: kokoro:force-run, ready to pull, size:XS

#20896 docs: add params to Sequential.pop docstring
  keras/src/models/sequential.py
Labels: kokoro:force-run, ready to pull, size:XS

#20906 Always allow `ExportArchive.track` to track TensorFlow resources.
  keras/src/backend/jax/export.py
  keras/src/backend/tensorflow/export.py
  keras/src/backend/torch/export.py
  keras/src/export/saved_model.py
  keras/src/export/saved_model_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#20901 Add iterations property to LossScaleOptimizer
  keras/src/optimizers/loss_scale_optimizer.py
  keras/src/optimizers/loss_scale_optimizer_test.py
Labels: size:S

#20907 `mlx` - `stft`, `istft`, and dtype handling in `numpy.py`
  keras/src/backend/mlx/__init__.py
  keras/src/backend/mlx/linalg.py
  keras/src/backend/mlx/math.py
  keras/src/backend/mlx/numpy.py
  keras/src/ops/linalg_test.py
  keras/src/ops/math_test.py
  keras/src/ops/numpy_test.py
Labels: size:L

#20909 Implementation of rot90 and unravel_index functions for MLX backend
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:M

#20888 Fix cloning with compiled sequential model
  keras/src/models/cloning.py
  keras/src/models/cloning_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20899 Add perspective_transform for ops
  keras/api/_tf_keras/keras/ops/image/__init__.py
  keras/api/ops/image/__init__.py
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/tensorflow/image.py
  keras/src/backend/torch/image.py
  keras/src/ops/image.py
  keras/src/ops/image_test.py
Labels: size:L, awaiting review

#20915 Update random_perspective to use ops.perspective_transform
  keras/src/backend/jax/image.py
  keras/src/layers/preprocessing/image_preprocessing/random_perspective.py
  keras/src/layers/preprocessing/image_preprocessing/random_perspective_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20923 Only load OpenVINO excludes file when backend is "openvino".
  conftest.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20924 Fix `masking_test.py` saving a file in the current folder.
  keras/src/layers/core/masking_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#20926 Recognize placer as a remote location
  keras/src/utils/file_utils.py
  keras/src/utils/file_utils_test.py
Labels: kokoro:force-run, ready to pull, size:S

#20921 [OpenVINO backend] Support arctan2. (#29010)
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#20927 `mlx` - numpy.searchsorted and numpy.historgram implemented
  .github/workflows/actions.yml
  integration_tests/mlx_custom_fit_test.py
  keras/src/backend/common/dtypes_test.py
  keras/src/backend/mlx/core.py
  keras/src/backend/mlx/numpy.py
  keras/src/backend/mlx/trainer.py
Labels: kokoro:force-run, ready to pull, size:M

#20929 [OpenVINO Backend] Include NumpyDtype tests
  keras/src/backend/openvino/excluded_concrete_tests.txt
Labels: kokoro:force-run, ready to pull, size:M

#20932 Remove unused dependency
  requirements-common.txt
Labels: ready to pull, size:XS, awaiting review

#20935 Fix failing jax remat test
  keras/src/layers/layer_test.py
Labels: kokoro:force-run, ready to pull

#20930 [Keras Ops] Add `keras.ops.polar` operation
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20934 [OpenVino BackEnd]Support np.average OV BE
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:S

#20941 [Openvino Backend] support numpy.arange, modify dtype check
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:S

#20954 Fix mean metrics to allow dict/list inputs
  keras/src/metrics/reduction_metrics.py
Labels: ready to pull, size:XS, awaiting review

#20900 Fix tril/triu ops
  keras/src/backend/tensorflow/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20956 Fix `BinaryAccuracy` to handle boolean inputs.
  keras/src/metrics/accuracy_metrics.py
  keras/src/metrics/reduction_metrics.py
Labels: ready to pull, size:S, awaiting review

#20957 `mlx` - trainer update for compilation and data adapters
  keras/src/backend/common/dtypes_test.py
  keras/src/backend/common/variables_test.py
  keras/src/backend/mlx/__init__.py
  keras/src/backend/mlx/core.py
  keras/src/backend/mlx/numpy.py
  keras/src/backend/mlx/random.py
  keras/src/backend/mlx/trainer.py
  keras/src/callbacks/tensorboard_test.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/preprocessing/image_preprocessing/cut_mix.py
  keras/src/layers/preprocessing/image_preprocessing/equalization.py
  keras/src/layers/preprocessing/image_preprocessing/mix_up.py
  keras/src/layers/preprocessing/normalization.py
  keras/src/losses/loss_test.py
  keras/src/trainers/data_adapters/array_data_adapter.py
  keras/src/trainers/data_adapters/array_data_adapter_test.py
  keras/src/trainers/data_adapters/array_slicing.py
  keras/src/trainers/data_adapters/data_adapter_utils.py
  keras/src/trainers/data_adapters/generator_data_adapter.py
  keras/src/trainers/data_adapters/generator_data_adapter_test.py
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
  keras/src/trainers/data_adapters/tf_dataset_adapter.py
  keras/src/trainers/data_adapters/tf_dataset_adapter_test.py
  keras/src/trainers/data_adapters/torch_data_loader_adapter.py
  keras/src/trainers/data_adapters/torch_data_loader_adapter_test.py
  keras/src/trainers/trainer_test.py
  keras/src/utils/module_utils.py
Labels: kokoro:force-run, ready to pull, size:L

#20948 Support diagflat, solve and fix trunc function
  keras/src/backend/mlx/linalg.py
  keras/src/backend/mlx/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20943 Add gaussian_blur for image
  keras/api/_tf_keras/keras/ops/image/__init__.py
  keras/api/ops/image/__init__.py
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/tensorflow/image.py
  keras/src/backend/torch/image.py
  keras/src/ops/image.py
  keras/src/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:L

#20928 [OpenVINO backend] Support arctan2, pass the NumpyDtypeTest::arctan2 test
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/ops/numpy_test.py
Labels: size:S, awaiting review

#20958 Update the RandomGaussianBlur layer to utilize the image layer method
  keras/src/backend/jax/image.py
  keras/src/layers/preprocessing/image_preprocessing/random_gaussian_blur.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#20972 Add `antialias` to `layers.Resizing` and add more tests.
  keras/src/layers/preprocessing/image_preprocessing/resizing.py
  keras/src/layers/preprocessing/image_preprocessing/resizing_test.py
Labels: kokoro:force-run, ready to pull, size:M

#20973 fix legacy model saving & reloading with axis argument in its layer
  keras/src/legacy/saving/legacy_h5_format_test.py
  keras/src/legacy/saving/saving_utils.py
Labels: kokoro:force-run, ready to pull, size:S

#20974 Refactor gaussian_blur in numpy to utilize scipy.signal.convolve2d
  keras/src/backend/numpy/image.py
Labels: kokoro:force-run, ready to pull, size:S

#20945 [OpenVino BackEnd]support np.count_nonzero for ov BackEnd
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: size:S, awaiting review
