Repository keras-team/keras, pull requests merged in 2025-06, with the labels that each got.

#21341 Ensures consistent serialization for Functional model
  keras/src/models/functional.py
  keras/src/models/functional_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21334 Make ops consistent and test ops consistency.
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/nn.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/core.py
  keras/src/backend/numpy/math.py
  keras/src/backend/numpy/nn.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/image.py
  keras/src/backend/openvino/math.py
  keras/src/backend/openvino/nn.py
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/nn.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/math.py
  keras/src/backend/torch/nn.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/core.py
  keras/src/ops/image.py
  keras/src/ops/math.py
  keras/src/ops/math_test.py
  keras/src/ops/nn.py
  keras/src/ops/numpy.py
  keras/src/ops/ops_test.py
Labels: kokoro:force-run, ready to pull, size:L

#21340 Fix comment
  keras/src/layers/pooling/average_pooling2d.py
Labels: kokoro:force-run, ready to pull, size:XS

#21349 Fix callback
  keras/src/callbacks/model_checkpoint.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21347 [OpenVINO Backend] support __rpow__ for OpenVINOKerasTensor
  keras/src/backend/openvino/core.py
Labels: kokoro:force-run, ready to pull, size:XS

#21353 [OpenVINO Backend] enable core tests
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/excluded_tests.txt
Labels: kokoro:force-run, ready to pull, size:S

#21348 [OpenVINO Backend] support comparison ops (>, <, <=, >=, ==, !=) for OpenVINOKerasTensor
  keras/src/backend/openvino/core.py
Labels: kokoro:force-run, ready to pull, size:M

#21358 Make `dtype` a static parameter of `OnesLike` and `ZerosLike`.
  keras/src/ops/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#21360 Allow `ops_test.py` to run with the `api` folder collapsed at the root.
  keras/src/ops/ops_test.py
Labels: ready to pull, size:XS, awaiting review

#21361 [OpenVINO Backend] update slice method
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
Labels: kokoro:force-run, ready to pull, size:S

#21367 Move `_dtype_policy` from `Operation` to `Layer`.
  keras/src/layers/layer.py
  keras/src/ops/operation.py
  keras/src/ops/operation_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21333 Re-apply Fixed issue with dot_product_attention when using TPU. #21254 after addressing cuDNN/FlashAttention API updates
  keras/src/backend/jax/nn.py
Labels: size:M, awaiting review, Gemma

#21370 Add implementation of precision-recall gain AUC
  keras/src/metrics/confusion_metrics.py
  keras/src/metrics/confusion_metrics_test.py
  keras/src/metrics/metrics_utils.py
Labels: ready to pull, size:M

#21372 Implement corrcoef function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21352 Raise warning when rms_scaling = True
  keras/src/layers/normalization/layer_normalization.py
  keras/src/ops/nn.py
Labels: ready to pull, size:S, awaiting review

#21385 Fix SKLearnClassifier and SKLearnRegressor examples
  keras/src/wrappers/sklearn_wrapper.py
Labels: kokoro:force-run, ready to pull, size:S

#21383 Update output_padding argument in convolution transpose layer
  keras/src/layers/convolutional/base_conv_transpose.py
  keras/src/layers/convolutional/conv1d_transpose.py
  keras/src/layers/convolutional/conv2d_transpose.py
  keras/src/layers/convolutional/conv3d_transpose.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21393 Fix numpy upgrade error
  keras/src/layers/rnn/rnn.py
Labels: ready to pull, size:XS

#21399 Add support for multiple dynamic dimensions to `Flatten` layer on TF.
  keras/src/layers/reshaping/flatten.py
  keras/src/layers/reshaping/flatten_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21387 Fix missing and fragile scikit-learn imports in Keras sklearn wrappers
  keras/src/wrappers/fixes.py
  keras/src/wrappers/sklearn_wrapper.py
  keras/src/wrappers/utils.py
Labels: ready to pull, size:S

#21400 Remove references to jax.experimental.layout.Layout.
  keras/src/backend/jax/distribution_lib.py
  keras/src/backend/jax/distribution_lib_test.py
Labels: ready to pull, size:XS, awaiting review

#21392 Fix crash when `sys.stdout.encoding` is `None`
  keras/src/utils/io_utils.py
Labels: kokoro:force-run, ready to pull, size:XS

#21369 [OpenVINO Backend] support while_loop
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/ops/core_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21359 [OpenVINO Backend] update __getitem__
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/excluded_tests.txt
  keras/src/ops/core_test.py
Labels: size:M, awaiting review

#21406 Add "format" support for latest JAX.
  keras/src/backend/jax/distribution_lib.py
Labels: ready to pull, size:XS

#21428 Fix symbolic call of `logsumexp` with int axis.
  keras/src/ops/math_test.py
  keras/src/ops/operation_utils.py
Labels: ready to pull, size:XS

#21430 Support non-tf.data.Dataset instances in multi-host setting.
  keras/src/distribution/distribution_lib.py
  keras/src/trainers/data_adapters/__init__.py
Labels: ready to pull, size:M, awaiting review

#21440 MLX small changes
  keras/src/backend/mlx/linalg.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:S
