Repository keras-team/keras, pull requests merged in 2025-09, with the labels that each got.

#21615 Store defaults of optional arguments in auto-config
  keras/src/ops/operation.py
  keras/src/ops/operation_test.py
Labels: kokoro:force-run, ready to pull, size:S

#21628 GPTQ refactor, GPU optimization, speedup, and test enhancements
  keras/src/models/model.py
  keras/src/models/model_test.py
  keras/src/quantizers/gptq.py
  keras/src/quantizers/gptq_config.py
  keras/src/quantizers/gptq_core.py
  keras/src/quantizers/gptq_core_test.py
  keras/src/quantizers/gptq_quant.py
  keras/src/quantizers/gptq_test.py
  keras/src/quantizers/quantizers.py
  keras/src/quantizers/quantizers_test.py
Labels: size:XL, awaiting review

#21633 Implement kron function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21611 Fix issue with concatenate, masking and symbolic inputs
  keras/src/layers/merging/concatenate.py
  keras/src/layers/merging/merging_test.py
Labels: ready to pull, size:S, awaiting review

#21652 Allow `searchsorted` to take a dynamically sized tensor.
  keras/src/backend/numpy/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: ready to pull, size:S, awaiting review

#21650 fix: use canonicalize_axis function in reduce_shape function
  keras/src/ops/operation_utils.py
  keras/src/ops/operation_utils_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#21646 Fix Torch ONNX export not respecting InputSpec.name
  keras/src/export/onnx.py
  keras/src/export/onnx_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#21641 Adds Native GPTQ Layer, Runtime Execution, and Serialization Support
  keras/api/_tf_keras/keras/dtype_policies/__init__.py
  keras/api/dtype_policies/__init__.py
  keras/src/dtype_policies/__init__.py
  keras/src/dtype_policies/dtype_policy.py
  keras/src/dtype_policies/dtype_policy_test.py
  keras/src/layers/core/dense.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/layers/core/embedding.py
  keras/src/layers/layer.py
  keras/src/models/model.py
  keras/src/quantizers/gptq.py
  keras/src/quantizers/gptq_config.py
  keras/src/quantizers/gptq_config_test.py
  keras/src/quantizers/gptq_core.py
  keras/src/quantizers/gptq_core_test.py
  keras/src/quantizers/gptq_test.py
  keras/src/quantizers/quantizers.py
  keras/src/quantizers/quantizers_test.py
Labels: kokoro:force-run, ready to pull, size:L, awaiting review, Gemma

#21680 Do not use `os.path.join` for variable paths.
  keras/src/backend/common/variables.py
  keras/src/backend/common/variables_test.py
Labels: ready to pull, size:XS, awaiting review

#21682 Do not use `os.path.sep` to detect `/` in names.
  keras/src/ops/operation.py
Labels: ready to pull, size:XS, awaiting review

#21672 Use JAX DimExpr for dynamic shapes in `compute_output_spec`.
  keras/src/backend/common/variables.py
  keras/src/backend/jax/core.py
  keras/src/backend/tests/compute_output_spec_test.py
Labels: ready to pull, size:M, awaiting review

#21671 Fix test failure in guides writing_your_own_callbacks.py
  guides/writing_your_own_callbacks.py
Labels: kokoro:force-run, ready to pull, size:XS

#21686 Adds 4-bit packing support to GPTQ Quantization
  keras/src/layers/core/dense.py
  keras/src/layers/core/dense_test.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/einsum_dense_test.py
  keras/src/quantizers/gptq.py
  keras/src/quantizers/gptq_core.py
  keras/src/quantizers/gptq_test.py
  keras/src/quantizers/quantizers.py
  keras/src/quantizers/quantizers_test.py
Labels: ready to pull, size:L, awaiting review

#21693 Fixes float64 type promotion issue
  keras/src/backend/common/dtypes.py
  keras/src/backend/common/dtypes_test.py
Labels: kokoro:force-run, ready to pull, size:S

#21694 Ensures compiled metrics resolve output names correctly
  keras/src/trainers/compile_utils.py
  keras/src/trainers/compile_utils_test.py
Labels: size:M, awaiting review

#21667 [Keras 3 OpenVINO Backend]: Support numpy.median operation
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:M
