Repository keras-team/keras, pull requests merged in 2025-05, with the labels that each got.

#21224 Fix stacked RNN with mask in JAX & Numpy backends
  keras/src/backend/jax/rnn.py
  keras/src/backend/numpy/rnn.py
  keras/src/layers/rnn/stacked_rnn_cells_test.py
Labels: kokoro:force-run, ready to pull, size:S

#21231 Openvino numpy ravel
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#21244 `mlx` - remat and continued test updates
  keras/src/backend/mlx/core.py
  keras/src/dtype_policies/dtype_policy_map_test.py
  keras/src/initializers/constant_initializers_test.py
  keras/src/layers/attention/grouped_query_attention_test.py
  keras/src/layers/attention/multi_head_attention_test.py
  keras/src/layers/layer_test.py
  keras/src/models/model_test.py
  keras/src/ops/linalg_test.py
  keras/src/ops/nn_test.py
  keras/src/quantizers/quantizers_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21239 Make `take_along_axis` with TF backend compilable.
  keras/src/backend/tensorflow/numpy.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21235 Implement blackman function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21246 Add NotImplementedError for angle & bartlett on openvino
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#21247 Interleave optimizer variable creation to restore backward-compatibility
  keras/src/optimizers/adadelta.py
  keras/src/optimizers/adafactor.py
  keras/src/optimizers/adam.py
  keras/src/optimizers/adamax.py
  keras/src/optimizers/base_optimizer.py
  keras/src/optimizers/ftrl.py
  keras/src/optimizers/lamb.py
  keras/src/optimizers/nadam.py
Labels: kokoro:force-run, ready to pull, size:M

#21221 [Keras Ops] view_as_complex() and view_as_real()
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/ops/__init__.py
  keras/src/ops/math.py
  keras/src/ops/math_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21256 Fix `take_along_axis` with TensorFlow with non-int32 indices.
  keras/src/backend/tensorflow/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S

#21254 Fixed issue with dot_product_attention when using TPU.
  keras/src/backend/jax/nn.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21243 Bug fixes in `plot_model` with nested models.
  integration_tests/model_visualization_test.py
  keras/src/utils/model_visualization.py
Labels: kokoro:force-run, ready to pull, size:L

#21260 Several linalg functions support
  keras/src/backend/mlx/linalg.py
Labels: kokoro:force-run, ready to pull, size:M

#21248 Simplify the logic of `quantize` and float8 build.
  keras/src/layers/core/dense.py
  keras/src/layers/core/einsum_dense.py
  keras/src/layers/core/embedding.py
  keras/src/layers/layer.py
Labels: ready to pull, size:M, awaiting review

#21261 Initialize random seed for distributed models.
  keras/src/backend/jax/distribution_lib.py
  keras/src/utils/rng_utils.py
Labels: size:M

#21257 Add openvino backend support for numpy.hstack
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21262 Increment optimizer._iterations in apply(...).
  keras/src/backend/jax/optimizer.py
  keras/src/optimizers/base_optimizer.py
Labels: kokoro:force-run, ready to pull, size:S

#21263 Add support for jax.experimental.layout layouts.
  keras/src/backend/jax/distribution_lib.py
  keras/src/backend/jax/distribution_lib_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21264 Allow variable layout to be set on construction.
  keras/src/backend/common/variables.py
  keras/src/backend/jax/core.py
  keras/src/optimizers/base_optimizer.py
Labels: kokoro:force-run, ready to pull, size:S

#21273 Implement hamming function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21281 [OpenVINO Backend] support reciprocal
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#21277 Fixed RandomGrayscall.call for single unbatched image.
  keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py
  keras/src/layers/preprocessing/image_preprocessing/random_grayscale_test.py
Labels: ready to pull, size:S, awaiting review

#21269 Implementation np.moveaxis function
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21217 Add an easy way to run a script for a few steps only
  keras/api/_tf_keras/keras/config/__init__.py
  keras/api/config/__init__.py
  keras/src/backend/config.py
  keras/src/backend/jax/trainer.py
  keras/src/backend/tensorflow/trainer.py
  keras/src/backend/torch/trainer.py
  keras/src/trainers/epoch_iterator.py
  keras/src/trainers/trainer_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21293 update JAX GPU version
  .kokoro/github/ubuntu/gpu/build.sh
  requirements-jax-cuda.txt
Labels: kokoro:force-run, ready to pull, size:XS

#21302 Revert "Add sparse support to `ops.ones_like` and `ops.zeros_like`."
  keras/src/backend/jax/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21270 Implementation np.outer function
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#21299 Use ops.add for bias addition in EinsumDense
  keras/src/layers/core/einsum_dense.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#21297 [OpenVINO Backend] update ops.stack to support tuples
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:XS

#21291 Update layer.py add_loss to properly handle when input loss is a list…
  keras/src/layers/layer.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#21296 [OpenVINO Backend] support ops.split
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#21290 Update layer.py add_metric error message
  keras/src/layers/layer.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#21303 Implement kaiser function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: ready to pull, size:M

#21307 Bump up minimum version of python to 3.10.
  CONTRIBUTING.md
  pyproject.toml
Labels: kokoro:force-run, ready to pull, size:XS

#21275 Fix for issue #21118: inconsistent behavior across callbacks
  keras/src/callbacks/__init__.py
  keras/src/callbacks/early_stopping.py
  keras/src/callbacks/model_checkpoint.py
  keras/src/callbacks/model_checkpoint_test.py
  keras/src/callbacks/monitor_callback.py
  keras/src/callbacks/monitor_callback_test.py
  keras/src/callbacks/reduce_lr_on_plateau.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21304 Fixed missing axis annotation in tf map_coordinates
  keras/src/backend/tensorflow/image.py
  keras/src/ops/image_test.py
Labels: kokoro:force-run, ready to pull, size:XS

#21312 Updated random_grayscale.py compute_output_spec
  keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py
Labels: ready to pull, size:XS, awaiting review

#21315 Modified confusion_metrics.py
  keras/src/metrics/confusion_metrics.py
Labels: kokoro:force-run, ready to pull, size:XS

#21318 Implement hanning function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21326 Updated random_grayscale.py compute_output_spec
  keras/src/layers/preprocessing/image_preprocessing/random_grayscale.py
Labels: kokoro:force-run, ready to pull, size:XS, awaiting review

#21327 add ops.layer_normalization
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/nn/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/nn/__init__.py
  keras/src/layers/normalization/layer_normalization.py
  keras/src/ops/nn.py
  keras/src/ops/nn_test.py
Labels: ready to pull, size:M

#21329 Revert "Fixed issue with dot_product_attention when using TPU. "
  keras/src/backend/jax/nn.py
Labels: ready to pull, size:M, awaiting review

#21330 `PyDataset` now implements `__iter__`.
  keras/src/trainers/data_adapters/py_dataset_adapter.py
  keras/src/trainers/data_adapters/py_dataset_adapter_test.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21337 Increase coverage in optimizers
  keras/src/optimizers/adamw_test.py
  keras/src/optimizers/ftrl_test.py
  keras/src/optimizers/lion_test.py
  keras/src/optimizers/nadam_test.py
  keras/src/optimizers/sgd_test.py
Labels: kokoro:force-run, ready to pull, size:M
