Repository keras-team/keras, pull requests merged in 2025-08, with the labels that each got.

#21545 [OpenVINO backend] fix __getitem__ and convert_to_tensor issues
  keras/src/backend/openvino/core.py
Labels: kokoro:force-run, ready to pull, size:S

#21538 Implement isneginf function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: ready to pull, size:M, awaiting review

#21553 Force computation and data placement on the CPU when using a Grain data pipeline.
  keras/src/backend/jax/distribution_lib.py
  keras/src/backend/torch/core.py
  keras/src/layers/preprocessing/image_preprocessing/resizing_test.py
  keras/src/layers/preprocessing/rescaling_test.py
  keras/src/layers/preprocessing/tf_data_layer.py
  keras/src/utils/backend_utils.py
Labels: kokoro:force-run, ready to pull, size:M

#21552 Add assume_unique and invert arguments to keras.ops.isin
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21418 [OpenVINO backend] Remove usage of deprecated `openvino.runtime`
  keras/src/backend/openvino/core.py
  keras/src/backend/openvino/math.py
  keras/src/backend/openvino/nn.py
  keras/src/backend/openvino/numpy.py
  keras/src/backend/openvino/random.py
  keras/src/backend/openvino/trainer.py
Labels: size:S, awaiting review

#21506 docs: Keras 3 evaluate() and compiled metrics clarification
  keras/src/trainers/trainer.py
Labels: kokoro:force-run, ready to pull, size:S, awaiting review

#21432 It worth not hiding exceptions
  keras/src/backend/jax/nn.py
Labels: ready to pull, size:S, awaiting review

#21524 [OpenVINO backend] Support numpy.deg2rad
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: kokoro:force-run, ready to pull, size:S

#21565 Fix nnx object state
  .github/workflows/actions.yml
  keras/src/ops/operation.py
Labels: kokoro:force-run, ready to pull, size:XS

#21570 Version bump 3.11.2 and nnx fix #21565
  .github/workflows/actions.yml
  keras/src/ops/operation.py
  keras/src/version.py
Labels: ready to pull, size:S

#21571 update version number
  keras/src/version.py
Labels: ready to pull, size:XS, awaiting review

#21554 Added cholesky inverse operation to all the backends
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/linalg/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/linalg/__init__.py
  keras/src/backend/jax/linalg.py
  keras/src/backend/numpy/linalg.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/linalg.py
  keras/src/backend/tensorflow/linalg.py
  keras/src/backend/torch/linalg.py
  keras/src/ops/linalg.py
  keras/src/ops/linalg_test.py
Labels: ready to pull, size:M, awaiting review

#21575 Disable `torch.load` in `TorchModuleWrapper` when in safe mode.
  keras/src/utils/torch_utils.py
  keras/src/utils/torch_utils_test.py
Labels: kokoro:force-run, ready to pull, size:M, awaiting review

#21588 [JAX] Fix breakage due to default dtype handling in ctc_loss.
  keras/src/backend/jax/nn.py
Labels: ready to pull, size:S

#21590 Improve deserialization error about `@register_keras_serializable`.
  keras/src/saving/serialization_lib.py
Labels: kokoro:force-run, ready to pull, size:S

#21587 Fix the `vocabulary_dtype` in `keras.layers.IntegerLookup()`
  keras/src/layers/preprocessing/integer_lookup.py
Labels: kokoro:force-run, ready to pull, size:XS

#21597 Make `vectorized_map` op serializable.
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/ops/core.py
  keras/src/ops/core_test.py
Labels: ready to pull, size:S, awaiting review

#21602 Propagate `safe_mode` flag to legacy h5 loading code.
  keras/src/layers/core/lambda_layer.py
  keras/src/legacy/saving/legacy_h5_format.py
  keras/src/legacy/saving/legacy_h5_format_test.py
  keras/src/legacy/saving/saving_utils.py
  keras/src/legacy/saving/serialization.py
  keras/src/saving/saving_api.py
  keras/src/saving/saving_lib_test.py
  keras/src/saving/serialization_lib.py
  keras/src/saving/serialization_lib_test.py
  keras/src/utils/torch_utils.py
Labels: ready to pull, size:M, awaiting review

#21603 Fix GRU with return_state=True on tf backend with cuda
  keras/src/backend/tensorflow/rnn.py
  keras/src/layers/rnn/gru_test.py
Labels: kokoro:force-run, ready to pull, size:S

#21548 Fix support for optional inputs in model.fit
  keras/src/backend/tensorflow/trainer.py
  keras/src/models/model_test.py
  keras/src/trainers/data_adapters/array_data_adapter.py
  keras/src/trainers/data_adapters/data_adapter_utils.py
  keras/src/trainers/data_adapters/generator_data_adapter.py
  keras/src/trainers/data_adapters/grain_dataset_adapter.py
  keras/src/trainers/data_adapters/tf_dataset_adapter.py
  keras/src/trainers/data_adapters/torch_data_loader_adapter.py
  keras/src/tree/dmtree_impl.py
  keras/src/tree/optree_impl.py
  keras/src/tree/tree_api.py
Labels: size:M

#21607 Version bump to 3.11.3
  keras/src/backend/tensorflow/rnn.py
  keras/src/layers/core/lambda_layer.py
  keras/src/layers/rnn/gru_test.py
  keras/src/legacy/saving/legacy_h5_format.py
  keras/src/legacy/saving/legacy_h5_format_test.py
  keras/src/legacy/saving/saving_utils.py
  keras/src/legacy/saving/serialization.py
  keras/src/saving/saving_api.py
  keras/src/saving/saving_lib_test.py
  keras/src/saving/serialization_lib.py
  keras/src/saving/serialization_lib_test.py
  keras/src/utils/torch_utils.py
  keras/src/utils/torch_utils_test.py
  keras/src/version.py
Labels: ready to pull, size:M

#21606 Implement hypot function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: size:M, awaiting review

#21604 Remove the usage of `JAX_DEFAULT_DTYPE_BITS` and the tests for 64-bit dtypes.
  conftest.py
  keras/src/backend/common/dtypes.py
  keras/src/backend/common/dtypes_test.py
  keras/src/backend/common/variables_test.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/torch/nn.py
  keras/src/constraints/constraints.py
  keras/src/initializers/constant_initializers.py
  keras/src/initializers/constant_initializers_test.py
  keras/src/layers/preprocessing/stft_spectrogram_test.py
  keras/src/ops/core_test.py
  keras/src/ops/math_test.py
  keras/src/ops/nn_test.py
  keras/src/ops/numpy_test.py
  keras/src/optimizers/adam_test.py
  keras/src/optimizers/adamax_test.py
  keras/src/optimizers/adamw_test.py
  keras/src/optimizers/lamb_test.py
  keras/src/optimizers/nadam_test.py
  keras/src/optimizers/schedules/learning_rate_schedule.py
  keras/src/random/random_test.py
Labels: kokoro:force-run, ready to pull, size:L

#21568 Proposed fix for issue #21519: Reshape layer does not handle -1 shape…
  keras/src/layers/reshaping/reshape.py
  keras/src/layers/reshaping/reshape_test.py
Labels: ready to pull, size:S, awaiting review

#21621 Update excluded_concrete_tests.txt
  keras/src/backend/jax/image.py
  keras/src/backend/numpy/image.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/tensorflow/image.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/image.py
  keras/src/ops/image_test.py
Labels: size:L

#21625 fix(layers): Fix IntegerLookup docstring output shape documentation and add test coverage
  keras/src/layers/preprocessing/integer_lookup.py
  keras/src/layers/preprocessing/integer_lookup_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21619 Create styleguide.md for keras
  .gemini/styleguide.md
Labels: kokoro:force-run, ready to pull, size:L

#21623 Implement gcd function in keras.ops
  keras/api/_tf_keras/keras/ops/__init__.py
  keras/api/_tf_keras/keras/ops/numpy/__init__.py
  keras/api/ops/__init__.py
  keras/api/ops/numpy/__init__.py
  keras/src/backend/jax/numpy.py
  keras/src/backend/numpy/numpy.py
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
  keras/src/backend/tensorflow/numpy.py
  keras/src/backend/torch/numpy.py
  keras/src/ops/numpy.py
  keras/src/ops/numpy_test.py
Labels: kokoro:force-run, ready to pull, size:M

#21600 Add meshgrid op support in Keras OpenVINO backend
  keras/src/backend/openvino/excluded_concrete_tests.txt
  keras/src/backend/openvino/numpy.py
Labels: ready to pull, size:M, awaiting review, backend:OpenVino
